{
  "boxplot_5aedc4.py": {
    "base_stats": {
      "total_parameters": 79,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 79,
      "parameters_with_annotations": 63
    },
    "base_error_count": 0,
    "llm_error_count": 5,
    "base_errors": [],
    "llm_errors": [
      "boxplot_5aedc4.py:176: error: Argument \"return_type\" to \"_plot\" of \"BoxPlot\" has incompatible type \"Optional[Literal['axes', 'dict', 'both']]\"; expected \"Literal['axes', 'dict', 'both']\"  [arg-type]",
      "boxplot_5aedc4.py:177: error: Argument 1 to \"maybe_color_bp\" of \"BoxPlot\" has incompatible type \"Union[Any, str, Dict[str, Any]]\"; expected \"Dict[str, Any]\"  [arg-type]",
      "boxplot_5aedc4.py:184: error: Argument \"return_type\" to \"_plot\" of \"BoxPlot\" has incompatible type \"Optional[Literal['axes', 'dict', 'both']]\"; expected \"Literal['axes', 'dict', 'both']\"  [arg-type]",
      "boxplot_5aedc4.py:185: error: Argument 1 to \"maybe_color_bp\" of \"BoxPlot\" has incompatible type \"Union[Any, str, Dict[str, Any]]\"; expected \"Dict[str, Any]\"  [arg-type]",
      "boxplot_5aedc4.py:245: error: List item 0 has incompatible type \"Optional[str]\"; expected \"str\"  [list-item]",
      "Found 5 errors in 1 file (checked 1 source file)"
    ]
  },
  "create_user_36a545.py": {
    "base_stats": {
      "total_parameters": 40,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 40,
      "parameters_with_annotations": 40
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "create_user_36a545.py:320: error: Dict entry 3 has incompatible type \"str\": \"bool\"; expected \"str\": \"Collection[str]\"  [dict-item]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "create_user_5beae0.py": {
    "base_stats": {
      "total_parameters": 39,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 39,
      "parameters_with_annotations": 39
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "create_user_5beae0.py:117: error: Incompatible types in assignment (expression has type \"None\", variable has type \"str\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "headers_cc92a5.py": {
    "base_stats": {
      "total_parameters": 43,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 43,
      "parameters_with_annotations": 30
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "headers_cc92a5.py:83: error: Overloaded function implementation does not accept all possible arguments of signature 1  [misc]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "httpclient_e36adc.py": {
    "base_stats": {
      "total_parameters": 87,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 87,
      "parameters_with_annotations": 61
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "httpclient_e36adc.py:490: error: Unsupported target for indexed assignment (\"Union[Any, Dict[str, str], None]\")  [index]",
      "httpclient_e36adc.py:500: error: Incompatible types in assignment (expression has type \"Union[str, bytes, None]\", variable has type \"bytes\")  [assignment]",
      "httpclient_e36adc.py:515: error: Incompatible types in assignment (expression has type \"Optional[bool]\", variable has type \"bool\")  [assignment]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "networks_4fcfb8.py": {
    "base_stats": {
      "total_parameters": 72,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 72,
      "parameters_with_annotations": 42
    },
    "base_error_count": 9,
    "llm_error_count": 5,
    "base_errors": [
      "networks_4fcfb8.py:87: error: Need type annotation for \"hidden_parts\" (hint: \"hidden_parts: Set[<type>] = ...\")  [var-annotated]",
      "networks_4fcfb8.py:242: error: Incompatible types in assignment (expression has type \"Set[str]\", base class \"AnyUrl\" defined the type as \"None\")  [assignment]",
      "networks_4fcfb8.py:255: error: Incompatible types in assignment (expression has type \"Set[str]\", base class \"AnyUrl\" defined the type as \"None\")  [assignment]",
      "networks_4fcfb8.py:291: error: Incompatible types in assignment (expression has type \"Set[str]\", base class \"AnyUrl\" defined the type as \"None\")  [assignment]",
      "networks_4fcfb8.py:296: error: Incompatible types in assignment (expression has type \"Set[str]\", base class \"AnyUrl\" defined the type as \"None\")  [assignment]",
      "networks_4fcfb8.py:300: error: Incompatible types in assignment (expression has type \"Set[str]\", base class \"AnyUrl\" defined the type as \"None\")  [assignment]",
      "networks_4fcfb8.py:305: error: Incompatible types in assignment (expression has type \"Set[str]\", base class \"AnyUrl\" defined the type as \"None\")  [assignment]",
      "networks_4fcfb8.py:313: error: Incompatible types in assignment (expression has type \"Set[str]\", base class \"AnyUrl\" defined the type as \"None\")  [assignment]",
      "networks_4fcfb8.py:320: error: Incompatible types in assignment (expression has type \"Set[str]\", base class \"AnyUrl\" defined the type as \"None\")  [assignment]",
      "Found 9 errors in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "networks_4fcfb8.py:259: error: Expected keyword arguments, {...}, or dict(...) in TypedDict constructor  [misc]",
      "networks_4fcfb8.py:385: error: Incompatible types in assignment (expression has type \"object\", variable has type \"Optional[str]\")  [assignment]",
      "networks_4fcfb8.py:426: error: TypedDict key must be a string literal; expected one of (\"scheme\", \"user\", \"password\", \"host\", \"tld\", ...)  [literal-required]",
      "networks_4fcfb8.py:525: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"str\")  [assignment]",
      "networks_4fcfb8.py:533: error: Dict entry 3 has incompatible type \"str\": \"bool\"; expected \"str\": \"Optional[str]\"  [dict-item]",
      "Found 5 errors in 1 file (checked 1 source file)"
    ]
  },
  "query_object_6550f7.py": {
    "base_stats": {
      "total_parameters": 30,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 30,
      "parameters_with_annotations": 12
    },
    "base_error_count": 4,
    "llm_error_count": 1,
    "base_errors": [
      "query_object_6550f7.py:25: error: Unexpected keyword argument \"old_name\" for \"DeprecatedField\"  [call-arg]",
      "query_object_6550f7.py:25: error: Unexpected keyword argument \"new_name\" for \"DeprecatedField\"  [call-arg]",
      "query_object_6550f7.py:26: error: Unexpected keyword argument \"old_name\" for \"DeprecatedField\"  [call-arg]",
      "query_object_6550f7.py:26: error: Unexpected keyword argument \"new_name\" for \"DeprecatedField\"  [call-arg]",
      "Found 4 errors in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "query_object_6550f7.py:128: error: Invalid index type \"str\" for \"Union[str, Dict[str, Any]]\"; expected type \"Union[SupportsIndex, slice]\"  [index]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "trainer_test_f0df2a.py": {
    "base_stats": {
      "total_parameters": 110,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 114,
      "parameters_with_annotations": 48
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "trainer_test_f0df2a.py:1264: error: Invalid index type \"int\" for \"Dict[str, Any]\"; expected type \"str\"  [index]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "xml_da8497.py": {
    "base_stats": {
      "total_parameters": 58,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 58,
      "parameters_with_annotations": 42
    },
    "base_error_count": 0,
    "llm_error_count": 8,
    "base_errors": [],
    "llm_errors": [
      "xml_da8497.py:401: error: Argument 1 to \"_parse_doc\" of \"_EtreeFrameParser\" has incompatible type \"Union[str, PathLike[Any], StringIO, BytesIO]\"; expected \"Union[str, bytes, StringIO, BytesIO]\"  [arg-type]",
      "xml_da8497.py:446: error: Incompatible types in assignment (expression has type \"List[Element]\", variable has type \"List[str]\")  [assignment]",
      "xml_da8497.py:463: error: Argument \"filepath_or_buffer\" to \"get_data_from_filepath\" has incompatible type \"Union[str, bytes, StringIO, BytesIO]\"; expected \"Union[str, PathLike[Any], StringIO, BytesIO]\"  [arg-type]",
      "xml_da8497.py:485: error: Argument 1 to \"_parse_doc\" of \"_LxmlFrameParser\" has incompatible type \"Union[str, PathLike[Any], StringIO, BytesIO]\"; expected \"Union[str, bytes, StringIO, BytesIO]\"  [arg-type]",
      "xml_da8497.py:539: error: Argument \"filepath_or_buffer\" to \"get_data_from_filepath\" has incompatible type \"Union[str, bytes, StringIO, BytesIO]\"; expected \"Union[str, PathLike[Any], StringIO, BytesIO]\"  [arg-type]",
      "xml_da8497.py:683: error: Argument 11 to \"_LxmlFrameParser\" has incompatible type \"Union[str, PathLike[Any], StringIO, BytesIO, None]\"; expected \"Union[str, StringIO, BytesIO, None]\"  [arg-type]",
      "xml_da8497.py:693: error: Incompatible types in assignment (expression has type \"_EtreeFrameParser\", variable has type \"_LxmlFrameParser\")  [assignment]",
      "xml_da8497.py:704: error: Argument 11 to \"_EtreeFrameParser\" has incompatible type \"Union[str, PathLike[Any], StringIO, BytesIO, None]\"; expected \"Union[str, StringIO, BytesIO, None]\"  [arg-type]",
      "Found 8 errors in 1 file (checked 1 source file)"
    ]
  },
  "account_dbed71.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 47,
      "parameters_with_annotations": 18
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "account_dbed71.py:78: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "account_dbed71.py:170: error: Incompatible types in assignment (expression has type \"float\", variable has type \"int\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "bias_metrics_5f20ad.py": {
    "base_stats": {
      "total_parameters": 39,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 39,
      "parameters_with_annotations": 24
    },
    "base_error_count": 0,
    "llm_error_count": 11,
    "base_errors": [],
    "llm_errors": [
      "bias_metrics_5f20ad.py:127: error: Incompatible return value type (got \"Tensor\", expected \"FloatTensor\")  [return-value]",
      "bias_metrics_5f20ad.py:378: error: Incompatible types in assignment (expression has type \"Callable[[int], Dict[int, FloatTensor]]\", variable has type \"Callable[[int], FloatTensor]\")  [assignment]",
      "bias_metrics_5f20ad.py:483: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]",
      "bias_metrics_5f20ad.py:484: error: Result type of / incompatible in assignment  [misc]",
      "bias_metrics_5f20ad.py:486: error: Incompatible return value type (got \"Tensor\", expected \"FloatTensor\")  [return-value]",
      "bias_metrics_5f20ad.py:493: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]",
      "bias_metrics_5f20ad.py:494: error: Incompatible types in assignment (expression has type \"Tensor\", target has type \"FloatTensor\")  [assignment]",
      "bias_metrics_5f20ad.py:499: error: Incompatible return value type (got \"Tensor\", expected \"FloatTensor\")  [return-value]",
      "bias_metrics_5f20ad.py:501: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]",
      "bias_metrics_5f20ad.py:503: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]",
      "bias_metrics_5f20ad.py:507: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]",
      "Found 11 errors in 1 file (checked 1 source file)"
    ]
  },
  "cover_860401.py": {
    "base_stats": {
      "total_parameters": 21,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 21,
      "parameters_with_annotations": 7
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "cover_860401.py:172: error: Incompatible types in assignment (expression has type \"float\", variable has type \"Optional[int]\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "metrics_b562d7.py": {
    "base_stats": {
      "total_parameters": 60,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 60,
      "parameters_with_annotations": 34
    },
    "base_error_count": 0,
    "llm_error_count": 9,
    "base_errors": [],
    "llm_errors": [
      "metrics_b562d7.py:55: error: Argument \"group\" to \"Gauge\" has incompatible type \"Optional[Any]\"; expected \"str\"  [arg-type]",
      "metrics_b562d7.py:56: error: Argument \"name\" to \"Gauge\" has incompatible type \"Optional[Any]\"; expected \"str\"  [arg-type]",
      "metrics_b562d7.py:89: error: List comprehension has incompatible type List[Optional[Gauge]]; expected List[Gauge]  [misc]",
      "metrics_b562d7.py:140: error: Argument \"group\" to \"Counter\" has incompatible type \"Optional[Any]\"; expected \"str\"  [arg-type]",
      "metrics_b562d7.py:141: error: Argument \"name\" to \"Counter\" has incompatible type \"Optional[Any]\"; expected \"str\"  [arg-type]",
      "metrics_b562d7.py:182: error: List comprehension has incompatible type List[Optional[Counter]]; expected List[Counter]  [misc]",
      "metrics_b562d7.py:241: error: Argument \"group\" to \"Timer\" has incompatible type \"Optional[Any]\"; expected \"str\"  [arg-type]",
      "metrics_b562d7.py:242: error: Argument \"name\" to \"Timer\" has incompatible type \"Optional[Any]\"; expected \"str\"  [arg-type]",
      "metrics_b562d7.py:294: error: List comprehension has incompatible type List[Optional[Timer]]; expected List[Timer]  [misc]",
      "Found 9 errors in 1 file (checked 1 source file)"
    ]
  },
  "notify_1817bd.py": {
    "base_stats": {
      "total_parameters": 43,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 43,
      "parameters_with_annotations": 33
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "notify_1817bd.py:147: error: Too few arguments  [call-arg]",
      "notify_1817bd.py:158: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"str\")  [assignment]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "random_033806.py": {
    "base_stats": {
      "total_parameters": 37,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 37,
      "parameters_with_annotations": 37
    },
    "base_error_count": 0,
    "llm_error_count": 6,
    "base_errors": [],
    "llm_errors": [
      "random_033806.py:173: error: Argument 4 to \"randomize_epoch_participation\" has incompatible type \"Optional[Random]\"; expected \"Random\"  [arg-type]",
      "random_033806.py:188: error: Argument 4 to \"randomize_epoch_participation\" has incompatible type \"Optional[Random]\"; expected \"Random\"  [arg-type]",
      "random_033806.py:189: error: Argument 4 to \"randomize_epoch_participation\" has incompatible type \"Optional[Random]\"; expected \"Random\"  [arg-type]",
      "random_033806.py:199: error: Argument 3 to \"set_some_new_deposits\" has incompatible type \"Optional[Random]\"; expected \"Random\"  [arg-type]",
      "random_033806.py:200: error: Argument 3 to \"exit_random_validators\" has incompatible type \"Optional[Random]\"; expected \"Random\"  [arg-type]",
      "random_033806.py:201: error: Argument 3 to \"slash_random_validators\" has incompatible type \"Optional[Random]\"; expected \"Random\"  [arg-type]",
      "Found 6 errors in 1 file (checked 1 source file)"
    ]
  },
  "sensor_51937f.py": {
    "base_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 17
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "sensor_51937f.py:190: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"str\")  [assignment]",
      "sensor_51937f.py:191: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"str\")  [assignment]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_2a092a.py": {
    "base_stats": {
      "total_parameters": 76,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 76,
      "parameters_with_annotations": 46
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "test_2a092a.py:66: error: Incompatible types in assignment (expression has type \"Dict[str, str]\", variable has type \"_Environ[str]\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_cli_3a2b0d.py": {
    "base_stats": {
      "total_parameters": 185,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 185,
      "parameters_with_annotations": 131
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "test_cli_3a2b0d.py:379: error: First argument to namedtuple() should be \"ModuleType\", not \"Module\"  [name-match]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_generic_7cde9d.py": {
    "base_stats": {
      "total_parameters": 56,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 56,
      "parameters_with_annotations": 28
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "test_generic_7cde9d.py:219: error: Argument 2 to \"construct\" has incompatible type \"List[int]\"; expected \"Union[int, Tuple[int, ...]]\"  [arg-type]",
      "test_generic_7cde9d.py:224: error: Argument 2 to \"construct\" has incompatible type \"List[int]\"; expected \"Union[int, Tuple[int, ...]]\"  [arg-type]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_pandas_efa602.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 165,
      "parameters_with_annotations": 95
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "test_pandas_efa602.py:335: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "test_pandas_efa602.py:210: error: Duplicate argument \"using_infer_string\" in function definition",
      "Found 1 error in 1 file (errors prevented further checking)"
    ]
  },
  "test_to_latex_569aaf.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 83,
      "parameters_with_annotations": 83
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "test_to_latex_569aaf.py:276: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "test_to_latex_569aaf.py:358: error: List item 0 has incompatible type \"Tuple[str, str]\"; expected \"str\"  [list-item]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "water_heater_44e018.py": {
    "base_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 6
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "water_heater_44e018.py:63: error: Incompatible types in assignment (expression has type \"Optional[bool]\", variable has type \"bool\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "binary_sensor_2da4f5.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 38,
      "parameters_with_annotations": 21
    },
    "base_error_count": 1,
    "llm_error_count": 3,
    "base_errors": [
      "binary_sensor_2da4f5.py:43: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "binary_sensor_2da4f5.py:170: error: Incompatible return value type (got \"Optional[str]\", expected \"str\")  [return-value]",
      "binary_sensor_2da4f5.py:256: error: Too few arguments  [call-arg]",
      "binary_sensor_2da4f5.py:263: error: Too few arguments  [call-arg]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "ewmh_1d4730.py": {
    "base_stats": {
      "total_parameters": 84,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 84,
      "parameters_with_annotations": 47
    },
    "base_error_count": 0,
    "llm_error_count": 4,
    "base_errors": [],
    "llm_errors": [
      "ewmh_1d4730.py:280: error: List item 1 has incompatible type \"Union[int, str]\"; expected \"int\"  [list-item]",
      "ewmh_1d4730.py:280: error: List item 2 has incompatible type \"Union[int, str]\"; expected \"int\"  [list-item]",
      "ewmh_1d4730.py:383: error: Incompatible return value type (got \"Optional[List[Any]]\", expected \"Optional[str]\")  [return-value]",
      "ewmh_1d4730.py:392: error: Incompatible return value type (got \"Optional[List[Any]]\", expected \"Optional[str]\")  [return-value]",
      "Found 4 errors in 1 file (checked 1 source file)"
    ]
  },
  "fbeta_multi_label_measure_test_75eeda.py": {
    "base_stats": {
      "total_parameters": 44,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 44,
      "parameters_with_annotations": 24
    },
    "base_error_count": 0,
    "llm_error_count": 26,
    "base_errors": [],
    "llm_errors": [
      "fbeta_multi_label_measure_test_75eeda.py:95: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:96: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:97: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:112: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:113: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:114: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:132: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:133: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:134: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:210: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:211: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:212: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:321: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:322: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:337: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:338: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:339: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:355: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:356: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:357: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:373: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:374: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:375: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:391: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:392: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_multi_label_measure_test_75eeda.py:393: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "Found 26 errors in 1 file (checked 1 source file)"
    ]
  },
  "http_server_4a75c7.py": {
    "base_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 13
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "http_server_4a75c7.py:52: error: Incompatible types in assignment (expression has type \"float\", variable has type \"int\")  [assignment]",
      "http_server_4a75c7.py:65: error: Incompatible types in assignment (expression has type \"Optional[int]\", variable has type \"int\")  [assignment]",
      "http_server_4a75c7.py:79: error: Argument 2 to \"send_header\" of \"BaseHTTPRequestHandler\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "interval_941dbf.py": {
    "base_stats": {
      "total_parameters": 96,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 96,
      "parameters_with_annotations": 60
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "interval_941dbf.py:330: error: Incompatible return value type (got \"Tuple[Callable[[Type[IntervalIndex], Dict[str, Any]], IntervalIndex], Tuple[Type[IntervalIndex], Dict[str, Any]], None]\", expected \"Tuple[type, Tuple[type, Dict[str, Any]], None]\")  [return-value]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "parquet_a441a6.py": {
    "base_stats": {
      "total_parameters": 63,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 63,
      "parameters_with_annotations": 55
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "parquet_a441a6.py:355: error: Argument \"compression\" to \"write\" of \"BaseImpl\" has incompatible type \"Optional[Literal['snappy', 'gzip', 'brotli', 'lz4', 'zstd']]\"; expected \"str\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "sampled_softmax_loss_ab8f9c.py": {
    "base_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 19
    },
    "base_error_count": 0,
    "llm_error_count": 5,
    "base_errors": [],
    "llm_errors": [
      "sampled_softmax_loss_ab8f9c.py:90: error: Incompatible types in assignment (expression has type \"Parameter\", variable has type \"Embedding\")  [assignment]",
      "sampled_softmax_loss_ab8f9c.py:91: error: Incompatible types in assignment (expression has type \"Parameter\", variable has type \"Embedding\")  [assignment]",
      "sampled_softmax_loss_ab8f9c.py:140: error: Argument 2 to \"embedding\" has incompatible type \"Embedding\"; expected \"Tensor\"  [arg-type]",
      "sampled_softmax_loss_ab8f9c.py:173: error: Incompatible types in assignment (expression has type \"Embedding\", variable has type \"Tensor\")  [assignment]",
      "sampled_softmax_loss_ab8f9c.py:174: error: Incompatible types in assignment (expression has type \"Embedding\", variable has type \"Tensor\")  [assignment]",
      "Found 5 errors in 1 file (checked 1 source file)"
    ]
  },
  "selector_spec_e2bf19.py": {
    "base_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 18
    },
    "base_error_count": 0,
    "llm_error_count": 4,
    "base_errors": [],
    "llm_errors": [
      "selector_spec_e2bf19.py:66: error: Incompatible types in assignment (expression has type \"str\", variable has type \"IndirectSelection\")  [assignment]",
      "selector_spec_e2bf19.py:99: error: Argument 1 to \"_match_to_int\" has incompatible type \"Dict[str, str]\"; expected \"Match[Any]\"  [arg-type]",
      "selector_spec_e2bf19.py:100: error: Argument 1 to \"_match_to_int\" has incompatible type \"Dict[str, str]\"; expected \"Match[Any]\"  [arg-type]",
      "selector_spec_e2bf19.py:153: error: Incompatible default for argument \"indirect_selection\" (default has type \"str\", argument has type \"IndirectSelection\")  [assignment]",
      "Found 4 errors in 1 file (checked 1 source file)"
    ]
  },
  "sequence_accuracy_test_b352af.py": {
    "base_stats": {
      "total_parameters": 17,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 17,
      "parameters_with_annotations": 11
    },
    "base_error_count": 0,
    "llm_error_count": 12,
    "base_errors": [],
    "llm_errors": [
      "sequence_accuracy_test_b352af.py:98: error: Incompatible types in assignment (expression has type \"List[Tensor]\", variable has type \"Tensor\")  [assignment]",
      "sequence_accuracy_test_b352af.py:99: error: Incompatible types in assignment (expression has type \"List[Tensor]\", variable has type \"Tensor\")  [assignment]",
      "sequence_accuracy_test_b352af.py:100: error: Incompatible types in assignment (expression has type \"List[Tensor]\", variable has type \"Tensor\")  [assignment]",
      "sequence_accuracy_test_b352af.py:102: error: Dict entry 0 has incompatible type \"str\": \"Tensor\"; expected \"str\": \"List[Tensor]\"  [dict-item]",
      "sequence_accuracy_test_b352af.py:103: error: Dict entry 1 has incompatible type \"str\": \"Tensor\"; expected \"str\": \"List[Tensor]\"  [dict-item]",
      "sequence_accuracy_test_b352af.py:104: error: Dict entry 2 has incompatible type \"str\": \"Tensor\"; expected \"str\": \"List[Tensor]\"  [dict-item]",
      "sequence_accuracy_test_b352af.py:136: error: Incompatible types in assignment (expression has type \"List[Tensor]\", variable has type \"Tensor\")  [assignment]",
      "sequence_accuracy_test_b352af.py:137: error: Incompatible types in assignment (expression has type \"List[Tensor]\", variable has type \"Tensor\")  [assignment]",
      "sequence_accuracy_test_b352af.py:138: error: Incompatible types in assignment (expression has type \"List[Tensor]\", variable has type \"Tensor\")  [assignment]",
      "sequence_accuracy_test_b352af.py:140: error: Dict entry 0 has incompatible type \"str\": \"Tensor\"; expected \"str\": \"List[Tensor]\"  [dict-item]",
      "sequence_accuracy_test_b352af.py:141: error: Dict entry 1 has incompatible type \"str\": \"Tensor\"; expected \"str\": \"List[Tensor]\"  [dict-item]",
      "sequence_accuracy_test_b352af.py:142: error: Dict entry 2 has incompatible type \"str\": \"Tensor\"; expected \"str\": \"List[Tensor]\"  [dict-item]",
      "Found 12 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_category_67f90a.py": {
    "base_stats": {
      "total_parameters": 34,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 34,
      "parameters_with_annotations": 15
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "test_category_67f90a.py:268: error: Argument 2 to \"isinstance\" has incompatible type \"Callable[..., Any]\"; expected \"_ClassInfo\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_quantile_94afc3.py": {
    "base_stats": {
      "total_parameters": 101,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 103,
      "parameters_with_annotations": 64
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "test_quantile_94afc3.py:15: error: Incompatible return value type (got \"Tuple[Any, ...]\", expected \"Tuple[str, str]\")  [return-value]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_replace_fc3342.py": {
    "base_stats": {
      "total_parameters": 80,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 80,
      "parameters_with_annotations": 28
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "test_replace_fc3342.py:177: error: List item 1 has incompatible type \"str\"; expected \"float\"  [list-item]",
      "test_replace_fc3342.py:400: error: Incompatible types in assignment (expression has type \"int\", variable has type \"Dict[Any, Any]\")  [assignment]",
      "test_replace_fc3342.py:401: error: Incompatible types in assignment (expression has type \"Dict[int, str]\", variable has type \"str\")  [assignment]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_round_0a4ab4.py": {
    "base_stats": {
      "total_parameters": 42,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 42,
      "parameters_with_annotations": 26
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "test_round_0a4ab4.py:128: error: Unexpected keyword argument \"ambiguous\"  [call-arg]",
      "test_round_0a4ab4.py:131: error: Unexpected keyword argument \"ambiguous\"  [call-arg]",
      "test_round_0a4ab4.py:135: error: Unexpected keyword argument \"ambiguous\"  [call-arg]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "token_characters_indexer_4a2ab1.py": {
    "base_stats": {
      "total_parameters": 19,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 20,
      "parameters_with_annotations": 13
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "token_characters_indexer_4a2ab1.py:111: error: Argument 1 to \"list\" has incompatible type \"zip[Tuple[Any, ...]]\"; expected \"Iterable[List[int]]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "waiting_fc6a47.py": {
    "base_stats": {
      "total_parameters": 114,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 114,
      "parameters_with_annotations": 101
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "waiting_fc6a47.py:494: error: Unsupported target for indexed assignment (\"Mapping[Any, ChannelStateCondition]\")  [index]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "_checklist_internal_2e9c80.py": {
    "base_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 10
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "_checklist_internal_2e9c80.py:25: error: \"ArgumentParser\" has no attribute \"add_parser\"; maybe \"add_subparsers\"?  [attr-defined]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "gen_runner_a44ef9.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 46,
      "parameters_with_annotations": 45
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "gen_runner_a44ef9.py:123: error: f-string: expecting '}'  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "gen_runner_a44ef9.py:290: error: Argument 1 to \"append\" of \"list\" has incompatible type \"Union[int, str]\"; expected \"str\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "json_7c2407.py": {
    "base_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 14
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "json_7c2407.py:183: error: Argument \"cls\" to \"dumps\" has incompatible type \"JSONEncoder\"; expected \"Optional[Type[JSONEncoder]]\"  [arg-type]",
      "json_7c2407.py:197: error: Unexpected keyword argument \"mode\"  [call-arg]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "multipart_07595c.py": {
    "base_stats": {
      "total_parameters": 80,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 80,
      "parameters_with_annotations": 43
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "multipart_07595c.py:231: error: Incompatible return value type (got \"Union[BodyPartReader, MultipartReader]\", expected \"Optional[BodyPartReader]\")  [return-value]",
      "multipart_07595c.py:863: error: Argument 1 to \"append\" of \"list\" has incompatible type \"Tuple[Any, Optional[str], Optional[str]]\"; expected \"Tuple[Any, str, str]\"  [arg-type]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "parameters_38dd02.py": {
    "base_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 14
    },
    "base_error_count": 2,
    "llm_error_count": 2,
    "base_errors": [
      "parameters_38dd02.py:56: error: Invalid type alias: expression is not a valid type  [valid-type]",
      "parameters_38dd02.py:56: error: Unsupported left operand type for | (\"Type[int]\")  [operator]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "parameters_38dd02.py:152: error: Argument 1 to \"range\" has incompatible type \"Union[float, int]\"; expected \"SupportsIndex\"  [arg-type]",
      "parameters_38dd02.py:152: error: Argument 2 to \"range\" has incompatible type \"Union[float, int]\"; expected \"SupportsIndex\"  [arg-type]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "pretrained_transformer_tokenizer_f82621.py": {
    "base_stats": {
      "total_parameters": 34,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 34,
      "parameters_with_annotations": 23
    },
    "base_error_count": 0,
    "llm_error_count": 5,
    "base_errors": [],
    "llm_errors": [
      "pretrained_transformer_tokenizer_f82621.py:223: error: Incompatible types in assignment (expression has type \"List[Optional[Tuple[int, int]]]\", variable has type \"Optional[List[Tuple[int, int]]]\")  [assignment]",
      "pretrained_transformer_tokenizer_f82621.py:226: error: Argument 4 to \"zip\" has incompatible type \"Optional[List[Tuple[int, int]]]\"; expected \"Iterable[Tuple[int, int]]\"  [arg-type]",
      "pretrained_transformer_tokenizer_f82621.py:374: error: Argument 2 to \"with_new_type_id\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]",
      "pretrained_transformer_tokenizer_f82621.py:380: error: Argument 2 to \"with_new_type_id\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]",
      "pretrained_transformer_tokenizer_f82621.py:382: error: Argument 2 to \"with_new_type_id\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]",
      "Found 5 errors in 1 file (checked 1 source file)"
    ]
  },
  "stack_621148.py": {
    "base_stats": {
      "total_parameters": 14,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 14,
      "parameters_with_annotations": 14
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "stack_621148.py:147: error: Incompatible types in assignment (expression has type \"Optional[FrameType]\", variable has type \"FrameType\")  [assignment]",
      "stack_621148.py:156: error: Incompatible types in assignment (expression has type \"Optional[FrameType]\", variable has type \"FrameType\")  [assignment]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "system_55d175.py": {
    "base_stats": {
      "total_parameters": 44,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 44,
      "parameters_with_annotations": 31
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "system_55d175.py:198: error: Argument 4 to \"CreateOpcodeStackData\" has incompatible type \"int\"; expected \"Optional[bytes]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_precise_shrinking_51b995.py": {
    "base_stats": {
      "total_parameters": 34,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 34,
      "parameters_with_annotations": 34
    },
    "base_error_count": 0,
    "llm_error_count": 6,
    "base_errors": [],
    "llm_errors": [
      "test_precise_shrinking_51b995.py:136: error: List comprehension has incompatible type List[Tuple[Tuple[type, Any], ...]]; expected List[Tuple[type, Any]]  [misc]",
      "test_precise_shrinking_51b995.py:153: error: Cannot infer type argument 1 of \"precisely_shrink\"  [misc]",
      "test_precise_shrinking_51b995.py:171: error: Cannot infer type argument 1 of \"precisely_shrink\"  [misc]",
      "test_precise_shrinking_51b995.py:263: error: Cannot infer type argument 1 of \"find_random\"  [misc]",
      "test_precise_shrinking_51b995.py:280: error: Cannot infer type argument 1 of \"precisely_shrink\"  [misc]",
      "test_precise_shrinking_51b995.py:286: error: Cannot infer type argument 1 of \"find_random\"  [misc]",
      "Found 6 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_stat_reductions_69f5b2.py": {
    "base_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 10
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "test_stat_reductions_69f5b2.py:65: error: Unexpected keyword argument \"copy\"  [call-arg]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "utils_71116c.py": {
    "base_stats": {
      "total_parameters": 26,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 26,
      "parameters_with_annotations": 26
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "utils_71116c.py:28: error: Incompatible import of \"generate_password_hash\" (imported name has type \"Callable[[str, str, int], str]\", local name has type \"Callable[[Union[str, bytes]], str]\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "weather_26d8e5.py": {
    "base_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 8
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "weather_26d8e5.py:138: error: Argument 1 to \"format_condition\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "__init___8ac541.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 14,
      "parameters_with_annotations": 14
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "__init___8ac541.py:56: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "__init___8ac541.py:124: error: Argument 2 to \"register_device\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "calendar_819d29.py": {
    "base_stats": {
      "total_parameters": 26,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 26,
      "parameters_with_annotations": 17
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "calendar_819d29.py:261: error: Argument 1 to \"strftime\" of \"date\" has incompatible type \"Optional[datetime]\"; expected \"date\"  [arg-type]",
      "calendar_819d29.py:282: error: Argument 1 to \"strftime\" of \"date\" has incompatible type \"Optional[datetime]\"; expected \"date\"  [arg-type]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "client_e5a475.py": {
    "base_stats": {
      "total_parameters": 53,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 53,
      "parameters_with_annotations": 39
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "client_e5a475.py:9: error: Unexpected argument to \"TypeVar()\": \"infer_variance\"  [misc]",
      "Found 1 error in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "client_e5a475.py:27: error: Unexpected argument to \"TypeVar()\": \"infer_variance\"  [misc]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "common_1f9133.py": {
    "base_stats": {
      "total_parameters": 24,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 24,
      "parameters_with_annotations": 24
    },
    "base_error_count": 0,
    "llm_error_count": 4,
    "base_errors": [],
    "llm_errors": [
      "common_1f9133.py:72: error: Incompatible types in assignment (expression has type \"str\", target has type \"bool\")  [assignment]",
      "common_1f9133.py:85: error: Incompatible types in assignment (expression has type \"str\", target has type \"bool\")  [assignment]",
      "common_1f9133.py:146: error: Incompatible types in assignment (expression has type \"str\", target has type \"int\")  [assignment]",
      "common_1f9133.py:159: error: Incompatible types in assignment (expression has type \"str\", target has type \"int\")  [assignment]",
      "Found 4 errors in 1 file (checked 1 source file)"
    ]
  },
  "conll2003_71bf0e.py": {
    "base_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 12
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "conll2003_71bf0e.py:76: error: Argument 2 to \"text_to_instance\" of \"Conll2003DatasetReader\" has incompatible type \"Tuple[Any, ...]\"; expected \"Optional[List[str]]\"  [arg-type]",
      "conll2003_71bf0e.py:76: error: Argument 3 to \"text_to_instance\" of \"Conll2003DatasetReader\" has incompatible type \"Tuple[Any, ...]\"; expected \"Optional[List[str]]\"  [arg-type]",
      "conll2003_71bf0e.py:76: error: Argument 4 to \"text_to_instance\" of \"Conll2003DatasetReader\" has incompatible type \"Tuple[Any, ...]\"; expected \"Optional[List[str]]\"  [arg-type]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "heartbeat_5b669e.py": {
    "base_stats": {
      "total_parameters": 29,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 29,
      "parameters_with_annotations": 19
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "heartbeat_5b669e.py:79: error: Incompatible return value type (got \"str\", expected \"HeartbeatStatus\")  [return-value]",
      "heartbeat_5b669e.py:81: error: Incompatible return value type (got \"str\", expected \"HeartbeatStatus\")  [return-value]",
      "heartbeat_5b669e.py:82: error: Incompatible return value type (got \"str\", expected \"HeartbeatStatus\")  [return-value]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "helper_91cf7a.py": {
    "base_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 22
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "helper_91cf7a.py:106: error: Argument 2 to \"debugError\" has incompatible type \"Exception\"; expected \"str\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "label_model_609423.py": {
    "base_stats": {
      "total_parameters": 52,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 52,
      "parameters_with_annotations": 26
    },
    "base_error_count": 0,
    "llm_error_count": 7,
    "base_errors": [],
    "llm_errors": [
      "label_model_609423.py:283: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Parameter\")  [assignment]",
      "label_model_609423.py:583: error: Incompatible types in assignment (expression has type \"Adam\", variable has type \"SGD\")  [assignment]",
      "label_model_609423.py:590: error: Incompatible types in assignment (expression has type \"Adamax\", variable has type \"SGD\")  [assignment]",
      "label_model_609423.py:611: error: Incompatible types in assignment (expression has type \"ExponentialLR\", variable has type \"Optional[LambdaLR]\")  [assignment]",
      "label_model_609423.py:613: error: Incompatible types in assignment (expression has type \"StepLR\", variable has type \"Optional[LambdaLR]\")  [assignment]",
      "label_model_609423.py:616: error: Incompatible types in assignment (expression has type \"Optional[LambdaLR]\", variable has type \"Optional[_LRScheduler]\")  [assignment]",
      "label_model_609423.py:642: error: Incompatible types in assignment (expression has type \"Optional[LambdaLR]\", variable has type \"Optional[_LRScheduler]\")  [assignment]",
      "Found 7 errors in 1 file (checked 1 source file)"
    ]
  },
  "multilabel_field_d11efd.py": {
    "base_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 8
    },
    "base_error_count": 1,
    "llm_error_count": 2,
    "base_errors": [
      "multilabel_field_d11efd.py:42: error: Need type annotation for \"_already_warned_namespaces\" (hint: \"_already_warned_namespaces: Set[<type>] = ...\")  [var-annotated]",
      "Found 1 error in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "multilabel_field_d11efd.py:56: error: Invalid index type \"Union[str, int]\" for \"Dict[str, int]\"; expected type \"str\"  [index]",
      "multilabel_field_d11efd.py:68: error: Argument 1 to \"zeros\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "sensor_f28e92.py": {
    "base_stats": {
      "total_parameters": 28,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 28,
      "parameters_with_annotations": 17
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "sensor_f28e92.py:82: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"str\")  [assignment]",
      "sensor_f28e92.py:91: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"str\")  [assignment]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "swagger_c55f37.py": {
    "base_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 17
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "swagger_c55f37.py:410: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"str\")  [assignment]",
      "swagger_c55f37.py:411: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"str\")  [assignment]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_process_inactivity_updates_23d95d.py": {
    "base_stats": {
      "total_parameters": 55,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 55,
      "parameters_with_annotations": 55
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "test_process_inactivity_updates_23d95d.py:61: error: Unexpected keyword argument \"rng\"  [call-arg]",
      "test_process_inactivity_updates_23d95d.py:63: error: Unexpected keyword argument \"rng\"  [call-arg]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "tracing_fe42d6.py": {
    "base_stats": {
      "total_parameters": 42,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 42,
      "parameters_with_annotations": 29
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "tracing_fe42d6.py:124: error: Incompatible types in assignment (expression has type \"Optional[FrameType]\", variable has type \"FrameType\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "base_bb93b4.py": {
    "base_stats": {
      "total_parameters": 128,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 128,
      "parameters_with_annotations": 77
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "base_bb93b4.py:30: error: Incompatible return value type (got \"Optional[str]\", expected \"Union[str, BaseStringArrayMethods]\")  [return-value]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "binary_sensor_c45748.py": {
    "base_stats": {
      "total_parameters": 82,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 82,
      "parameters_with_annotations": 54
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "binary_sensor_c45748.py:197: error: Incompatible types in assignment (expression has type \"Optional[int]\", base class \"XiaomiBinarySensor\" defined the type as \"int\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "encoding_c1153a.py": {
    "base_stats": {
      "total_parameters": 21,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 21,
      "parameters_with_annotations": 21
    },
    "base_error_count": 0,
    "llm_error_count": 9,
    "base_errors": [],
    "llm_errors": [
      "encoding_c1153a.py:148: error: Argument 1 to \"len\" has incompatible type \"Union[str, List[str], Dict[str, str], None]\"; expected \"Sized\"  [arg-type]",
      "encoding_c1153a.py:149: error: Argument 1 to \"len\" has incompatible type \"Union[str, List[str], Dict[str, str], None]\"; expected \"Sized\"  [arg-type]",
      "encoding_c1153a.py:155: error: Incompatible types in assignment (expression has type \"cycle[str]\", variable has type \"Union[str, List[str], Dict[str, str], None]\")  [assignment]",
      "encoding_c1153a.py:161: error: Incompatible types in assignment (expression has type \"cycle[str]\", variable has type \"str\")  [assignment]",
      "encoding_c1153a.py:185: error: Argument \"prefix\" to \"_get_dummies_1d\" has incompatible type \"Union[str, List[str], Dict[str, str], None]\"; expected \"Optional[str]\"  [arg-type]",
      "encoding_c1153a.py:226: error: Argument 1 to \"len\" has incompatible type \"Union[Any, Iterable[Any]]\"; expected \"Sized\"  [arg-type]",
      "encoding_c1153a.py:252: error: Incompatible types in assignment (expression has type \"float\", variable has type \"int\")  [assignment]",
      "encoding_c1153a.py:254: error: Argument 1 to \"len\" has incompatible type \"Union[Any, Iterable[Any]]\"; expected \"Sized\"  [arg-type]",
      "encoding_c1153a.py:451: error: Argument 1 to \"append\" of \"list\" has incompatible type \"Hashable\"; expected \"str\"  [arg-type]",
      "Found 9 errors in 1 file (checked 1 source file)"
    ]
  },
  "fbeta_measure_test_d2fc57.py": {
    "base_stats": {
      "total_parameters": 42,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 42,
      "parameters_with_annotations": 23
    },
    "base_error_count": 0,
    "llm_error_count": 38,
    "base_errors": [],
    "llm_errors": [
      "fbeta_measure_test_d2fc57.py:85: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:86: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:87: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:103: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:104: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:105: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:126: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:127: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:128: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:146: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:147: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:148: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:169: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:170: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:171: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:187: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:188: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:189: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:205: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:206: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:207: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:229: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:230: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:231: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"float\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:250: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:251: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:262: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:263: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:264: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:276: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:277: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:278: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:290: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:291: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:292: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:304: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:305: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "fbeta_measure_test_d2fc57.py:306: error: Incompatible types in assignment (expression has type \"Union[List[float], float]\", variable has type \"List[float]\")  [assignment]",
      "Found 38 errors in 1 file (checked 1 source file)"
    ]
  },
  "light_7346d9.py": {
    "base_stats": {
      "total_parameters": 43,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 43,
      "parameters_with_annotations": 16
    },
    "base_error_count": 0,
    "llm_error_count": 16,
    "base_errors": [],
    "llm_errors": [
      "light_7346d9.py:448: error: Incompatible types in assignment (expression has type \"Tuple[float, ...]\", variable has type \"Optional[Tuple[float, float]]\")  [assignment]",
      "light_7346d9.py:461: error: Incompatible types in assignment (expression has type \"Tuple[int, ...]\", variable has type \"Optional[Tuple[int, int, int]]\")  [assignment]",
      "light_7346d9.py:474: error: Incompatible types in assignment (expression has type \"Tuple[int, ...]\", variable has type \"Optional[Tuple[int, int, int, int]]\")  [assignment]",
      "light_7346d9.py:487: error: Incompatible types in assignment (expression has type \"Tuple[int, ...]\", variable has type \"Optional[Tuple[int, int, int, int, int]]\")  [assignment]",
      "light_7346d9.py:528: error: Incompatible types in assignment (expression has type \"Tuple[float, ...]\", variable has type \"Tuple[float, float]\")  [assignment]",
      "light_7346d9.py:538: error: Incompatible types in assignment (expression has type \"Tuple[float, ...]\", variable has type \"Tuple[float, float]\")  [assignment]",
      "light_7346d9.py:548: error: Incompatible types in assignment (expression has type \"Tuple[int, ...]\", variable has type \"Tuple[int, int, int, int, int]\")  [assignment]",
      "light_7346d9.py:562: error: Incompatible types in assignment (expression has type \"Tuple[int, ...]\", variable has type \"Tuple[int, int, int, int]\")  [assignment]",
      "light_7346d9.py:575: error: Incompatible types in assignment (expression has type \"Tuple[int, ...]\", variable has type \"Tuple[int, int, int]\")  [assignment]",
      "light_7346d9.py:816: error: Argument 1 to \"int\" has incompatible type \"Optional[int]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]",
      "light_7346d9.py:880: error: Argument 1 to \"int\" has incompatible type \"Optional[int]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]",
      "light_7346d9.py:947: error: Argument 1 to \"int\" has incompatible type \"Optional[int]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]",
      "light_7346d9.py:948: error: Argument 1 to \"int\" has incompatible type \"Optional[int]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]",
      "light_7346d9.py:949: error: Argument 1 to \"int\" has incompatible type \"Optional[int]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]",
      "light_7346d9.py:950: error: Argument 1 to \"int\" has incompatible type \"Optional[int]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]",
      "light_7346d9.py:951: error: Argument 1 to \"int\" has incompatible type \"Optional[int]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]",
      "Found 16 errors in 1 file (checked 1 source file)"
    ]
  },
  "multitask_24dbfa.py": {
    "base_stats": {
      "total_parameters": 15,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 15,
      "parameters_with_annotations": 10
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "multitask_24dbfa.py:116: error: Incompatible types in assignment (expression has type \"Tensor\", target has type \"LongTensor\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "note_76679d.py": {
    "base_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 16
    },
    "base_error_count": 0,
    "llm_error_count": 5,
    "base_errors": [],
    "llm_errors": [
      "note_76679d.py:32: error: Argument \"text\" to \"Note\" has incompatible type \"Optional[Any]\"; expected \"str\"  [arg-type]",
      "note_76679d.py:33: error: Argument \"user\" to \"Note\" has incompatible type \"Optional[Any]\"; expected \"str\"  [arg-type]",
      "note_76679d.py:68: error: Argument \"text\" to \"Note\" has incompatible type \"Optional[Any]\"; expected \"str\"  [arg-type]",
      "note_76679d.py:69: error: Argument \"user\" to \"Note\" has incompatible type \"Optional[Any]\"; expected \"str\"  [arg-type]",
      "note_76679d.py:127: error: List comprehension has incompatible type List[Optional[Note]]; expected List[Note]  [misc]",
      "Found 5 errors in 1 file (checked 1 source file)"
    ]
  },
  "sensor_393e9c.py": {
    "base_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 8
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "sensor_393e9c.py:215: error: Argument \"multiplication_factor\" to \"TomorrowioSensorEntityDescription\" has incompatible type \"float\"; expected \"Optional[Callable[[float], float]]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "spacy_tokenizer_edae48.py": {
    "base_stats": {
      "total_parameters": 21,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 21,
      "parameters_with_annotations": 14
    },
    "base_error_count": 0,
    "llm_error_count": 7,
    "base_errors": [],
    "llm_errors": [
      "spacy_tokenizer_edae48.py:117: error: Dict entry 0 has incompatible type \"str\": \"str\"; expected \"str\": \"Optional[List[str]]\"  [dict-item]",
      "spacy_tokenizer_edae48.py:118: error: Dict entry 1 has incompatible type \"str\": \"str\"; expected \"str\": \"Optional[List[str]]\"  [dict-item]",
      "spacy_tokenizer_edae48.py:119: error: Dict entry 2 has incompatible type \"str\": \"bool\"; expected \"str\": \"Optional[List[str]]\"  [dict-item]",
      "spacy_tokenizer_edae48.py:120: error: Dict entry 3 has incompatible type \"str\": \"bool\"; expected \"str\": \"Optional[List[str]]\"  [dict-item]",
      "spacy_tokenizer_edae48.py:121: error: Dict entry 4 has incompatible type \"str\": \"bool\"; expected \"str\": \"Optional[List[str]]\"  [dict-item]",
      "spacy_tokenizer_edae48.py:122: error: Dict entry 5 has incompatible type \"str\": \"bool\"; expected \"str\": \"Optional[List[str]]\"  [dict-item]",
      "spacy_tokenizer_edae48.py:123: error: Dict entry 6 has incompatible type \"str\": \"bool\"; expected \"str\": \"Optional[List[str]]\"  [dict-item]",
      "Found 7 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_bar_9978a0.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 40,
      "parameters_with_annotations": 40
    },
    "base_error_count": 1,
    "llm_error_count": 4,
    "base_errors": [
      "test_bar_9978a0.py:12: error: f-string: expecting '}'  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "test_bar_9978a0.py:171: error: Dict entry 0 has incompatible type \"Tuple[int, int]\": \"Tuple[str, str]\"; expected \"Tuple[int, int]\": \"List[Tuple[str, str]]\"  [dict-item]",
      "test_bar_9978a0.py:172: error: Dict entry 1 has incompatible type \"Tuple[int, int]\": \"Tuple[str, str]\"; expected \"Tuple[int, int]\": \"List[Tuple[str, str]]\"  [dict-item]",
      "test_bar_9978a0.py:173: error: Dict entry 2 has incompatible type \"Tuple[int, int]\": \"Tuple[str, str]\"; expected \"Tuple[int, int]\": \"List[Tuple[str, str]]\"  [dict-item]",
      "test_bar_9978a0.py:174: error: Dict entry 3 has incompatible type \"Tuple[int, int]\": \"Tuple[str, str]\"; expected \"Tuple[int, int]\": \"List[Tuple[str, str]]\"  [dict-item]",
      "Found 4 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_configuration_798036.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 131,
      "parameters_with_annotations": 131
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "test_configuration_798036.py:323: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "test_configuration_798036.py:1088: error: Invalid index type \"Optional[str]\" for \"Dict[str, Any]\"; expected type \"str\"  [index]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_media_source_357294.py": {
    "base_stats": {
      "total_parameters": 17,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 17,
      "parameters_with_annotations": 17
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "test_media_source_357294.py:175: error: Argument 2 to \"create_event_message\" has incompatible type \"Optional[datetime]\"; expected \"datetime\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "tools_632c06.py": {
    "base_stats": {
      "total_parameters": 10,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 10,
      "parameters_with_annotations": 10
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "tools_632c06.py:49: error: Argument 1 to \"__call__\" of \"_lru_cache_wrapper\" has incompatible type \"Type[T]\"; expected \"Hashable\"  [arg-type]",
      "tools_632c06.py:101: error: Argument 1 to \"__call__\" of \"_lru_cache_wrapper\" has incompatible type \"Type[Any]\"; expected \"Hashable\"  [arg-type]",
      "tools_632c06.py:110: error: Argument 1 to \"__call__\" of \"_lru_cache_wrapper\" has incompatible type \"Type[Any]\"; expected \"Hashable\"  [arg-type]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "tts_834735.py": {
    "base_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 14
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "tts_834735.py:54: error: Argument 1 to \"Path\" has incompatible type \"Optional[str]\"; expected \"Union[str, PathLike[str]]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "accessors_09b267.py": {
    "base_stats": {
      "total_parameters": 60,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 60,
      "parameters_with_annotations": 30
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "accessors_09b267.py:702: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"Dict[str, Any]\")  [assignment]",
      "accessors_09b267.py:774: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"Dict[str, Any]\")  [assignment]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "auth_0ecea0.py": {
    "base_stats": {
      "total_parameters": 7,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 7,
      "parameters_with_annotations": 1
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "auth_0ecea0.py:80: error: Argument \"purpose\" to \"create_default_context\" has incompatible type \"Optional[int]\"; expected \"Purpose\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "binary_sensor_39cce2.py": {
    "base_stats": {
      "total_parameters": 14,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 15,
      "parameters_with_annotations": 10
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "binary_sensor_39cce2.py:154: error: Incompatible types in assignment (expression has type \"None\", variable has type \"Dict[Any, Any]\")  [assignment]",
      "binary_sensor_39cce2.py:169: error: Too many arguments for \"__init__\" of \"AirzoneBinarySensor\"  [call-arg]",
      "binary_sensor_39cce2.py:187: error: Too many arguments for \"__init__\" of \"AirzoneBinarySensor\"  [call-arg]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "common_4a17c0.py": {
    "base_stats": {
      "total_parameters": 41,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 41,
      "parameters_with_annotations": 41
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "common_4a17c0.py:130: error: Incompatible types in assignment (expression has type \"str\", target has type \"bool\")  [assignment]",
      "common_4a17c0.py:148: error: Incompatible types in assignment (expression has type \"str\", target has type \"float\")  [assignment]",
      "common_4a17c0.py:267: error: Incompatible types in assignment (expression has type \"float\", target has type \"str\")  [assignment]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "isa_18_2_b9e836.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 14,
      "parameters_with_annotations": 11
    },
    "base_error_count": 1,
    "llm_error_count": 2,
    "base_errors": [
      "isa_18_2_b9e836.py:50: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "isa_18_2_b9e836.py:93: error: Argument \"key\" to \"sorted\" has incompatible type overloaded function; expected \"Callable[[str], Union[SupportsDunderLT[Any], SupportsDunderGT[Any]]]\"  [arg-type]",
      "isa_18_2_b9e836.py:181: error: Argument 3 to \"next_state\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "jinja_17d794.py": {
    "base_stats": {
      "total_parameters": 29,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 29,
      "parameters_with_annotations": 20
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "jinja_17d794.py:72: error: Need type annotation for \"_render_cache\" (hint: \"_render_cache: Dict[<type>, <type>] = ...\")  [var-annotated]",
      "Found 1 error in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "jinja_17d794.py:114: error: Incompatible types in assignment (expression has type \"Union[Literal[True], Match[str], None]\", variable has type \"bool\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "sensor_3f0300.py": {
    "base_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 11
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "sensor_3f0300.py:96: error: Argument 5 to \"AirzoneZoneSensor\" has incompatible type \"Optional[Any]\"; expected \"Dict[str, Any]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_unit_conversion_d2dfd2.py": {
    "base_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 31
    },
    "base_error_count": 3,
    "llm_error_count": 1,
    "base_errors": [
      "test_unit_conversion_d2dfd2.py:53: error: \"object\" has no attribute \"__iter__\"; maybe \"__dir__\" or \"__str__\"? (not iterable)  [attr-defined]",
      "test_unit_conversion_d2dfd2.py:58: error: \"object\" has no attribute \"__iter__\"; maybe \"__dir__\" or \"__str__\"? (not iterable)  [attr-defined]",
      "test_unit_conversion_d2dfd2.py:70: error: \"object\" has no attribute \"__iter__\"; maybe \"__dir__\" or \"__str__\"? (not iterable)  [attr-defined]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "test_unit_conversion_d2dfd2.py:2687: error: Incompatible types in assignment (expression has type \"ApproxBase\", variable has type \"float\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "utils_5a157a.py": {
    "base_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 18
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "utils_5a157a.py:82: error: \"list\" expects 1 type argument, but 3 given  [type-arg]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "core_1410fd.py": {
    "base_stats": {
      "total_parameters": 61,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 61,
      "parameters_with_annotations": 54
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "core_1410fd.py:150: error: Argument 1 to \"pre_seg\" of \"Pinyin\" has incompatible type \"Union[str, List[str]]\"; expected \"str\"  [arg-type]",
      "core_1410fd.py:154: error: Argument 1 has incompatible type \"Union[str, List[str]]\"; expected \"str\"  [arg-type]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "encoder_base_ec641d.py": {
    "base_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 11
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "encoder_base_ec641d.py:84: error: Incompatible types in assignment (expression has type \"Union[int, float]\", variable has type \"int\")  [assignment]",
      "encoder_base_ec641d.py:96: error: Incompatible types in assignment (expression has type \"Tuple[Tensor, ...]\", variable has type \"Union[Tensor, Tuple[Tensor, Tensor], None]\")  [assignment]",
      "encoder_base_ec641d.py:175: error: Incompatible return value type (got \"Tuple[Tensor, ...]\", expected \"Union[Tensor, Tuple[Tensor, Tensor], None]\")  [return-value]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "question_answering_suite_c14a3b.py": {
    "base_stats": {
      "total_parameters": 30,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 30,
      "parameters_with_annotations": 20
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "question_answering_suite_c14a3b.py:89: error: Incompatible return value type (got \"Callable[[Tuple[str, str], KwArg(Any)], Tuple[str, str]]\", expected \"Callable[[Tuple[str, str], Any], Tuple[str, str]]\")  [return-value]",
      "question_answering_suite_c14a3b.py:105: error: List comprehension has incompatible type List[Tuple[str, str]]; expected List[str]  [misc]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "retention_81eb85.py": {
    "base_stats": {
      "total_parameters": 42,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 42,
      "parameters_with_annotations": 42
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "retention_81eb85.py:181: error: Argument 1 to \"len\" has incompatible type \"Iterable[int]\"; expected \"Sized\"  [arg-type]",
      "retention_81eb85.py:199: error: Argument 1 to \"len\" has incompatible type \"Iterable[int]\"; expected \"Sized\"  [arg-type]",
      "retention_81eb85.py:217: error: Argument 1 to \"len\" has incompatible type \"Iterable[int]\"; expected \"Sized\"  [arg-type]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "sensor_875fbc.py": {
    "base_stats": {
      "total_parameters": 28,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 28,
      "parameters_with_annotations": 19
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "sensor_875fbc.py:160: error: Invalid index type \"Union[str, int]\" for \"Dict[str, str]\"; expected type \"str\"  [index]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "span_utils_b17f45.py": {
    "base_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 32,
      "parameters_with_annotations": 30
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "span_utils_b17f45.py:66: error: Argument 1 to \"append\" of \"list\" has incompatible type \"Tuple[int, int]\"; expected \"Tuple[int, Tuple[int, int]]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_inquisitor_e1b111.py": {
    "base_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 18
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "test_inquisitor_e1b111.py:21: error: Missing positional arguments \"value\", \"tb\" in call to \"print_exception\"  [call-arg]",
      "test_inquisitor_e1b111.py:21: error: Argument 1 to \"print_exception\" has incompatible type \"BaseException\"; expected \"Optional[Type[BaseException]]\"  [arg-type]",
      "test_inquisitor_e1b111.py:87: error: Incompatible types in assignment (expression has type \"T\", variable has type \"int\")  [assignment]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_seq_copy_int_d9450d.py": {
    "base_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 13
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "test_seq_copy_int_d9450d.py:161: error: List comprehension has incompatible type List[Tuple[object, ...]]; expected List[Tuple[str, str, bool, int, int]]  [misc]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "_doctools_2a0387.py": {
    "base_stats": {
      "total_parameters": 24,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 24,
      "parameters_with_annotations": 17
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "_doctools_2a0387.py:44: error: Incompatible default for argument \"labels\" (default has type \"Tuple[]\", argument has type \"Optional[List[str]]\")  [assignment]",
      "_doctools_2a0387.py:74: error: Argument 2 to \"zip\" has incompatible type \"Optional[List[str]]\"; expected \"Iterable[str]\"  [arg-type]",
      "_doctools_2a0387.py:85: error: Argument 2 to \"zip\" has incompatible type \"Optional[List[str]]\"; expected \"Iterable[str]\"  [arg-type]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "commands_764f18.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 23,
      "parameters_with_annotations": 22
    },
    "base_error_count": 1,
    "llm_error_count": 2,
    "base_errors": [
      "commands_764f18.py:134: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "commands_764f18.py:57: error: Incompatible types in assignment (expression has type \"List[Any]\", variable has type \"Tuple[str, ...]\")  [assignment]",
      "commands_764f18.py:127: error: Argument 2 to \"insert\" of \"list\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "encoding_8cbe7e.py": {
    "base_stats": {
      "total_parameters": 49,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 49,
      "parameters_with_annotations": 39
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "encoding_8cbe7e.py:153: error: Argument 1 to \"url_encode\" has incompatible type \"Dict[str, bool]\"; expected \"Union[Mapping[str, str], Iterable[Tuple[str, str]]]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "sampler_d1337e.py": {
    "base_stats": {
      "total_parameters": 52,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 52,
      "parameters_with_annotations": 35
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "sampler_d1337e.py:38: error: Incompatible types in assignment (expression has type \"float\", target has type \"int\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "__init___b55467.py": {
    "base_stats": {
      "total_parameters": 8,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 8,
      "parameters_with_annotations": 8
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "__init___b55467.py:2: error: Need type annotation for \"_registry\" (hint: \"_registry: Dict[<type>, <type>] = ...\")  [var-annotated]",
      "Found 1 error in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "__init___b55467.py:56: error: Return value expected  [return-value]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "climate_9e8de7.py": {
    "base_stats": {
      "total_parameters": 12,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 12,
      "parameters_with_annotations": 6
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "climate_9e8de7.py:189: error: Incompatible types in assignment (expression has type \"float\", variable has type \"Optional[int]\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "log_67c6cb.py": {
    "base_stats": {
      "total_parameters": 62,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 64,
      "parameters_with_annotations": 50
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "log_67c6cb.py:78: error: Argument \"action\" to \"log_with_context\" of \"AbstractEventLogger\" has incompatible type \"Union[str, Callable[..., str]]\"; expected \"str\"  [arg-type]",
      "log_67c6cb.py:79: error: Argument \"object_ref\" to \"log_with_context\" of \"AbstractEventLogger\" has incompatible type \"Union[str, Callable[..., str], None]\"; expected \"Optional[str]\"  [arg-type]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "message_cache_dbda93.py": {
    "base_stats": {
      "total_parameters": 49,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 49,
      "parameters_with_annotations": 49
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "message_cache_dbda93.py:224: error: Argument 2 to \"sew_messages_and_reactions\" has incompatible type \"List[RawReactionRow]\"; expected \"Iterable[Dict[str, Any]]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "misc_23de87.py": {
    "base_stats": {
      "total_parameters": 47,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 47,
      "parameters_with_annotations": 47
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "misc_23de87.py:118: error: Incompatible types in assignment (expression has type \"List[List[<nothing>]]\", target has type \"Tuple[List[float], List[float]]\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "nlp_fe0862.py": {
    "base_stats": {
      "total_parameters": 38,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 38,
      "parameters_with_annotations": 32
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "nlp_fe0862.py:185: error: Incompatible types in assignment (expression has type \"Type[BaseNLPLabelingFunction]\", base class \"base_nlp_labeling_function\" defined the type as \"None\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "nlp_fe0862.py:53: error: Argument \"pre\" to \"SpacyPreprocessorParameters\" has incompatible type \"Optional[List[Callable[[Any], Any]]]\"; expected \"List[Callable[[Any], Any]]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "raiden_service_70320b.py": {
    "base_stats": {
      "total_parameters": 110,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 110,
      "parameters_with_annotations": 68
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "raiden_service_70320b.py:382: error: Argument 1 to \"join\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_planner_aec317.py": {
    "base_stats": {
      "total_parameters": 177,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 167,
      "parameters_with_annotations": 51
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "test_planner_aec317.py:2431: error: Need type annotation for \"deployed_resources\"  [var-annotated]",
      "test_planner_aec317.py:2496: error: Need type annotation for \"deployed_resources\"  [var-annotated]",
      "test_planner_aec317.py:2536: error: Need type annotation for \"deployed_resources\"  [var-annotated]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "xml_bf31a3.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 44,
      "parameters_with_annotations": 21
    },
    "base_error_count": 1,
    "llm_error_count": 2,
    "base_errors": [
      "xml_bf31a3.py:199: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "xml_bf31a3.py:400: error: Invalid index type \"None\" for \"Dict[str, str]\"; expected type \"str\"  [index]",
      "xml_bf31a3.py:430: error: Incompatible types in assignment (expression has type \"Union[str, IOBase, None]\", variable has type \"Union[str, IOBase]\")  [assignment]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "arguments_a79ceb.py": {
    "base_stats": {
      "total_parameters": 48,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 52,
      "parameters_with_annotations": 33
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "arguments_a79ceb.py:27: error: Name \"Iterable\" is not defined  [name-defined]",
      "arguments_a79ceb.py:27: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Iterable\")",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "gallery_2bb1c1.py": {
    "base_stats": {
      "total_parameters": 32,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 32,
      "parameters_with_annotations": 32
    },
    "base_error_count": 2,
    "llm_error_count": 1,
    "base_errors": [
      "gallery_2bb1c1.py:20: error: Incompatible types in assignment (expression has type \"partial[CompletedProcess[str]]\", variable has type overloaded function)  [assignment]",
      "gallery_2bb1c1.py:23: error: Invalid statement in NamedTuple definition; expected \"field_name: field_type [= default]\"  [misc]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "gallery_2bb1c1.py:21: error: Incompatible types in assignment (expression has type \"partial[CompletedProcess[str]]\", variable has type overloaded function)  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "simple_httpclient_5928fa.py": {
    "base_stats": {
      "total_parameters": 60,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 60,
      "parameters_with_annotations": 34
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "simple_httpclient_5928fa.py:508: error: Incompatible types in assignment (expression has type \"None\", variable has type \"Callable[[], None]\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "states_8ed126.py": {
    "base_stats": {
      "total_parameters": 45,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 45,
      "parameters_with_annotations": 36
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "states_8ed126.py:439: error: \"Counter\" expects 1 type argument, but 2 given  [type-arg]",
      "states_8ed126.py:449: error: Argument 1 to \"len\" has incompatible type \"Iterable[Any]\"; expected \"Sized\"  [arg-type]",
      "states_8ed126.py:486: error: \"Counter\" expects 1 type argument, but 2 given  [type-arg]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_cat_c39959.py": {
    "base_stats": {
      "total_parameters": 20,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 20,
      "parameters_with_annotations": 20
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "test_cat_c39959.py:31: error: Incompatible types in assignment (expression has type \"List[str]\", variable has type \"Optional[Callable[..., Union[Any, Any]]]\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_conversion_928a39.py": {
    "base_stats": {
      "total_parameters": 63,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 63,
      "parameters_with_annotations": 51
    },
    "base_error_count": 0,
    "llm_error_count": 5,
    "base_errors": [],
    "llm_errors": [
      "test_conversion_928a39.py:67: error: \"type\" expects no type arguments, but 1 given  [type-arg]",
      "test_conversion_928a39.py:103: error: \"type\" expects no type arguments, but 1 given  [type-arg]",
      "test_conversion_928a39.py:133: error: \"type\" expects no type arguments, but 1 given  [type-arg]",
      "test_conversion_928a39.py:324: error: \"type\" expects no type arguments, but 1 given  [type-arg]",
      "test_conversion_928a39.py:522: error: \"type\" expects no type arguments, but 1 given  [type-arg]",
      "Found 5 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_style_48cf89.py": {
    "base_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 25
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "test_style_48cf89.py:67: error: List item 3 has incompatible type \"Tuple[str, List[str], bool]\"; expected \"Tuple[str, List[str], Union[str, Dict[str, str]]]\"  [list-item]",
      "test_style_48cf89.py:68: error: List item 4 has incompatible type \"Tuple[str, List[str], bool]\"; expected \"Tuple[str, List[str], Union[str, Dict[str, str]]]\"  [list-item]",
      "test_style_48cf89.py:72: error: Dict entry 0 has incompatible type \"str\": \"None\"; expected \"str\": \"str\"  [dict-item]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_to_csv_e7f2e8.py": {
    "base_stats": {
      "total_parameters": 143,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 144,
      "parameters_with_annotations": 83
    },
    "base_error_count": 0,
    "llm_error_count": 6,
    "base_errors": [],
    "llm_errors": [
      "test_to_csv_e7f2e8.py:605: error: Argument 3 to \"_return_result_expected\" of \"TestDataFrameToCSV\" has incompatible type \"**Dict[str, int]\"; expected \"Optional[str]\"  [arg-type]",
      "test_to_csv_e7f2e8.py:605: error: Argument 3 to \"_return_result_expected\" of \"TestDataFrameToCSV\" has incompatible type \"**Dict[str, int]\"; expected \"bool\"  [arg-type]",
      "test_to_csv_e7f2e8.py:798: error: Argument 1 to \"_make_frame\" has incompatible type \"bool\"; expected \"Optional[List[str]]\"  [arg-type]",
      "test_to_csv_e7f2e8.py:808: error: Argument 1 to \"_make_frame\" has incompatible type \"bool\"; expected \"Optional[List[str]]\"  [arg-type]",
      "test_to_csv_e7f2e8.py:812: error: Argument 1 to \"_make_frame\" has incompatible type \"bool\"; expected \"Optional[List[str]]\"  [arg-type]",
      "test_to_csv_e7f2e8.py:1024: error: Argument 1 to \"read_csv\" of \"TestDataFrameToCSV\" has incompatible type \"StringIO\"; expected \"Union[str, Path]\"  [arg-type]",
      "Found 6 errors in 1 file (checked 1 source file)"
    ]
  },
  "vacuum_0ba5e2.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 19,
      "parameters_with_annotations": 8
    },
    "base_error_count": 1,
    "llm_error_count": 3,
    "base_errors": [
      "vacuum_0ba5e2.py:117: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "vacuum_0ba5e2.py:192: error: Argument 1 to \"get\" of \"dict\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]",
      "vacuum_0ba5e2.py:195: error: Invalid index type \"Optional[str]\" for \"Dict[str, Any]\"; expected type \"str\"  [index]",
      "vacuum_0ba5e2.py:212: error: Invalid index type \"Optional[str]\" for \"Dict[str, Any]\"; expected type \"str\"  [index]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "_parser_ad554d.py": {
    "base_stats": {
      "total_parameters": 78,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 78,
      "parameters_with_annotations": 70
    },
    "base_error_count": 0,
    "llm_error_count": 4,
    "base_errors": [],
    "llm_errors": [
      "_parser_ad554d.py:48: error: Incompatible types in assignment (expression has type \"str\", variable has type \"bytes\")  [assignment]",
      "_parser_ad554d.py:55: error: Argument 1 to \"loads\" has incompatible type \"bytes\"; expected \"str\"  [arg-type]",
      "_parser_ad554d.py:320: error: Incompatible types in assignment (expression has type \"None\", variable has type \"str\")  [assignment]",
      "_parser_ad554d.py:515: error: Incompatible types in assignment (expression has type \"None\", variable has type \"str\")  [assignment]",
      "Found 4 errors in 1 file (checked 1 source file)"
    ]
  },
  "__init___716b23.py": {
    "base_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 10
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "__init___716b23.py:125: error: Argument 2 to \"BroadlinkMP1BG1Device\" has incompatible type \"*Tuple[str, str, str, str, str, int, int, int]\"; expected \"int\"  [arg-type]",
      "__init___716b23.py:127: error: Argument 2 to \"BroadlinkSP4BDevice\" has incompatible type \"*Tuple[str, str, str, str, str, int, int, int]\"; expected \"int\"  [arg-type]",
      "__init___716b23.py:128: error: Argument 2 to \"BroadlinkDevice\" has incompatible type \"*Tuple[str, str, str, str, str, int, int, int]\"; expected \"int\"  [arg-type]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "actor_865029.py": {
    "base_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 5
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "actor_865029.py:74: error: \"AsyncGenerator\" expects 2 type arguments, but 3 given  [type-arg]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "confluent_3b2473.py": {
    "base_stats": {
      "total_parameters": 58,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 58,
      "parameters_with_annotations": 36
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "confluent_3b2473.py:524: error: Unexpected keyword argument \"on_delivery\"  [call-arg]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "data_catalog_8d7fcf.py": {
    "base_stats": {
      "total_parameters": 59,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 59,
      "parameters_with_annotations": 36
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "data_catalog_8d7fcf.py:456: error: Argument 1 to \"_FrozenDatasets\" has incompatible type \"Optional[_FrozenDatasets]\"; expected \"Optional[Dict[str, Any]]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "entity_3c2299.py": {
    "base_stats": {
      "total_parameters": 12,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 12,
      "parameters_with_annotations": 5
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "entity_3c2299.py:120: error: Argument 1 to \"set_result\" of \"Future\" has incompatible type \"bool\"; expected \"None\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "entity_680502.py": {
    "base_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 5
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "entity_680502.py:169: error: Incompatible return value type (got \"Optional[str]\", expected \"str\")  [return-value]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "find_learning_rate_f33819.py": {
    "base_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 21
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "find_learning_rate_f33819.py:29: error: \"ArgumentParser\" has no attribute \"add_parser\"; maybe \"add_subparsers\"?  [attr-defined]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "sensor_f004b2.py": {
    "base_stats": {
      "total_parameters": 51,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 51,
      "parameters_with_annotations": 23
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "sensor_f004b2.py:238: error: Incompatible types in assignment (expression has type \"FilterState\", variable has type \"_State\")  [assignment]",
      "sensor_f004b2.py:238: error: Argument 1 to \"filter_state\" of \"Filter\" has incompatible type \"_State\"; expected \"FilterState\"  [arg-type]",
      "sensor_f004b2.py:426: error: Too many arguments for \"FilterState\"  [call-arg]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "sourcemaps_0942d0.py": {
    "base_stats": {
      "total_parameters": 27,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 27,
      "parameters_with_annotations": 16
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "sourcemaps_0942d0.py:96: error: Argument 1 to \"dumpDeltaMap\" of \"SourceMapper\" has incompatible type \"List[List[int]]\"; expected \"List[List[List[int]]]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_hist_method_862ac9.py": {
    "base_stats": {
      "total_parameters": 140,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 140,
      "parameters_with_annotations": 70
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "test_hist_method_862ac9.py:595: error: Incompatible types in assignment (expression has type \"Union[str, List[str], None]\", variable has type \"Optional[List[str]]\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_mediatedtransfer_b63130.py": {
    "base_stats": {
      "total_parameters": 47,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 47,
      "parameters_with_annotations": 47
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "test_mediatedtransfer_b63130.py:563: error: Incompatible default for argument \"expected_transferred_amounts\" (default has type \"Type[List[Any]]\", argument has type \"List[int]\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_utils_4b4e4d.py": {
    "base_stats": {
      "total_parameters": 42,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 42,
      "parameters_with_annotations": 42
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "test_utils_4b4e4d.py:259: error: Incompatible types in assignment (expression has type overloaded function, variable has type overloaded function)  [assignment]",
      "test_utils_4b4e4d.py:264: error: Argument \"file\" to \"print\" has incompatible type \"Union[GzipFile, TextIO]\"; expected \"Optional[SupportsWrite[str]]\"  [arg-type]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "transformer_layer_bf9c8e.py": {
    "base_stats": {
      "total_parameters": 34,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 34,
      "parameters_with_annotations": 27
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "transformer_layer_bf9c8e.py:75: error: Incompatible types in assignment (expression has type \"Optional[BoolTensor]\", variable has type \"BoolTensor\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "browser_8130a6.py": {
    "base_stats": {
      "total_parameters": 19,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 8
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "browser_8130a6.py:190: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"str\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "collections_5f4a3a.py": {
    "base_stats": {
      "total_parameters": 63,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 63,
      "parameters_with_annotations": 39
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "collections_5f4a3a.py:120: error: Incompatible types in assignment (expression has type \"Tuple[Type[bool], Callable[[Sized], int], Type[Tuple[Any, ...]], Type[List[Any]]]\", variable has type \"Tuple[type, ...]\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "color_a02da4.py": {
    "base_stats": {
      "total_parameters": 100,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 162,
      "parameters_with_annotations": 162
    },
    "base_error_count": 1,
    "llm_error_count": 12,
    "base_errors": [
      "color_a02da4.py:11: error: Too many arguments for \"RGBColor\"  [call-arg]",
      "Found 1 error in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "color_a02da4.py:345: error: Incompatible return value type (got \"Tuple[int, ...]\", expected \"Tuple[int, int, int, int]\")  [return-value]",
      "color_a02da4.py:350: error: Incompatible return value type (got \"Tuple[int, ...]\", expected \"Tuple[int, int, int]\")  [return-value]",
      "color_a02da4.py:370: error: Incompatible types in assignment (expression has type \"Tuple[float, float, float, int, int]\", variable has type \"Tuple[int, int, int, int, int]\")  [assignment]",
      "color_a02da4.py:375: error: Incompatible return value type (got \"Tuple[int, ...]\", expected \"Tuple[int, int, int, int, int]\")  [return-value]",
      "color_a02da4.py:398: error: Incompatible return value type (got \"Tuple[int, ...]\", expected \"Tuple[int, int, int, int, int]\")  [return-value]",
      "color_a02da4.py:398: error: Argument 2 to \"match_max_scale\" has incompatible type \"Tuple[float, float, float]\"; expected \"Tuple[int, ...]\"  [arg-type]",
      "color_a02da4.py:627: error: Incompatible return value type (got \"Tuple[int, ...]\", expected \"Tuple[int, int, int, int]\")  [return-value]",
      "color_a02da4.py:632: error: Incompatible return value type (got \"Tuple[int, ...]\", expected \"Tuple[int, int, int]\")  [return-value]",
      "color_a02da4.py:657: error: Incompatible return value type (got \"Tuple[int, ...]\", expected \"Tuple[int, int, int, int, int]\")  [return-value]",
      "color_a02da4.py:657: error: Argument 2 to \"match_max_scale\" has incompatible type \"Tuple[float, float, float, float, float]\"; expected \"Tuple[int, ...]\"  [arg-type]",
      "color_a02da4.py:680: error: Incompatible return value type (got \"Tuple[int, ...]\", expected \"Tuple[int, int, int, int, int]\")  [return-value]",
      "color_a02da4.py:680: error: Argument 2 to \"match_max_scale\" has incompatible type \"Tuple[float, float, float]\"; expected \"Tuple[int, ...]\"  [arg-type]",
      "Found 12 errors in 1 file (checked 1 source file)"
    ]
  },
  "mysql_113041.py": {
    "base_stats": {
      "total_parameters": 24,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 24,
      "parameters_with_annotations": 16
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "mysql_113041.py:34: error: Need type annotation for \"type_code_map\" (hint: \"type_code_map: Dict[<type>, <type>] = ...\")  [var-annotated]",
      "Found 1 error in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "mysql_113041.py:197: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"Union[int, str]\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "openapi_a5fc11.py": {
    "base_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 17
    },
    "base_error_count": 0,
    "llm_error_count": 4,
    "base_errors": [],
    "llm_errors": [
      "openapi_a5fc11.py:242: error: Invalid index type \"Union[str, int]\" for \"Union[Dict[str, Any], List[Any]]\"; expected type \"str\"  [index]",
      "openapi_a5fc11.py:242: error: Invalid index type \"Union[str, int]\" for \"Union[Dict[str, Any], List[Any]]\"; expected type \"SupportsIndex\"  [index]",
      "openapi_a5fc11.py:362: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"str\")  [assignment]",
      "openapi_a5fc11.py:363: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"str\")  [assignment]",
      "Found 4 errors in 1 file (checked 1 source file)"
    ]
  },
  "service_registry_e94e0b.py": {
    "base_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 16
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "service_registry_e94e0b.py:75: error: Incompatible types in assignment (expression has type \"None\", variable has type \"bool\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "span_based_f1_measure_cf6fc9.py": {
    "base_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 14
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "span_based_f1_measure_cf6fc9.py:127: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[BoolTensor]\")  [assignment]",
      "span_based_f1_measure_cf6fc9.py:148: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"int\")  [assignment]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_period_c61bbd.py": {
    "base_stats": {
      "total_parameters": 88,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 88,
      "parameters_with_annotations": 29
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "test_period_c61bbd.py:772: error: Argument 1 to \"datetime\" has incompatible type \"*Tuple[int, ...]\"; expected \"Optional[tzinfo]\"  [arg-type]",
      "test_period_c61bbd.py:814: error: Argument 1 to \"datetime\" has incompatible type \"*Tuple[int, ...]\"; expected \"Optional[tzinfo]\"  [arg-type]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_procedure_3f923d.py": {
    "base_stats": {
      "total_parameters": 26,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 26,
      "parameters_with_annotations": 19
    },
    "base_error_count": 1,
    "llm_error_count": 5,
    "base_errors": [
      "test_procedure_3f923d.py:98: error: Need type annotation for \"ULTRA_TESTS\" (hint: \"ULTRA_TESTS: List[<type>] = ...\")  [var-annotated]",
      "Found 1 error in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "test_procedure_3f923d.py:87: error: Argument 1 to \"_get_val\" of \"CattTest\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]",
      "test_procedure_3f923d.py:90: error: Argument 1 to \"int\" has incompatible type \"Optional[Any]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]",
      "test_procedure_3f923d.py:304: error: Argument \"standard\" to \"run_tests\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]",
      "test_procedure_3f923d.py:304: error: Argument \"audio\" to \"run_tests\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]",
      "test_procedure_3f923d.py:304: error: Argument \"ultra\" to \"run_tests\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]",
      "Found 5 errors in 1 file (checked 1 source file)"
    ]
  },
  "celery_tests_fc4a66.py": {
    "base_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 30
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "celery_tests_fc4a66.py:110: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"str\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "climate_8c1cee.py": {
    "base_stats": {
      "total_parameters": 10,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 10,
      "parameters_with_annotations": 7
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "climate_8c1cee.py:156: error: Incompatible types in assignment (expression has type \"None\", variable has type \"float\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "common_fcbb68.py": {
    "base_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 16
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "common_fcbb68.py:244: error: Starred assignment target must be in a list or tuple  [misc]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "conftest_cc5a31.py": {
    "base_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 12,
      "parameters_with_annotations": 11
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "conftest_cc5a31.py:90: error: Type cannot be declared in assignment to non-self attribute  [misc]",
      "conftest_cc5a31.py:163: error: Yield value expected  [misc]",
      "conftest_cc5a31.py:181: error: Type cannot be declared in assignment to non-self attribute  [misc]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "device_e3bccf.py": {
    "base_stats": {
      "total_parameters": 29,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 29,
      "parameters_with_annotations": 11
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "device_e3bccf.py:145: error: Incompatible return value type (got \"Union[str, None, Any]\", expected \"bool\")  [return-value]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "media_player_4a0667.py": {
    "base_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 4
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "media_player_4a0667.py:36: error: Need type annotation for \"_attr_source_list\" (hint: \"_attr_source_list: List[<type>] = ...\")  [var-annotated]",
      "Found 1 error in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "media_player_4a0667.py:226: error: Incompatible types in assignment (expression has type \"None\", variable has type \"str\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_backup_restore_171613.py": {
    "base_stats": {
      "total_parameters": 17,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 17,
      "parameters_with_annotations": 17
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "test_backup_restore_171613.py:220: error: Incompatible return value type (got \"object\", expected \"bool\")  [return-value]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_deprecated_validate_arguments_bca830.py": {
    "base_stats": {
      "total_parameters": 45,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 45,
      "parameters_with_annotations": 41
    },
    "base_error_count": 3,
    "llm_error_count": 87,
    "base_errors": [
      "test_deprecated_validate_arguments_bca830.py:4: error: Module \"typing\" has no attribute \"Annotated\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:4: note: Use `from typing_extensions import Annotated` instead",
      "test_deprecated_validate_arguments_bca830.py:4: note: See https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-new-additions-to-the-typing-module",
      "Found 1 error in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "test_deprecated_validate_arguments_bca830.py:4: error: Module \"typing\" has no attribute \"Annotated\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:4: note: Use `from typing_extensions import Annotated` instead",
      "test_deprecated_validate_arguments_bca830.py:4: note: See https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-new-additions-to-the-typing-module",
      "test_deprecated_validate_arguments_bca830.py:29: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:29: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:30: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:31: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:31: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:32: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:32: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:34: error: Too few arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:40: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:40: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:50: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:50: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:52: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:52: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:52: error: Unexpected keyword argument \"apple\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:54: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:54: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:54: error: Unexpected keyword argument \"a\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:56: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:56: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:56: error: Unexpected keyword argument \"a\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:56: error: Unexpected keyword argument \"b\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:69: error: \"Callable[[F], F]\" has no attribute \"vd\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:70: error: \"Callable[[F], F]\" has no attribute \"raw_function\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:71: error: \"Callable[[F], F]\" has no attribute \"vd\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:72: error: \"Callable[[F], F]\" has no attribute \"vd\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:73: error: \"Callable[[F], F]\" has no attribute \"model\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:74: error: \"Callable[[F], F]\" has no attribute \"model\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:75: error: \"Callable[[F], F]\" has no attribute \"model\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:76: error: \"Callable[[F], F]\" has no attribute \"model\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:85: error: \"Callable[[F], F]\" has no attribute \"model\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:86: error: Unexpected keyword argument \"a\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:86: error: Unexpected keyword argument \"b\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:88: error: Unexpected keyword argument \"a\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:88: error: Unexpected keyword argument \"b\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:98: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:98: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:106: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:106: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:107: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:107: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:107: error: Unexpected keyword argument \"c\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:107: error: Unexpected keyword argument \"d\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:116: error: Incompatible types in assignment (expression has type \"Callable[[F], F]\", variable has type \"Callable[[int, int, VarArg(int), DefaultNamedArg(int, 'd'), KwArg(Any)], str]\")  [assignment]",
      "test_deprecated_validate_arguments_bca830.py:121: error: Argument \"args\" to \"foo\" has incompatible type \"Tuple[int, int]\"; expected \"int\"  [arg-type]",
      "test_deprecated_validate_arguments_bca830.py:122: error: Argument \"args\" to \"foo\" has incompatible type \"Tuple[int, int]\"; expected \"int\"  [arg-type]",
      "test_deprecated_validate_arguments_bca830.py:134: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:135: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:135: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:157: error: \"Callable[[F], F]\" has no attribute \"model\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:158: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:158: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:160: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:160: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:160: error: Unexpected keyword argument \"apple\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:162: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:162: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:162: error: Unexpected keyword argument \"apple\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:162: error: Unexpected keyword argument \"banana\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:164: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:164: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:195: error: Incompatible types in \"await\" (actual type \"int\", expected type \"Awaitable[Any]\")  [misc]",
      "test_deprecated_validate_arguments_bca830.py:195: error: Value of type variable \"F\" of \"foo\" cannot be \"int\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:195: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:200: error: Value of type variable \"F\" of \"foo\" cannot be \"str\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:200: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:200: error: Argument 1 to \"run\" has incompatible type \"str\"; expected \"Coroutine[Any, Any, <nothing>]\"  [arg-type]",
      "test_deprecated_validate_arguments_bca830.py:216: error: Value of type variable \"F\" of \"foo\" cannot be \"List[int]\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:216: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:218: error: Value of type variable \"F\" of \"foo\" cannot be \"List[str]\"  [type-var]",
      "test_deprecated_validate_arguments_bca830.py:218: error: Too many arguments for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:247: error: Invalid self argument \"X\" to attribute function \"foo\" with type \"Callable[[F], F]\"  [misc]",
      "test_deprecated_validate_arguments_bca830.py:247: error: Too many arguments for \"foo\" of \"X\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:248: error: Invalid self argument \"X\" to attribute function \"foo\" with type \"Callable[[F], F]\"  [misc]",
      "test_deprecated_validate_arguments_bca830.py:250: error: Invalid self argument \"X\" to attribute function \"foo\" with type \"Callable[[F], F]\"  [misc]",
      "test_deprecated_validate_arguments_bca830.py:277: error: Too many arguments for \"foo\" of \"X\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:304: error: \"Callable[[int, int], str]\" has no attribute \"model\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:317: error: \"Callable[[int, int], str]\" has no attribute \"model\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:357: error: \"Callable[[F], F]\" has no attribute \"validate\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:359: error: \"Callable[[F], F]\" has no attribute \"validate\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:360: error: \"Callable[..., Any]\" has no attribute \"assert_not_called\"  [attr-defined]",
      "test_deprecated_validate_arguments_bca830.py:371: error: Unexpected keyword argument \"b\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:379: error: Unexpected keyword argument \"d\" for \"foo\"  [call-arg]",
      "test_deprecated_validate_arguments_bca830.py:380: error: Unexpected keyword argument \"b\" for \"foo\"  [call-arg]",
      "Found 85 errors in 1 file (checked 1 source file)"
    ]
  },
  "translations_f1af2c.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 27,
      "parameters_with_annotations": 27
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "translations_f1af2c.py:186: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "translations_f1af2c.py:151: error: Dict entry 0 has incompatible type \"Type[str]\": \"Any\"; expected \"str\": \"Any\"  [dict-item]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "alerta_4aa3fa.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 15,
      "parameters_with_annotations": 11
    },
    "base_error_count": 1,
    "llm_error_count": 8,
    "base_errors": [
      "alerta_4aa3fa.py:52: error: f-string: expecting '}'  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "alerta_4aa3fa.py:75: error: Type cannot be declared in assignment to non-self attribute  [misc]",
      "alerta_4aa3fa.py:76: error: Type cannot be declared in assignment to non-self attribute  [misc]",
      "alerta_4aa3fa.py:77: error: Type cannot be declared in assignment to non-self attribute  [misc]",
      "alerta_4aa3fa.py:78: error: Type cannot be declared in assignment to non-self attribute  [misc]",
      "alerta_4aa3fa.py:79: error: Type cannot be declared in assignment to non-self attribute  [misc]",
      "alerta_4aa3fa.py:80: error: Type cannot be declared in assignment to non-self attribute  [misc]",
      "alerta_4aa3fa.py:81: error: Type cannot be declared in assignment to non-self attribute  [misc]",
      "alerta_4aa3fa.py:96: error: Type cannot be declared in assignment to non-self attribute  [misc]",
      "Found 8 errors in 1 file (checked 1 source file)"
    ]
  },
  "api_tests_b98962.py": {
    "base_stats": {
      "total_parameters": 108,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 108,
      "parameters_with_annotations": 49
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "api_tests_b98962.py:53: error: Argument 1 to \"deepcopy\" has incompatible type \"Optional[Dict[str, Any]]\"; expected \"Dict[str, Any]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "bucket_batch_sampler_a1e388.py": {
    "base_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 12
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "bucket_batch_sampler_a1e388.py:112: error: List comprehension has incompatible type List[List[int]]; expected List[int]  [misc]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "entropy_test_fa6663.py": {
    "base_stats": {
      "total_parameters": 15,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 15,
      "parameters_with_annotations": 10
    },
    "base_error_count": 0,
    "llm_error_count": 5,
    "base_errors": [],
    "llm_errors": [
      "entropy_test_fa6663.py:66: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"BoolTensor\")  [assignment]",
      "entropy_test_fa6663.py:78: error: Incompatible types in assignment (expression has type \"List[Tensor]\", variable has type \"Tensor\")  [assignment]",
      "entropy_test_fa6663.py:79: error: Dict entry 0 has incompatible type \"str\": \"Tensor\"; expected \"str\": \"List[Tensor]\"  [dict-item]",
      "entropy_test_fa6663.py:98: error: Incompatible types in assignment (expression has type \"List[Tensor]\", variable has type \"Tensor\")  [assignment]",
      "entropy_test_fa6663.py:99: error: Dict entry 0 has incompatible type \"str\": \"Tensor\"; expected \"str\": \"List[Tensor]\"  [dict-item]",
      "Found 5 errors in 1 file (checked 1 source file)"
    ]
  },
  "fairness_metrics_fcc9f2.py": {
    "base_stats": {
      "total_parameters": 35,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 35,
      "parameters_with_annotations": 23
    },
    "base_error_count": 0,
    "llm_error_count": 21,
    "base_errors": [],
    "llm_errors": [
      "fairness_metrics_fcc9f2.py:111: error: Value expression in dictionary comprehension has incompatible type \"Tensor\"; expected type \"FloatTensor\"  [misc]",
      "fairness_metrics_fcc9f2.py:119: error: Incompatible types in assignment (expression has type \"Tensor\", target has type \"FloatTensor\")  [assignment]",
      "fairness_metrics_fcc9f2.py:123: error: Too many arguments  [call-arg]",
      "fairness_metrics_fcc9f2.py:123: error: Incompatible types in assignment (expression has type \"Tensor\", target has type \"FloatTensor\")  [assignment]",
      "fairness_metrics_fcc9f2.py:123: error: Argument 1 has incompatible type \"Tensor\"; expected \"Distribution\"  [arg-type]",
      "fairness_metrics_fcc9f2.py:123: error: Argument 2 has incompatible type \"Tensor\"; expected \"Distribution\"  [arg-type]",
      "fairness_metrics_fcc9f2.py:252: error: Value expression in dictionary comprehension has incompatible type \"Tensor\"; expected type \"FloatTensor\"  [misc]",
      "fairness_metrics_fcc9f2.py:264: error: Incompatible types in assignment (expression has type \"Tensor\", target has type \"FloatTensor\")  [assignment]",
      "fairness_metrics_fcc9f2.py:267: error: Incompatible types in assignment (expression has type \"Tensor\", target has type \"FloatTensor\")  [assignment]",
      "fairness_metrics_fcc9f2.py:271: error: Too many arguments  [call-arg]",
      "fairness_metrics_fcc9f2.py:271: error: Incompatible types in assignment (expression has type \"Tensor\", target has type \"FloatTensor\")  [assignment]",
      "fairness_metrics_fcc9f2.py:271: error: Argument 1 has incompatible type \"Tensor\"; expected \"Distribution\"  [arg-type]",
      "fairness_metrics_fcc9f2.py:271: error: Argument 2 has incompatible type \"Tensor\"; expected \"Distribution\"  [arg-type]",
      "fairness_metrics_fcc9f2.py:402: error: Value expression in dictionary comprehension has incompatible type \"Tensor\"; expected type \"FloatTensor\"  [misc]",
      "fairness_metrics_fcc9f2.py:408: error: Value expression in dictionary comprehension has incompatible type \"Tensor\"; expected type \"FloatTensor\"  [misc]",
      "fairness_metrics_fcc9f2.py:418: error: Incompatible types in assignment (expression has type \"Tensor\", target has type \"FloatTensor\")  [assignment]",
      "fairness_metrics_fcc9f2.py:421: error: Incompatible types in assignment (expression has type \"Tensor\", target has type \"FloatTensor\")  [assignment]",
      "fairness_metrics_fcc9f2.py:425: error: Too many arguments  [call-arg]",
      "fairness_metrics_fcc9f2.py:425: error: Incompatible types in assignment (expression has type \"Tensor\", target has type \"FloatTensor\")  [assignment]",
      "fairness_metrics_fcc9f2.py:425: error: Argument 1 has incompatible type \"Tensor\"; expected \"Distribution\"  [arg-type]",
      "fairness_metrics_fcc9f2.py:425: error: Argument 2 has incompatible type \"Tensor\"; expected \"Distribution\"  [arg-type]",
      "Found 21 errors in 1 file (checked 1 source file)"
    ]
  },
  "fork_transition_eab473.py": {
    "base_stats": {
      "total_parameters": 61,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 61,
      "parameters_with_annotations": 61
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "fork_transition_eab473.py:412: error: Argument 5 to \"_transition_until_active\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]",
      "fork_transition_eab473.py:421: error: Argument \"ignoring_proposers\" to \"transition_to_next_epoch_and_append_blocks\" has incompatible type \"Optional[List[Optional[int]]]\"; expected \"Optional[List[int]]\"  [arg-type]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "IPairList_2e2b02.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 26,
      "parameters_with_annotations": 16
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "IPairList_2e2b02.py:201: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "IPairList_2e2b02.py:17: error: Name \"TypedDict\" is not defined  [name-defined]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "pin_fe5cb3.py": {
    "base_stats": {
      "total_parameters": 32,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 32,
      "parameters_with_annotations": 22
    },
    "base_error_count": 0,
    "llm_error_count": 4,
    "base_errors": [],
    "llm_errors": [
      "pin_fe5cb3.py:73: error: Incompatible return value type (got \"Union[bool, int, None]\", expected \"bool\")  [return-value]",
      "pin_fe5cb3.py:126: error: Incompatible return value type (got \"Union[bool, int, None]\", expected \"int\")  [return-value]",
      "pin_fe5cb3.py:184: error: Incompatible return value type (got \"Union[bool, int, None]\", expected \"bool\")  [return-value]",
      "pin_fe5cb3.py:250: error: Incompatible return value type (got \"Union[bool, int, None]\", expected \"int\")  [return-value]",
      "Found 4 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_categorical_c93963.py": {
    "base_stats": {
      "total_parameters": 105,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 161,
      "parameters_with_annotations": 161
    },
    "base_error_count": 0,
    "llm_error_count": 5,
    "base_errors": [],
    "llm_errors": [
      "test_categorical_c93963.py:3584: error: Incompatible types in assignment (expression has type \"Type[FutureWarning]\", variable has type \"Optional[Warning]\")  [assignment]",
      "test_categorical_c93963.py:3767: error: Incompatible types in assignment (expression has type \"Type[FutureWarning]\", variable has type \"Optional[Warning]\")  [assignment]",
      "test_categorical_c93963.py:3950: error: Incompatible types in assignment (expression has type \"Type[FutureWarning]\", variable has type \"Optional[Warning]\")  [assignment]",
      "test_categorical_c93963.py:4133: error: Incompatible types in assignment (expression has type \"Type[FutureWarning]\", variable has type \"Optional[Warning]\")  [assignment]",
      "test_categorical_c93963.py:4316: error: Incompatible types in assignment (expression has type \"Type[FutureWarning]\", variable has type \"Optional[Warning]\")  [assignment]",
      "Found 5 errors in 1 file (checked 1 source file)"
    ]
  },
  "_cert_chain_analyzer_dafae6.py": {
    "base_stats": {
      "total_parameters": 10,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 10,
      "parameters_with_annotations": 5
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "_cert_chain_analyzer_dafae6.py:224: error: Missing positional argument \"verified_certificate_chain\" in call to \"CertificateDeploymentAnalysisResult\"  [call-arg]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "exceptions_667b5e.py": {
    "base_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 11
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "exceptions_667b5e.py:6: error: Incompatible types in assignment (expression has type \"int\", base class \"tuple\" defined the type as \"Callable[[Tuple[int, ...], Any, SupportsIndex, SupportsIndex], int]\")  [assignment]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "execution_context_66f661.py": {
    "base_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 16,
      "parameters_with_annotations": 9
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "execution_context_66f661.py:32: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"Union[int, str]\")  [assignment]",
      "execution_context_66f661.py:230: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"str\")  [assignment]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "files_a4064b.py": {
    "base_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 31
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "files_a4064b.py:103: error: Argument 1 to \"__call__\" of \"_lru_cache_wrapper\" has incompatible type \"Iterable[Union[str, Path]]\"; expected \"Hashable\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "formatters_73c936.py": {
    "base_stats": {
      "total_parameters": 14,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 14,
      "parameters_with_annotations": 10
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "formatters_73c936.py:73: error: Argument 3 to \"__init__\" of \"Formatter\" has incompatible type \"str\"; expected \"Literal['%', '{', '$']\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "image_processing_d971eb.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 23,
      "parameters_with_annotations": 16
    },
    "base_error_count": 1,
    "llm_error_count": 3,
    "base_errors": [
      "image_processing_d971eb.py:164: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "image_processing_d971eb.py:166: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"int\")  [assignment]",
      "image_processing_d971eb.py:167: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"List[Any]\")  [assignment]",
      "image_processing_d971eb.py:172: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"str\")  [assignment]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "message_6587fb.py": {
    "base_stats": {
      "total_parameters": 97,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 97,
      "parameters_with_annotations": 97
    },
    "base_error_count": 0,
    "llm_error_count": 4,
    "base_errors": [],
    "llm_errors": [
      "message_6587fb.py:686: error: Argument \"input_dict\" to \"aggregate_pms\" has incompatible type \"Dict[int, RawUnreadDirectMessageDict]\"; expected \"Dict[int, Dict[str, Any]]\"  [arg-type]",
      "message_6587fb.py:687: error: Argument \"input_dict\" to \"aggregate_streams\" has incompatible type \"Dict[int, RawUnreadStreamDict]\"; expected \"Dict[int, Dict[str, Any]]\"  [arg-type]",
      "message_6587fb.py:688: error: Argument \"input_dict\" to \"aggregate_direct_message_groups\" has incompatible type \"Dict[int, RawUnreadDirectMessageGroupDict]\"; expected \"Dict[int, Dict[str, Any]]\"  [arg-type]",
      "message_6587fb.py:928: error: Invalid index type \"Optional[int]\" for \"Dict[int, Dict[str, Any]]\"; expected type \"int\"  [index]",
      "Found 4 errors in 1 file (checked 1 source file)"
    ]
  },
  "sensor_b3b9e2.py": {
    "base_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 15
    },
    "base_error_count": 0,
    "llm_error_count": 2,
    "base_errors": [],
    "llm_errors": [
      "sensor_b3b9e2.py:117: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"int\")  [assignment]",
      "sensor_b3b9e2.py:168: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"int\")  [assignment]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_merge_asof_031054.py": {
    "base_stats": {
      "total_parameters": 143,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 148,
      "parameters_with_annotations": 78
    },
    "base_error_count": 0,
    "llm_error_count": 5,
    "base_errors": [],
    "llm_errors": [
      "test_merge_asof_031054.py:1308: error: List item 0 has incompatible type \"float\"; expected \"str\"  [list-item]",
      "test_merge_asof_031054.py:1308: error: List item 1 has incompatible type \"float\"; expected \"str\"  [list-item]",
      "test_merge_asof_031054.py:1309: error: List item 0 has incompatible type \"float\"; expected \"str\"  [list-item]",
      "test_merge_asof_031054.py:1309: error: List item 1 has incompatible type \"float\"; expected \"str\"  [list-item]",
      "test_merge_asof_031054.py:1309: error: List item 2 has incompatible type \"float\"; expected \"str\"  [list-item]",
      "Found 5 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_web_response_099ecd.py": {
    "base_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 14
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "test_web_response_099ecd.py:798: error: Argument 1 to \"BufferedReader\" has incompatible type \"BytesIO\"; expected \"RawIOBase\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "test_web_response_099ecd.py:924: error: Argument 1 to \"BufferedReader\" has incompatible type \"BytesIO\"; expected \"RawIOBase\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "transformation_82baef.py": {
    "base_stats": {
      "total_parameters": 106,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 107,
      "parameters_with_annotations": 107
    },
    "base_error_count": 0,
    "llm_error_count": 5,
    "base_errors": [],
    "llm_errors": [
      "transformation_82baef.py:620: error: Argument 1 to \"map\" has incompatible type \"Type[reversed[Any]]\"; expected \"Callable[[Tuple[int, Any]], Tuple[Any, int]]\"  [arg-type]",
      "transformation_82baef.py:831: error: Value expression in dictionary comprehension has incompatible type \"Dict[Any, float]\"; expected type \"float\"  [misc]",
      "transformation_82baef.py:835: error: Argument 3 to \"apply_replacements\" has incompatible type \"Dict[str, float]\"; expected \"Dict[str, Dict[Any, Any]]\"  [arg-type]",
      "transformation_82baef.py:982: error: Incompatible types in assignment (expression has type \"Optional[List[List[str]]]\", variable has type \"List[List[str]]\")  [assignment]",
      "transformation_82baef.py:1042: error: Need type annotation for \"missing_by_row_list\"  [var-annotated]",
      "Found 5 errors in 1 file (checked 1 source file)"
    ]
  },
  "_content_aabc8a.py": {
    "base_stats": {
      "total_parameters": 26,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 26,
      "parameters_with_annotations": 20
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "_content_aabc8a.py:97: error: Argument 1 to \"IteratorByteStream\" has incompatible type \"Union[bytes, str, Iterable[bytes]]\"; expected \"Iterable[bytes]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "arguments_9b0c43.py": {
    "base_stats": {
      "total_parameters": 75,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 96,
      "parameters_with_annotations": 89
    },
    "base_error_count": 1,
    "llm_error_count": 1,
    "base_errors": [
      "arguments_9b0c43.py:11: error: No parent module -- cannot perform relative import",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "arguments_9b0c43.py:11: error: No parent module -- cannot perform relative import",
      "Found 1 error in 1 file (errors prevented further checking)"
    ]
  },
  "client_processing_dfe140.py": {
    "base_stats": {
      "total_parameters": 0,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 22,
      "parameters_with_annotations": 22
    },
    "base_error_count": 1,
    "llm_error_count": 3,
    "base_errors": [
      "client_processing_dfe140.py:151: error: invalid syntax  [syntax]",
      "Found 1 error in 1 file (errors prevented further checking)"
    ],
    "llm_errors": [
      "client_processing_dfe140.py:111: error: Unexpected keyword argument \"axis\"  [call-arg]",
      "client_processing_dfe140.py:122: error: Unexpected keyword argument \"axis\"  [call-arg]",
      "client_processing_dfe140.py:233: error: Argument 1 to \"StringIO\" has incompatible type \"Union[str, Dict[str, Any]]\"; expected \"Optional[str]\"  [arg-type]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "discovery_df519d.py": {
    "base_stats": {
      "total_parameters": 26,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 26,
      "parameters_with_annotations": 21
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "discovery_df519d.py:70: error: Argument 1 to \"get\" of \"dict\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "schemas_911003.py": {
    "base_stats": {
      "total_parameters": 26,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 25,
      "parameters_with_annotations": 16
    },
    "base_error_count": 0,
    "llm_error_count": 1,
    "base_errors": [],
    "llm_errors": [
      "schemas_911003.py:577: error: Argument 1 to \"Path\" has incompatible type \"Optional[str]\"; expected \"Union[str, PathLike[str]]\"  [arg-type]",
      "Found 1 error in 1 file (checked 1 source file)"
    ]
  },
  "test_expected_output_03115c.py": {
    "base_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 31,
      "parameters_with_annotations": 30
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "test_expected_output_03115c.py:26: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]",
      "test_expected_output_03115c.py:41: error: Name \"foo\" is not defined  [name-defined]",
      "test_expected_output_03115c.py:41: error: Name \"bar\" is not defined  [name-defined]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "test_meta_learners_15283b.py": {
    "base_stats": {
      "total_parameters": 19,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 19,
      "parameters_with_annotations": 19
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "test_meta_learners_15283b.py:415: error: Incompatible return value type (got \"Tuple[Callable[[Any], Any], Any, Dict[<nothing>, <nothing>]]\", expected \"Callable[..., Any]\")  [return-value]",
      "test_meta_learners_15283b.py:422: error: Argument 2 to \"isinstance\" has incompatible type \"<typing special form>\"; expected \"_ClassInfo\"  [arg-type]",
      "test_meta_learners_15283b.py:436: error: Incompatible return value type (got \"Tuple[Callable[[Any], Any], Any, Dict[<nothing>, <nothing>]]\", expected \"Callable[..., Any]\")  [return-value]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "util_b72b9c.py": {
    "base_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 18,
      "parameters_with_annotations": 6
    },
    "base_error_count": 0,
    "llm_error_count": 6,
    "base_errors": [],
    "llm_errors": [
      "util_b72b9c.py:182: error: Argument 1 to \"float\" has incompatible type \"Optional[Any]\"; expected \"Union[SupportsFloat, SupportsIndex, str, Buffer]\"  [arg-type]",
      "util_b72b9c.py:190: error: Argument 1 to \"float\" has incompatible type \"Optional[Any]\"; expected \"Union[SupportsFloat, SupportsIndex, str, Buffer]\"  [arg-type]",
      "util_b72b9c.py:198: error: Argument 1 to \"int\" has incompatible type \"Optional[Any]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]",
      "util_b72b9c.py:206: error: Argument 1 to \"int\" has incompatible type \"Optional[Any]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]",
      "util_b72b9c.py:214: error: Argument 1 to \"float\" has incompatible type \"Optional[Any]\"; expected \"Union[SupportsFloat, SupportsIndex, str, Buffer]\"  [arg-type]",
      "util_b72b9c.py:222: error: Argument 1 to \"int\" has incompatible type \"Optional[Any]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]",
      "Found 6 errors in 1 file (checked 1 source file)"
    ]
  },
  "v2_validated_func_97b85a.py": {
    "base_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 8
    },
    "base_error_count": 2,
    "llm_error_count": 3,
    "base_errors": [
      "v2_validated_func_97b85a.py:15: error: \"type\" expects no type arguments, but 1 given  [type-arg]",
      "v2_validated_func_97b85a.py:15: error: \"dict\" is not subscriptable  [misc]",
      "Found 2 errors in 1 file (checked 1 source file)"
    ],
    "llm_errors": [
      "v2_validated_func_97b85a.py:16: error: \"type\" expects no type arguments, but 1 given  [type-arg]",
      "v2_validated_func_97b85a.py:18: error: ClassVar can only be used for assignments in class body  [misc]",
      "v2_validated_func_97b85a.py:19: error: ClassVar can only be used for assignments in class body  [misc]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  },
  "__init___98a815.py": {
    "base_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 0
    },
    "llm_stats": {
      "total_parameters": 13,
      "parameters_with_annotations": 10
    },
    "base_error_count": 0,
    "llm_error_count": 3,
    "base_errors": [],
    "llm_errors": [
      "__init___98a815.py:49: error: Incompatible types in assignment (expression has type \"staticmethod[[VarArg(Any), KwArg(Any)], Any]\", variable has type \"Callable[..., Any]\")  [assignment]",
      "__init___98a815.py:50: error: Incompatible types in assignment (expression has type \"staticmethod[[VarArg(Any), KwArg(Any)], Any]\", variable has type \"Callable[..., Any]\")  [assignment]",
      "__init___98a815.py:52: error: Incompatible types in assignment (expression has type \"staticmethod[[VarArg(Any), KwArg(Any)], Any]\", variable has type \"Callable[[int, int, Any], int]\")  [assignment]",
      "Found 3 errors in 1 file (checked 1 source file)"
    ]
  }
}