{
    "switch_5474d5.py": {
        "stats": {
            "total_parameters": 24,
            "parameters_with_annotations": 15
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "google_config_4b4b29.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "google_config_4b4b29.py:128: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "scope_ba10d8.py": {
        "stats": {
            "total_parameters": 37,
            "parameters_with_annotations": 25
        },
        "error_count": 5,
        "isCompiled": false,
        "errors": [
            "scope_ba10d8.py:65: error: Argument 1 to \"ord\" has incompatible type \"str | int\"; expected \"str | bytes | bytearray\"  [arg-type]",
            "scope_ba10d8.py:67: error: Incompatible types in assignment (expression has type \"str | int\", variable has type \"int\")  [assignment]",
            "scope_ba10d8.py:130: error: \"Scope\" has no attribute \"func_vbgocz63\"  [attr-defined]",
            "scope_ba10d8.py:145: error: Unsupported left operand type for + (\"Sequence[Mapping[str, Any]]\")  [operator]",
            "scope_ba10d8.py:146: error: Argument 1 to \"DeepChainMap\" has incompatible type \"*Sequence[Mapping[str, Any]]\"; expected \"MutableMapping[str, Any]\"  [arg-type]",
            "Found 5 errors in 1 file (checked 1 source file)"
        ]
    },
    "awsclient_860c67.py": {
        "stats": {
            "total_parameters": 100,
            "parameters_with_annotations": 68
        },
        "error_count": 27,
        "isCompiled": false,
        "errors": [
            "awsclient_860c67.py:158: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:166: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:177: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:193: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:201: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:205: error: Need type annotation for \"vpc_config\"  [var-annotated]",
            "awsclient_860c67.py:213: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:218: error: \"TypedAWSClient\" has no attribute \"_get_lambda_code_deployment_error\"  [attr-defined]",
            "awsclient_860c67.py:221: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:229: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:269: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:282: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:291: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:317: error: \"TypedAWSClient\" has no attribute \"get_custom_domain_params_v2\"  [attr-defined]",
            "awsclient_860c67.py:326: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:328: error: \"TypedAWSClient\" has no attribute \"_call_client_method_with_retries\"  [attr-defined]",
            "awsclient_860c67.py:350: error: Incompatible return value type (got \"dict[str, Any]\", expected \"DomainNameResponse\")  [return-value]",
            "awsclient_860c67.py:353: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:355: error: \"TypedAWSClient\" has no attribute \"_call_client_method_with_retries\"  [attr-defined]",
            "awsclient_860c67.py:366: error: Incompatible return value type (got \"dict[str, Any]\", expected \"DomainNameResponse\")  [return-value]",
            "awsclient_860c67.py:370: error: \"TypedAWSClient\" has no attribute \"_call_client_method_with_retries\"  [attr-defined]",
            "awsclient_860c67.py:371: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:378: error: \"TypedAWSClient\" has no attribute \"_get_lambda_code_deployment_error\"  [attr-defined]",
            "awsclient_860c67.py:389: error: Incompatible types in assignment (expression has type \"bytes\", target has type \"str\")  [assignment]",
            "awsclient_860c67.py:391: error: \"TypedAWSClient\" has no attribute \"_client\"  [attr-defined]",
            "awsclient_860c67.py:395: error: Missing return statement  [return]",
            "awsclient_860c67.py:400: error: Return value expected  [return-value]",
            "Found 27 errors in 1 file (checked 1 source file)"
        ]
    },
    "registry_6e5f77.py": {
        "stats": {
            "total_parameters": 15,
            "parameters_with_annotations": 11
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "registry_6e5f77.py:56: error: Name \"_process_group_platform\" is not defined  [name-defined]",
            "registry_6e5f77.py:85: error: \"GroupIntegrationRegistry\" has no attribute \"on_off_states\"  [attr-defined]",
            "registry_6e5f77.py:103: error: Too many arguments for \"SingleStateType\"  [call-arg]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "conftest_4ecb9c.py": {
        "stats": {
            "total_parameters": 10,
            "parameters_with_annotations": 10
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "projected_gradient_descent_d15783.py": {
        "stats": {
            "total_parameters": 15,
            "parameters_with_annotations": 6
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "freqtradebot_43234d.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "freqtradebot_43234d.py:328: error: f-string: unmatched '['  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "binary_sensor_f0d918.py": {
        "stats": {
            "total_parameters": 42,
            "parameters_with_annotations": 36
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "http_server_4a75c7.py": {
        "stats": {
            "total_parameters": 16,
            "parameters_with_annotations": 13
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "http_server_4a75c7.py:66: error: Incompatible types in assignment (expression has type \"int | None\", variable has type \"int\")  [assignment]",
            "http_server_4a75c7.py:80: error: Argument 2 to \"send_header\" of \"BaseHTTPRequestHandler\" has incompatible type \"str | None\"; expected \"str\"  [arg-type]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "test_websocket_handshake_a4bf54.py": {
        "stats": {
            "total_parameters": 5,
            "parameters_with_annotations": 5
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "test_meta_learners_15283b.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_meta_learners_15283b.py:263: error: '[' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_reductions_87ff0d.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_reductions_87ff0d.py:274: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "rate_limiter_5a146f.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "rate_limiter_5a146f.py:18: error: '[' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "sensor_efafae.py": {
        "stats": {
            "total_parameters": 9,
            "parameters_with_annotations": 4
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "cover_b5d82f.py": {
        "stats": {
            "total_parameters": 13,
            "parameters_with_annotations": 4
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "calendar_819d29.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "calendar_819d29.py:344: error: '{' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "weather_020398.py": {
        "stats": {
            "total_parameters": 22,
            "parameters_with_annotations": 13
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "execution_855aa0.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "execution_855aa0.py:38: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "_arrow_string_mixins_7654a8.py": {
        "stats": {
            "total_parameters": 82,
            "parameters_with_annotations": 46
        },
        "error_count": 74,
        "isCompiled": false,
        "errors": [
            "_arrow_string_mixins_7654a8.py:31: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:32: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_int_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:35: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:38: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:42: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:44: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:49: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:51: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:56: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:58: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:69: error: \"ArrowStringArrayMixin\" has no attribute \"astype\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:72: error: \"type[ArrowStringArrayMixin]\" has no attribute \"_from_sequence\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:72: error: \"ArrowStringArrayMixin\" has no attribute \"dtype\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:81: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:85: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:97: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:99: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:105: error: \"ArrowStringArrayMixin\" has no attribute \"_apply_elementwise\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:106: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:115: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:125: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:135: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:140: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:143: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:146: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:150: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:151: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:152: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:155: error: \"ArrowStringArrayMixin\" has no attribute \"_apply_elementwise\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:159: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:160: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:161: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:166: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:168: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:170: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:172: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:174: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:179: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:181: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:183: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:185: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:187: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:190: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:191: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:194: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:195: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:198: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:199: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:202: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:203: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:206: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:207: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:210: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:211: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:214: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:215: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:218: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:219: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:222: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:223: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:226: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:227: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:238: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:239: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_bool_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:244: error: \"ArrowStringArrayMixin\" has no attribute \"_str_contains\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:249: error: \"ArrowStringArrayMixin\" has no attribute \"_str_match\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:254: error: \"ArrowStringArrayMixin\" has no attribute \"_apply_elementwise\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:256: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_int_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:258: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:261: error: \"ArrowStringArrayMixin\" has no attribute \"_apply_elementwise\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:263: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_int_result\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:268: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:273: error: \"ArrowStringArrayMixin\" has no attribute \"_pa_array\"  [attr-defined]",
            "_arrow_string_mixins_7654a8.py:278: error: \"ArrowStringArrayMixin\" has no attribute \"_convert_int_result\"  [attr-defined]",
            "Found 74 errors in 1 file (checked 1 source file)"
        ]
    },
    "gymexperiments_f3782d.py": {
        "stats": {
            "total_parameters": 37,
            "parameters_with_annotations": 37
        },
        "error_count": 11,
        "isCompiled": false,
        "errors": [
            "gymexperiments_f3782d.py:20: error: Unsupported operand types for in (\"str | None\" and \"str\")  [operator]",
            "gymexperiments_f3782d.py:22: error: List item 0 has incompatible type \"str | None\"; expected \"str\"  [list-item]",
            "gymexperiments_f3782d.py:30: error: Argument 1 to \"int\" has incompatible type \"str | None\"; expected \"str | Buffer | SupportsInt | SupportsIndex | SupportsTrunc\"  [arg-type]",
            "gymexperiments_f3782d.py:112: error: List item 0 has incompatible type \"int\"; expected \"None\"  [list-item]",
            "gymexperiments_f3782d.py:113: error: List item 0 has incompatible type \"int\"; expected \"None\"  [list-item]",
            "gymexperiments_f3782d.py:114: error: List item 0 has incompatible type \"int\"; expected \"None\"  [list-item]",
            "gymexperiments_f3782d.py:114: error: List item 1 has incompatible type \"int\"; expected \"None\"  [list-item]",
            "gymexperiments_f3782d.py:114: error: List item 2 has incompatible type \"int\"; expected \"None\"  [list-item]",
            "gymexperiments_f3782d.py:119: error: List item 0 has incompatible type \"int\"; expected \"None\"  [list-item]",
            "gymexperiments_f3782d.py:119: error: List item 1 has incompatible type \"int\"; expected \"None\"  [list-item]",
            "gymexperiments_f3782d.py:119: error: List item 2 has incompatible type \"int\"; expected \"None\"  [list-item]",
            "Found 11 errors in 1 file (checked 1 source file)"
        ]
    },
    "worker_1df819.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "worker_1df819.py:141: error: unterminated string literal (detected at line 141)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "common_5f186a.py": {
        "stats": {
            "total_parameters": 22,
            "parameters_with_annotations": 21
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "test_sql_f4958a.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_sql_f4958a.py:393: error: unterminated string literal (detected at line 393)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_webserver_68a1ed.py": {
        "stats": {
            "total_parameters": 7,
            "parameters_with_annotations": 7
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_webserver_68a1ed.py:39: error: The return type of a generator function should be \"Generator\" or one of its supertypes  [misc]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "validator_71103e.py": {
        "stats": {
            "total_parameters": 41,
            "parameters_with_annotations": 41
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "validator_71103e.py:172: error: Name \"fold_iter\" is not defined  [name-defined]",
            "validator_71103e.py:198: error: Name \"_join_split_log\" is not defined  [name-defined]",
            "validator_71103e.py:203: error: Need type annotation for \"perturbator_log\"  [var-annotated]",
            "validator_71103e.py:282: error: Name \"parallel_validator_iteration\" is not defined  [name-defined]",
            "Found 4 errors in 1 file (checked 1 source file)"
        ]
    },
    "target_8f735b.py": {
        "stats": {
            "total_parameters": 21,
            "parameters_with_annotations": 10
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "__init___7dd003.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "__init___7dd003.py:315: error: closing parenthesis ')' does not match opening parenthesis '['  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "exceptions_c3abb4.py": {
        "stats": {
            "total_parameters": 62,
            "parameters_with_annotations": 40
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "test_base_7e51af.py": {
        "stats": {
            "total_parameters": 18,
            "parameters_with_annotations": 17
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "test_binance_2f9760.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_binance_2f9760.py:211: error: unterminated string literal (detected at line 211)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "__init___e1c908.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "__init___e1c908.py:110: error: '[' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "data_drawer_b3adf2.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "data_drawer_b3adf2.py:57: error: '[' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_notify_74a852.py": {
        "stats": {
            "total_parameters": 18,
            "parameters_with_annotations": 17
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_notify_74a852.py:145: error: Incompatible types in assignment (expression has type \"str\", variable has type \"list[str]\")  [assignment]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "test_homekit_aeba14.py": {
        "stats": {
            "total_parameters": 15,
            "parameters_with_annotations": 15
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_homekit_aeba14.py:59: error: The return type of a generator function should be \"Generator\" or one of its supertypes  [misc]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "views_61a9fc.py": {
        "stats": {
            "total_parameters": 25,
            "parameters_with_annotations": 22
        },
        "error_count": 6,
        "isCompiled": false,
        "errors": [
            "views_61a9fc.py:152: error: Incompatible types in assignment (expression has type \"int\", variable has type \"str | None\")  [assignment]",
            "views_61a9fc.py:157: error: Incompatible types in assignment (expression has type \"int\", variable has type \"str | None\")  [assignment]",
            "views_61a9fc.py:190: error: Incompatible types in assignment (expression has type \"int\", variable has type \"str | None\")  [assignment]",
            "views_61a9fc.py:195: error: Incompatible types in assignment (expression has type \"int\", variable has type \"str | None\")  [assignment]",
            "views_61a9fc.py:251: error: Incompatible return value type (got \"StreamResponse\", expected \"Response\")  [return-value]",
            "views_61a9fc.py:292: error: Incompatible return value type (got \"StreamResponse\", expected \"Response\")  [return-value]",
            "Found 6 errors in 1 file (checked 1 source file)"
        ]
    },
    "streams_d2f3a4.py": {
        "stats": {
            "total_parameters": 59,
            "parameters_with_annotations": 20
        },
        "error_count": 5,
        "isCompiled": false,
        "errors": [
            "streams_d2f3a4.py:56: error: \"AsyncStreamReaderMixin\" has no attribute \"readline\"  [attr-defined]",
            "streams_d2f3a4.py:60: error: \"AsyncStreamReaderMixin\" has no attribute \"read\"  [attr-defined]",
            "streams_d2f3a4.py:64: error: \"AsyncStreamReaderMixin\" has no attribute \"readany\"  [attr-defined]",
            "streams_d2f3a4.py:72: error: Argument 1 to \"ChunkTupleAsyncStreamIterator\" has incompatible type \"AsyncStreamReaderMixin\"; expected \"StreamReader\"  [arg-type]",
            "streams_d2f3a4.py:312: error: Need type annotation for \"blocks\" (hint: \"blocks: list[<type>] = ...\")  [var-annotated]",
            "Found 5 errors in 1 file (checked 1 source file)"
        ]
    },
    "transport_2d9279.py": {
        "stats": {
            "total_parameters": 15,
            "parameters_with_annotations": 15
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "smartcontracts_ab65b2.py": {
        "stats": {
            "total_parameters": 16,
            "parameters_with_annotations": 16
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "applications_c5af27.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "applications_c5af27.py:36: error: closing parenthesis ')' does not match opening parenthesis '[' on line 34  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "pytables_63fc81.py": {
        "stats": {
            "total_parameters": 88,
            "parameters_with_annotations": 48
        },
        "error_count": 33,
        "isCompiled": false,
        "errors": [
            "pytables_63fc81.py:57: error: Incompatible return value type (got \"T\", expected \"Term | Constant\")  [return-value]",
            "pytables_63fc81.py:139: error: Too many arguments for \"object\"  [call-arg]",
            "pytables_63fc81.py:139: error: Unexpected keyword argument \"queryables\" for \"object\"  [call-arg]",
            "pytables_63fc81.py:179: error: Name \"TermValue\" is not defined  [name-defined]",
            "pytables_63fc81.py:183: error: Name \"TermValue\" is not defined  [name-defined]",
            "pytables_63fc81.py:197: error: Name \"TermValue\" is not defined  [name-defined]",
            "pytables_63fc81.py:204: error: Name \"TermValue\" is not defined  [name-defined]",
            "pytables_63fc81.py:211: error: Name \"TermValue\" is not defined  [name-defined]",
            "pytables_63fc81.py:219: error: Name \"TermValue\" is not defined  [name-defined]",
            "pytables_63fc81.py:222: error: Name \"TermValue\" is not defined  [name-defined]",
            "pytables_63fc81.py:228: error: Name \"TermValue\" is not defined  [name-defined]",
            "pytables_63fc81.py:230: error: Name \"TermValue\" is not defined  [name-defined]",
            "/opt/miniconda3/envs/ppmlenv/lib/python3.10/site-packages/mypy/typeshed/stdlib/builtins.pyi:113: note: \"object\" defined here",
            "pytables_63fc81.py:139: error: Unexpected keyword argument \"encoding\" for \"object\"  [call-arg]",
            "/opt/miniconda3/envs/ppmlenv/lib/python3.10/site-packages/mypy/typeshed/stdlib/builtins.pyi:113: note: \"object\" defined here",
            "pytables_63fc81.py:139: error: \"T\" has no attribute \"evaluate\"  [attr-defined]",
            "pytables_63fc81.py:190: error: Item \"None\" of \"str | None\" has no attribute \"startswith\"  [union-attr]",
            "pytables_63fc81.py:210: error: Item \"None\" of \"Any | None\" has no attribute \"searchsorted\"  [union-attr]",
            "pytables_63fc81.py:359: error: \"AST\" has no attribute \"op\"  [attr-defined]",
            "pytables_63fc81.py:360: error: \"AST\" has no attribute \"operand\"  [attr-defined]",
            "pytables_63fc81.py:361: error: \"AST\" has no attribute \"op\"  [attr-defined]",
            "pytables_63fc81.py:362: error: \"AST\" has no attribute \"operand\"  [attr-defined]",
            "pytables_63fc81.py:363: error: \"AST\" has no attribute \"op\"  [attr-defined]",
            "pytables_63fc81.py:368: error: \"AST\" has no attribute \"value\"  [attr-defined]",
            "pytables_63fc81.py:371: error: \"AST\" has no attribute \"targets\"  [attr-defined]",
            "pytables_63fc81.py:372: error: \"AST\" has no attribute \"value\"  [attr-defined]",
            "pytables_63fc81.py:376: error: \"AST\" has no attribute \"value\"  [attr-defined]",
            "pytables_63fc81.py:377: error: \"AST\" has no attribute \"slice\"  [attr-defined]",
            "pytables_63fc81.py:390: error: \"AST\" has no attribute \"attr\"  [attr-defined]",
            "pytables_63fc81.py:391: error: \"AST\" has no attribute \"value\"  [attr-defined]",
            "pytables_63fc81.py:392: error: \"AST\" has no attribute \"ctx\"  [attr-defined]",
            "pytables_63fc81.py:407: error: Incompatible return value type (got \"AST\", expected \"Eq\")  [return-value]",
            "pytables_63fc81.py:410: error: \"AST\" has no attribute \"op\"  [attr-defined]",
            "Found 31 errors in 1 file (checked 1 source file)"
        ]
    },
    "database_5bbb39.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "database_5bbb39.py:442: error: expected ':'  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "sensor_5837db.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "sensor_5837db.py:125: error: f-string: unmatched '('  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "function_184992.py": {
        "stats": {
            "total_parameters": 44,
            "parameters_with_annotations": 42
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "IPairList_2e2b02.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "IPairList_2e2b02.py:238: error: f-string: unmatched '['  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "datatree_65bfb0.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "datatree_65bfb0.py:364: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "configurations_98b5ec.py": {
        "stats": {
            "total_parameters": 34,
            "parameters_with_annotations": 19
        },
        "error_count": 6,
        "isCompiled": false,
        "errors": [
            "configurations_98b5ec.py:43: error: Incompatible types in assignment (expression has type \"list[str]\", target has type \"str\")  [assignment]",
            "configurations_98b5ec.py:44: error: Incompatible types in assignment (expression has type \"list[str]\", target has type \"str\")  [assignment]",
            "configurations_98b5ec.py:51: error: Incompatible types in assignment (expression has type \"list[str]\", target has type \"str\")  [assignment]",
            "configurations_98b5ec.py:58: error: Incompatible types in assignment (expression has type \"list[str]\", target has type \"str\")  [assignment]",
            "configurations_98b5ec.py:330: error: \"DBAPIConnection\" has no attribute \"isolation_level\"  [attr-defined]",
            "configurations_98b5ec.py:335: error: \"DBAPIConnection\" has no attribute \"exec_driver_sql\"  [attr-defined]",
            "Found 6 errors in 1 file (checked 1 source file)"
        ]
    },
    "device_4d4bcc.py": {
        "stats": {
            "total_parameters": 49,
            "parameters_with_annotations": 25
        },
        "error_count": 28,
        "isCompiled": false,
        "errors": [
            "device_4d4bcc.py:39: error: \"RachioPerson\" has no attribute \"_setup\"  [attr-defined]",
            "device_4d4bcc.py:53: error: \"RachioIro\" has no attribute \"pause_watering\"  [attr-defined]",
            "device_4d4bcc.py:60: error: \"RachioIro\" has no attribute \"resume_watering\"  [attr-defined]",
            "device_4d4bcc.py:67: error: \"RachioIro\" has no attribute \"stop_watering\"  [attr-defined]",
            "device_4d4bcc.py:71: error: Name \"stop_water\" is not defined  [name-defined]",
            "device_4d4bcc.py:75: error: Name \"pause_water\" is not defined  [name-defined]",
            "device_4d4bcc.py:77: error: Name \"resume_water\" is not defined  [name-defined]",
            "device_4d4bcc.py:83: error: Name \"is_invalid_auth_code\" is not defined  [name-defined]",
            "device_4d4bcc.py:83: error: Invalid index type \"int\" for \"dict[str, Any]\"; expected type \"str\"  [index]",
            "device_4d4bcc.py:85: error: Invalid index type \"int\" for \"dict[str, Any]\"; expected type \"str\"  [index]",
            "device_4d4bcc.py:87: error: Invalid index type \"int\" for \"dict[str, Any]\"; expected type \"str\"  [index]",
            "device_4d4bcc.py:89: error: Name \"is_invalid_auth_code\" is not defined  [name-defined]",
            "device_4d4bcc.py:89: error: Invalid index type \"int\" for \"dict[str, Any]\"; expected type \"str\"  [index]",
            "device_4d4bcc.py:91: error: Invalid index type \"int\" for \"dict[str, Any]\"; expected type \"str\"  [index]",
            "device_4d4bcc.py:93: error: Invalid index type \"int\" for \"dict[str, Any]\"; expected type \"str\"  [index]",
            "device_4d4bcc.py:94: error: Invalid index type \"int\" for \"dict[str, Any]\"; expected type \"str\"  [index]",
            "device_4d4bcc.py:96: error: Invalid index type \"int\" for \"dict[str, Any]\"; expected type \"str\"  [index]",
            "device_4d4bcc.py:158: error: \"RachioIro\" has no attribute \"controller_id\"  [attr-defined]",
            "device_4d4bcc.py:162: error: \"RachioIro\" has no attribute \"_init_webhooks\"; maybe \"_webhooks\"?  [attr-defined]",
            "device_4d4bcc.py:172: error: \"RachioIro\" has no attribute \"controller_id\"  [attr-defined]",
            "device_4d4bcc.py:184: error: \"RachioIro\" has no attribute \"controller_id\"  [attr-defined]",
            "device_4d4bcc.py:186: error: Invalid index type \"int\" for \"dict[str, Any]\"; expected type \"str\"  [index]",
            "device_4d4bcc.py:187: error: Name \"_deinit_webhooks\" is not defined  [name-defined]",
            "device_4d4bcc.py:201: error: \"RachioIro\" has no attribute \"controller_id\"  [attr-defined]",
            "device_4d4bcc.py:216: error: \"RachioIro\" has no attribute \"list_zones\"  [attr-defined]",
            "device_4d4bcc.py:231: error: \"RachioIro\" has no attribute \"controller_id\"  [attr-defined]",
            "device_4d4bcc.py:236: error: \"RachioIro\" has no attribute \"controller_id\"  [attr-defined]",
            "device_4d4bcc.py:241: error: \"RachioIro\" has no attribute \"controller_id\"  [attr-defined]",
            "Found 28 errors in 1 file (checked 1 source file)"
        ]
    },
    "sensor_d95271.py": {
        "stats": {
            "total_parameters": 14,
            "parameters_with_annotations": 7
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "api_88b699.py": {
        "stats": {
            "total_parameters": 30,
            "parameters_with_annotations": 14
        },
        "error_count": 22,
        "isCompiled": false,
        "errors": [
            "api_88b699.py:35: error: \"CattDevice\" has no attribute \"_create_cast\"  [attr-defined]",
            "api_88b699.py:55: error: \"CattDevice\" has no attribute \"_create_cast\"  [attr-defined]",
            "api_88b699.py:57: error: \"CattDevice\" has no attribute \"_create_controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:75: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:76: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:77: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:79: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:85: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:89: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:90: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:94: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:95: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:103: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:104: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:112: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:113: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:121: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:122: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:130: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:138: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:146: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "api_88b699.py:154: error: \"CattDevice\" has no attribute \"controller\"; maybe \"_cast_controller\"?  [attr-defined]",
            "Found 22 errors in 1 file (checked 1 source file)"
        ]
    },
    "websocket_api_aac75a.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "websocket_api_aac75a.py:185: error: closing parenthesis ']' does not match opening parenthesis '(' on line 184  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "entity_9f065b.py": {
        "stats": {
            "total_parameters": 27,
            "parameters_with_annotations": 16
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "sum__a10910.py": {
        "stats": {
            "total_parameters": 26,
            "parameters_with_annotations": 26
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "optimiser_abeb97.py": {
        "stats": {
            "total_parameters": 13,
            "parameters_with_annotations": 7
        },
        "error_count": 8,
        "isCompiled": false,
        "errors": [
            "optimiser_abeb97.py:38: error: \"Optimiser\" has no attribute \"hill_climb\"  [attr-defined]",
            "optimiser_abeb97.py:45: error: \"Optimiser\" has no attribute \"score_function\"  [attr-defined]",
            "optimiser_abeb97.py:53: error: \"Optimiser\" has no attribute \"score_function\"  [attr-defined]",
            "optimiser_abeb97.py:54: error: \"Optimiser\" has no attribute \"current_score\"  [attr-defined]",
            "optimiser_abeb97.py:56: error: \"Optimiser\" has no attribute \"current_score\"  [attr-defined]",
            "optimiser_abeb97.py:60: error: \"Optimiser\" has no attribute \"current_score\"  [attr-defined]",
            "optimiser_abeb97.py:133: error: \"Optimiser\" has no attribute \"consider_new_data\"  [attr-defined]",
            "optimiser_abeb97.py:150: error: \"Optimiser\" has no attribute \"consider_new_data\"  [attr-defined]",
            "Found 8 errors in 1 file (checked 1 source file)"
        ]
    },
    "oauth2_4b34aa.py": {
        "stats": {
            "total_parameters": 14,
            "parameters_with_annotations": 13
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "oauth2_4b34aa.py:13: error: Name \"TYPE_CHECKING\" is not defined  [name-defined]",
            "oauth2_4b34aa.py:46: error: Name \"refresh_oauth2_token\" is not defined  [name-defined]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "addressee_265b46.py": {
        "stats": {
            "total_parameters": 35,
            "parameters_with_annotations": 27
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "test_selector_29872e.py": {
        "stats": {
            "total_parameters": 25,
            "parameters_with_annotations": 21
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "calibration_d3fe81.py": {
        "stats": {
            "total_parameters": 16,
            "parameters_with_annotations": 16
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "calibration_d3fe81.py:125: error: Incompatible return value type (got \"list[int]\", expected \"list[float]\")  [return-value]",
            "calibration_d3fe81.py:125: note: \"list\" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance",
            "calibration_d3fe81.py:125: note: Consider using \"Sequence\" instead, which is covariant",
            "calibration_d3fe81.py:125: note: Perhaps you need a type annotation for \"fair_thresholds\"? Suggestion: \"list[float]\"",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "tools_6a9569.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "tools_6a9569.py:111: error: closing parenthesis ']' does not match opening parenthesis '(' on line 105  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_runner_66f090.py": {
        "stats": {
            "total_parameters": 47,
            "parameters_with_annotations": 31
        },
        "error_count": 15,
        "isCompiled": false,
        "errors": [
            "test_runner_66f090.py:48: error: Method \"func_w6w220tz\" is marked as an override, but no base method was found with this name  [misc]",
            "test_runner_66f090.py:54: error: Method \"func_wx1ahxzw\" is marked as an override, but no base method was found with this name  [misc]",
            "test_runner_66f090.py:58: error: Method \"func_q44wo44s\" is marked as an override, but no base method was found with this name  [misc]",
            "test_runner_66f090.py:64: error: Method \"func_qoxs6fva\" is marked as an override, but no base method was found with this name  [misc]",
            "test_runner_66f090.py:70: error: Method \"func_v8jlua5y\" is marked as an override, but no base method was found with this name  [misc]",
            "test_runner_66f090.py:123: error: Variable \"multiprocessing.Value\" is not valid as a type  [valid-type]",
            "test_runner_66f090.py:123: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases",
            "test_runner_66f090.py:132: error: multiprocessing.Value? has no attribute \"get_lock\"  [attr-defined]",
            "test_runner_66f090.py:133: error: multiprocessing.Value? has no attribute \"value\"  [attr-defined]",
            "test_runner_66f090.py:134: error: multiprocessing.Value? has no attribute \"value\"  [attr-defined]",
            "test_runner_66f090.py:144: error: Name \"initialize_worker_path\" is not defined  [name-defined]",
            "test_runner_66f090.py:147: error: Name \"run_subsuite\" is not defined  [name-defined]",
            "test_runner_66f090.py:148: error: Name \"init_worker\" is not defined  [name-defined]",
            "test_runner_66f090.py:232: error: Name \"get_test_names\" is not defined  [name-defined]",
            "test_runner_66f090.py:268: error: Name \"get_tests_from_suite\" is not defined  [name-defined]",
            "Found 14 errors in 1 file (checked 1 source file)"
        ]
    },
    "freshness_735399.py": {
        "stats": {
            "total_parameters": 60,
            "parameters_with_annotations": 37
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "gen_runner_a44ef9.py": {
        "stats": {
            "total_parameters": 46,
            "parameters_with_annotations": 46
        },
        "error_count": 18,
        "isCompiled": false,
        "errors": [
            "gen_runner_a44ef9.py:37: error: Name \"generate_test_vector\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:52: error: Name \"_represent_none\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:53: error: Name \"_represent_str\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:63: error: Name \"cfg_represent_bytes\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:68: error: Name \"cfg_represent_quoted_str\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:127: error: Name \"validate_output_dir\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:184: error: Name \"generate_test_vector\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:186: error: Name \"write_result_into_diagnostics_obj\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:192: error: Name \"worker_function\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:194: error: Name \"write_result_into_diagnostics_obj\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:241: error: Name \"execute_test\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:250: error: Name \"output_part\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:250: error: Name \"dump_yaml_fn\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:270: error: Incompatible types in assignment (expression has type \"str\", variable has type \"int | None\")  [assignment]",
            "gen_runner_a44ef9.py:286: error: Argument 1 to \"append\" of \"list\" has incompatible type \"str | int\"; expected \"str\"  [arg-type]",
            "gen_runner_a44ef9.py:298: error: Name \"dump\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:332: error: Name \"dump_ssz_fn\" is not defined  [name-defined]",
            "gen_runner_a44ef9.py:346: error: Name \"dump\" is not defined  [name-defined]",
            "Found 18 errors in 1 file (checked 1 source file)"
        ]
    },
    "test_cli_4e6ec5.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_cli_4e6ec5.py:361: error: unterminated triple-quoted string literal (detected at line 380)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "parameters_38dd02.py": {
        "stats": {
            "total_parameters": 31,
            "parameters_with_annotations": 14
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "parameters_38dd02.py:64: error: Incompatible types in assignment (expression has type \"<typing special form>\", variable has type \"type[Any]\")  [assignment]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "legacy_d0ef53.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "legacy_d0ef53.py:35: error: invalid syntax. Perhaps you forgot a comma?  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "cache_053dd3.py": {
        "stats": {
            "total_parameters": 16,
            "parameters_with_annotations": 16
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "cache_053dd3.py:106: error: \"_Wrapped[[VarArg(Any), KwArg(Any)], Any, [VarArg(Any), KwArg(Any)], Response]\" has no attribute \"make_cache_key\"  [attr-defined]",
            "cache_053dd3.py:140: error: \"_Wrapped[[VarArg(Any), KwArg(Any)], Any, [VarArg(Any), KwArg(Any)], Response]\" has no attribute \"uncached\"  [attr-defined]",
            "cache_053dd3.py:141: error: \"_Wrapped[[VarArg(Any), KwArg(Any)], Any, [VarArg(Any), KwArg(Any)], Response]\" has no attribute \"cache_timeout\"  [attr-defined]",
            "cache_053dd3.py:142: error: \"_Wrapped[[VarArg(Any), KwArg(Any)], Any, [VarArg(Any), KwArg(Any)], Response]\" has no attribute \"make_cache_key\"  [attr-defined]",
            "Found 4 errors in 1 file (checked 1 source file)"
        ]
    },
    "ioloop_93815f.py": {
        "stats": {
            "total_parameters": 94,
            "parameters_with_annotations": 49
        },
        "error_count": 13,
        "isCompiled": false,
        "errors": [
            "ioloop_93815f.py:54: error: Name \"BaseAsyncIOLoop\" is not defined  [name-defined]",
            "ioloop_93815f.py:138: error: Name \"AsyncIOLoop\" is not defined  [name-defined]",
            "ioloop_93815f.py:201: error: Name \"run\" is not defined  [name-defined]",
            "ioloop_93815f.py:209: error: Name \"timeout_callback\" is not defined  [name-defined]",
            "ioloop_93815f.py:282: error: Incompatible types in assignment (expression has type \"Executor\", variable has type \"ThreadPoolExecutor\")  [assignment]",
            "ioloop_93815f.py:308: error: \"_Selectable\" has no attribute \"fileno\"  [attr-defined]",
            "ioloop_93815f.py:315: error: \"_Selectable\" has no attribute \"close\"  [attr-defined]",
            "ioloop_93815f.py:338: error: Cannot determine type of \"tdeadline\"  [has-type]",
            "ioloop_93815f.py:341: error: Cannot determine type of \"tdeadline\"  [has-type]",
            "ioloop_93815f.py:368: error: \"PeriodicCallback\" has no attribute \"_schedule_next\"  [attr-defined]",
            "ioloop_93815f.py:393: error: \"PeriodicCallback\" has no attribute \"_schedule_next\"  [attr-defined]",
            "ioloop_93815f.py:398: error: \"PeriodicCallback\" has no attribute \"_update_next\"  [attr-defined]",
            "ioloop_93815f.py:400: error: \"PeriodicCallback\" has no attribute \"_run\"  [attr-defined]",
            "Found 13 errors in 1 file (checked 1 source file)"
        ]
    },
    "usage_logger_0d0a99.py": {
        "stats": {
            "total_parameters": 18,
            "parameters_with_annotations": 14
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "_doctools_2a0387.py": {
        "stats": {
            "total_parameters": 24,
            "parameters_with_annotations": 17
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "_doctools_2a0387.py:150: error: Argument \"labels\" to \"plot\" of \"TablePlotter\" has incompatible type \"list[str]\"; expected \"tuple[str, ...]\"  [arg-type]",
            "_doctools_2a0387.py:153: error: Argument \"labels\" to \"plot\" of \"TablePlotter\" has incompatible type \"list[str]\"; expected \"tuple[str, ...]\"  [arg-type]",
            "_doctools_2a0387.py:159: error: Argument \"labels\" to \"plot\" of \"TablePlotter\" has incompatible type \"list[str]\"; expected \"tuple[str, ...]\"  [arg-type]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "utils_03a814.py": {
        "stats": {
            "total_parameters": 41,
            "parameters_with_annotations": 8
        },
        "error_count": 16,
        "isCompiled": false,
        "errors": [
            "utils_03a814.py:69: error: \"BondDevice\" has no attribute \"_has_any_action\"  [attr-defined]",
            "utils_03a814.py:73: error: \"BondDevice\" has no attribute \"_has_any_action\"  [attr-defined]",
            "utils_03a814.py:77: error: \"BondDevice\" has no attribute \"_has_any_action\"  [attr-defined]",
            "utils_03a814.py:81: error: \"BondDevice\" has no attribute \"_has_any_action\"  [attr-defined]",
            "utils_03a814.py:85: error: \"BondDevice\" has no attribute \"_has_any_action\"  [attr-defined]",
            "utils_03a814.py:89: error: \"BondDevice\" has no attribute \"_has_any_action\"  [attr-defined]",
            "utils_03a814.py:93: error: \"BondDevice\" has no attribute \"_has_any_action\"  [attr-defined]",
            "utils_03a814.py:97: error: \"BondDevice\" has no attribute \"_has_any_action\"  [attr-defined]",
            "utils_03a814.py:101: error: \"BondDevice\" has no attribute \"_has_any_action\"  [attr-defined]",
            "utils_03a814.py:106: error: \"BondDevice\" has no attribute \"_has_any_action\"  [attr-defined]",
            "utils_03a814.py:111: error: \"BondDevice\" has no attribute \"_has_any_action\"  [attr-defined]",
            "utils_03a814.py:116: error: \"BondDevice\" has no attribute \"_has_any_action\"  [attr-defined]",
            "utils_03a814.py:184: error: \"BondHub\" has no attribute \"is_bridge\"; maybe \"_bridge\"?  [attr-defined]",
            "utils_03a814.py:185: error: \"BondDevice\" has no attribute \"name\"  [attr-defined]",
            "utils_03a814.py:191: error: \"BondHub\" has no attribute \"is_bridge\"; maybe \"_bridge\"?  [attr-defined]",
            "utils_03a814.py:192: error: \"BondDevice\" has no attribute \"location\"  [attr-defined]",
            "Found 16 errors in 1 file (checked 1 source file)"
        ]
    },
    "BaseReinforcementLearningModel_998089.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "BaseReinforcementLearningModel_998089.py:103: error: f-string: unmatched '['  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "mediator_edd547.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "mediator_edd547.py:138: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_2a092a.py": {
        "stats": {
            "total_parameters": 76,
            "parameters_with_annotations": 46
        },
        "error_count": 14,
        "isCompiled": false,
        "errors": [
            "test_2a092a.py:43: error: \"Client\" has no attribute \"_chalice_config\"; maybe \"_chalice_config_obj\"?  [attr-defined]",
            "test_2a092a.py:49: error: \"Client\" has no attribute \"_chalice_config\"; maybe \"_chalice_config_obj\"?  [attr-defined]",
            "test_2a092a.py:74: error: Incompatible types in assignment (expression has type \"dict[str, str]\", variable has type \"_Environ[str]\")  [assignment]",
            "test_2a092a.py:93: error: \"TestHTTPClient\" has no attribute \"_patched_env_vars\"  [attr-defined]",
            "test_2a092a.py:98: error: \"TestHTTPClient\" has no attribute \"_error_response\"  [attr-defined]",
            "test_2a092a.py:99: error: \"type[HTTPResponse]\" has no attribute \"create_from_dict\"  [attr-defined]",
            "test_2a092a.py:106: error: \"TestHTTPClient\" has no attribute \"request\"  [attr-defined]",
            "test_2a092a.py:109: error: \"TestHTTPClient\" has no attribute \"request\"  [attr-defined]",
            "test_2a092a.py:112: error: \"TestHTTPClient\" has no attribute \"request\"  [attr-defined]",
            "test_2a092a.py:115: error: \"TestHTTPClient\" has no attribute \"request\"  [attr-defined]",
            "test_2a092a.py:118: error: \"TestHTTPClient\" has no attribute \"request\"  [attr-defined]",
            "test_2a092a.py:121: error: \"TestHTTPClient\" has no attribute \"request\"  [attr-defined]",
            "test_2a092a.py:124: error: \"TestHTTPClient\" has no attribute \"request\"  [attr-defined]",
            "test_2a092a.py:236: error: \"TestLambdaClient\" has no attribute \"_patched_env_vars\"  [attr-defined]",
            "Found 14 errors in 1 file (checked 1 source file)"
        ]
    },
    "packager_d0d7be.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "packager_d0d7be.py:357: error: unterminated string literal (detected at line 357)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_support_views_55d8a9.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_support_views_55d8a9.py:187: error: unterminated string literal (detected at line 187)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "artifacts_099b0a.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "artifacts_099b0a.py:480: error: unterminated triple-quoted string literal (detected at line 483)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "camera_4dd787.py": {
        "stats": {
            "total_parameters": 10,
            "parameters_with_annotations": 5
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "sensor_818a5d.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "sensor_818a5d.py:116: error: '[' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "git_90c119.py": {
        "stats": {
            "total_parameters": 50,
            "parameters_with_annotations": 50
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "git_90c119.py:394: error: Need type annotation for \"committers\"  [var-annotated]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "config_test_89096c.py": {
        "stats": {
            "total_parameters": 23,
            "parameters_with_annotations": 8
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "test_web_response_099ecd.py": {
        "stats": {
            "total_parameters": 11,
            "parameters_with_annotations": 11
        },
        "error_count": 7,
        "isCompiled": false,
        "errors": [
            "test_web_response_099ecd.py:241: error: Incompatible types in assignment (expression has type \"object\", variable has type \"int | float | datetime | str | None\")  [assignment]",
            "test_web_response_099ecd.py:308: error: Argument \"value\" to \"ETag\" has incompatible type \"int\"; expected \"str\"  [arg-type]",
            "test_web_response_099ecd.py:328: error: \"Callable[[str, CIMultiDict[str]], Coroutine[Any, Any, None]]\" has no attribute \"called\"  [attr-defined]",
            "test_web_response_099ecd.py:398: error: \"Callable[[str, int], None]\" has no attribute \"assert_called_with\"  [attr-defined]",
            "test_web_response_099ecd.py:425: error: \"Callable[[str, int], None]\" has no attribute \"assert_called_with\"  [attr-defined]",
            "test_web_response_099ecd.py:438: error: \"Callable[[str, int], None]\" has no attribute \"assert_called_with\"  [attr-defined]",
            "test_web_response_099ecd.py:449: error: \"Callable[[str, int], None]\" has no attribute \"assert_called_with\"  [attr-defined]",
            "Found 7 errors in 1 file (checked 1 source file)"
        ]
    },
    "stata_4ae9e0.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "stata_4ae9e0.py:42: error: f-string: unmatched '['  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "selector_62ee5d.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "selector_62ee5d.py:113: error: '[' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "project_7870ca.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "project_7870ca.py:101: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "datetimes_c4b343.py": {
        "stats": {
            "total_parameters": 61,
            "parameters_with_annotations": 26
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "datetimes_c4b343.py:53: error: \"None\" not callable  [misc]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "service_registry_e94e0b.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "service_registry_e94e0b.py:83: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "weather_ac8565.py": {
        "stats": {
            "total_parameters": 33,
            "parameters_with_annotations": 20
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "weather_ac8565.py:30: error: Name \"_calculate_unique_id\" is not defined  [name-defined]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "utils_a09b8c.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "utils_a09b8c.py:211: error: closing parenthesis ']' does not match opening parenthesis '(' on line 205  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "core_214ccb.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "core_214ccb.py:353: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_helpers_38220e.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_helpers_38220e.py:404: error: unterminated string literal (detected at line 404)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "timedeltas_44fa81.py": {
        "stats": {
            "total_parameters": 24,
            "parameters_with_annotations": 16
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "timedeltas_44fa81.py:69: error: Name \"np\" is not defined  [name-defined]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "user_deposit_72a164.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "user_deposit_72a164.py:454: error: unterminated string literal (detected at line 454)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "humidifier_e2948a.py": {
        "stats": {
            "total_parameters": 22,
            "parameters_with_annotations": 9
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "humidifier_e2948a.py:214: error: Name \"func_kdapfxyn\" is not defined  [name-defined]",
            "humidifier_e2948a.py:260: error: Incompatible types in assignment (expression has type \"int\", variable has type \"str\")  [assignment]",
            "humidifier_e2948a.py:322: error: Incompatible types in assignment (expression has type \"int\", variable has type \"str\")  [assignment]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "test_graph_69fed4.py": {
        "stats": {
            "total_parameters": 37,
            "parameters_with_annotations": 25
        },
        "error_count": 12,
        "isCompiled": false,
        "errors": [
            "test_graph_69fed4.py:44: error: Name \"func_28zs7ogb\" is not defined  [name-defined]",
            "test_graph_69fed4.py:53: error: Name \"func_28zs7ogb\" is not defined  [name-defined]",
            "test_graph_69fed4.py:57: error: Name \"func_28zs7ogb\" is not defined  [name-defined]",
            "test_graph_69fed4.py:64: error: Name \"func_28zs7ogb\" is not defined  [name-defined]",
            "test_graph_69fed4.py:67: error: Name \"func_28zs7ogb\" is not defined  [name-defined]",
            "test_graph_69fed4.py:77: error: Name \"func_28zs7ogb\" is not defined  [name-defined]",
            "test_graph_69fed4.py:85: error: Name \"func_28zs7ogb\" is not defined  [name-defined]",
            "test_graph_69fed4.py:87: error: Name \"func_28zs7ogb\" is not defined  [name-defined]",
            "test_graph_69fed4.py:89: error: Name \"func_28zs7ogb\" is not defined  [name-defined]",
            "test_graph_69fed4.py:96: error: Name \"func_28zs7ogb\" is not defined  [name-defined]",
            "test_graph_69fed4.py:98: error: Name \"func_28zs7ogb\" is not defined  [name-defined]",
            "test_graph_69fed4.py:100: error: Name \"func_28zs7ogb\" is not defined  [name-defined]",
            "Found 12 errors in 1 file (checked 1 source file)"
        ]
    },
    "numba__13f34f.py": {
        "stats": {
            "total_parameters": 42,
            "parameters_with_annotations": 42
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "_warnings_0608d5.py": {
        "stats": {
            "total_parameters": 11,
            "parameters_with_annotations": 11
        },
        "error_count": 9,
        "isCompiled": false,
        "errors": [
            "_warnings_0608d5.py:93: error: Incompatible types in assignment (expression has type \"tuple[str | None, ...]\", variable has type \"str | tuple[str, ...] | None\")  [assignment]",
            "_warnings_0608d5.py:96: error: Argument 2 to \"zip\" has incompatible type \"str | tuple[str, ...] | None\"; expected \"Iterable[str]\"  [arg-type]",
            "_warnings_0608d5.py:97: error: Name \"_assert_caught_expected_warnings\" is not defined  [name-defined]",
            "_warnings_0608d5.py:105: error: Name \"_assert_caught_expected_warnings\" is not defined  [name-defined]",
            "_warnings_0608d5.py:109: error: Name \"_assert_caught_no_extra_warnings\" is not defined  [name-defined]",
            "_warnings_0608d5.py:144: error: Name \"_assert_raised_with_correct_stacklevel\" is not defined  [name-defined]",
            "_warnings_0608d5.py:167: error: Name \"_is_unexpected_warning\" is not defined  [name-defined]",
            "_warnings_0608d5.py:197: error: Item \"None\" of \"FrameType | None\" has no attribute \"f_back\"  [union-attr]",
            "_warnings_0608d5.py:199: error: Argument 1 to \"getfile\" has incompatible type \"FrameType | None\"; expected Module | type[Any] | MethodType | FunctionType | TracebackType | FrameType | CodeType | Callable[..., Any]  [arg-type]",
            "Found 9 errors in 1 file (checked 1 source file)"
        ]
    },
    "data_kitchen_58b770.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "data_kitchen_58b770.py:289: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "simple_httpclient_5928fa.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "simple_httpclient_5928fa.py:101: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "schemas_d6d78d.py": {
        "stats": {
            "total_parameters": 61,
            "parameters_with_annotations": 43
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "sensor_c2feed.py": {
        "stats": {
            "total_parameters": 32,
            "parameters_with_annotations": 16
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "fan_7d4617.py": {
        "stats": {
            "total_parameters": 29,
            "parameters_with_annotations": 11
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "schema_generic_tests_906d8a.py": {
        "stats": {
            "total_parameters": 69,
            "parameters_with_annotations": 51
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "api_tests_78614f.py": {
        "stats": {
            "total_parameters": 94,
            "parameters_with_annotations": 94
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "lambda_dataset_8c1015.py": {
        "stats": {
            "total_parameters": 13,
            "parameters_with_annotations": 7
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "featherdatahandler_48f824.py": {
        "stats": {
            "total_parameters": 27,
            "parameters_with_annotations": 20
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "switch_045d67.py": {
        "stats": {
            "total_parameters": 19,
            "parameters_with_annotations": 14
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "base_6a0ea7.py": {
        "stats": {
            "total_parameters": 70,
            "parameters_with_annotations": 47
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "base_6a0ea7.py:38: error: \"ZulipUploadBackend\" has no attribute \"delete_message_attachment\"  [attr-defined]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "edge_positioning_82e827.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "edge_positioning_82e827.py:60: error: f-string: unmatched '('  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "sensor_cdccc8.py": {
        "stats": {
            "total_parameters": 21,
            "parameters_with_annotations": 12
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "sensor_cdccc8.py:110: error: \"PublicTransportData\" has no attribute \"update\"  [attr-defined]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "app_9acae6.py": {
        "stats": {
            "total_parameters": 102,
            "parameters_with_annotations": 58
        },
        "error_count": 13,
        "isCompiled": false,
        "errors": [
            "app_9acae6.py:23: error: Name \"TYPE_CHECKING\" is not defined  [name-defined]",
            "app_9acae6.py:44: error: Argument \"headers\" to \"Response\" has incompatible type \"dict[str, str] | None\"; expected \"dict[str, str | list[str]] | None\"  [arg-type]",
            "app_9acae6.py:51: error: Name \"_content_type_header_contains\" is not defined  [name-defined]",
            "app_9acae6.py:238: error: Unsupported target for indexed assignment (\"Collection[str]\")  [index]",
            "app_9acae6.py:270: error: \"CORSConfig\" has no attribute \"allow_headers\"; maybe \"_allow_headers\"?  [attr-defined]",
            "app_9acae6.py:282: error: \"CORSConfig\" has no attribute \"get_access_control_headers\"  [attr-defined]",
            "app_9acae6.py:314: error: \"Request\" has no attribute \"_base64decode\"; maybe \"_is_base64_encoded\"?  [attr-defined]",
            "app_9acae6.py:326: error: \"Request\" has no attribute \"raw_body\"; maybe \"_raw_body\" or \"_body\"?  [attr-defined]",
            "app_9acae6.py:354: error: Name \"handle_extra_types\" is not defined  [name-defined]",
            "app_9acae6.py:355: error: \"Response\" has no attribute \"_sort_headers\"  [attr-defined]",
            "app_9acae6.py:363: error: \"Response\" has no attribute \"_b64encode_body_if_needed\"  [attr-defined]",
            "app_9acae6.py:385: error: \"Response\" has no attribute \"_base64encode\"  [attr-defined]",
            "app_9acae6.py:409: error: \"RouteEntry\" has no attribute \"_parse_view_args\"  [attr-defined]",
            "Found 13 errors in 1 file (checked 1 source file)"
        ]
    },
    "sensor_97b467.py": {
        "stats": {
            "total_parameters": 15,
            "parameters_with_annotations": 10
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "sensor_97b467.py:109: error: \"GitLabData\" has no attribute \"_update\"; maybe \"update\"?  [attr-defined]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "conftest_06275c.py": {
        "stats": {
            "total_parameters": 29,
            "parameters_with_annotations": 29
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "api_tests_b98962.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "api_tests_b98962.py:337: error: unterminated string literal (detected at line 337)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "entities_19afaa.py": {
        "stats": {
            "total_parameters": 21,
            "parameters_with_annotations": 21
        },
        "error_count": 5,
        "isCompiled": false,
        "errors": [
            "entities_19afaa.py:16: error: Name \"apply_event_entity_id_matchers\" is not defined  [name-defined]",
            "entities_19afaa.py:17: error: Name \"apply_entities_hints\" is not defined  [name-defined]",
            "entities_19afaa.py:28: error: Name \"states_select_for_entity_ids\" is not defined  [name-defined]",
            "entities_19afaa.py:44: error: Name \"apply_event_entity_id_matchers\" is not defined  [name-defined]",
            "entities_19afaa.py:51: error: Name \"apply_entities_hints\" is not defined  [name-defined]",
            "Found 5 errors in 1 file (checked 1 source file)"
        ]
    },
    "period_85d698.py": {
        "stats": {
            "total_parameters": 54,
            "parameters_with_annotations": 31
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "image_91d679.py": {
        "stats": {
            "total_parameters": 11,
            "parameters_with_annotations": 7
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "image_91d679.py:43: error: Name \"refresh_coordinators\" is not defined  [name-defined]",
            "image_91d679.py:47: error: Name \"parse_image\" is not defined  [name-defined]",
            "image_91d679.py:108: error: Incompatible types in assignment (expression has type \"tuple[Any | BaseException, Any | BaseException]\", variable has type \"list[Any]\")  [assignment]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "climate_9e8de7.py": {
        "stats": {
            "total_parameters": 12,
            "parameters_with_annotations": 6
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "binary_sensor_a3bb34.py": {
        "stats": {
            "total_parameters": 18,
            "parameters_with_annotations": 11
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "binary_sensor_a3bb34.py:102: error: Argument 1 to \"filter\" has incompatible type \"Callable[[Any], Any]\"; expected \"Callable[[Any], TypeGuard[dict[str, Any] | None]]\"  [arg-type]",
            "binary_sensor_a3bb34.py:102: error: Value of type \"dict[str, Any] | None\" is not indexable  [index]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "sensor_31ba0c.py": {
        "stats": {
            "total_parameters": 18,
            "parameters_with_annotations": 12
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "ops_97a00f.py": {
        "stats": {
            "total_parameters": 76,
            "parameters_with_annotations": 35
        },
        "error_count": 12,
        "isCompiled": false,
        "errors": [
            "ops_97a00f.py:173: error: Incompatible return value type (got \"Any | frozenset[Any]\", expected \"bool\")  [return-value]",
            "ops_97a00f.py:281: error: \"Op\" not callable  [operator]",
            "ops_97a00f.py:282: error: \"Op\" not callable  [operator]",
            "ops_97a00f.py:305: error: Item \"Op\" of \"Term | Op\" has no attribute \"evaluate\"  [union-attr]",
            "ops_97a00f.py:307: error: Item \"Op\" of \"Term | Op\" has no attribute \"evaluate\"  [union-attr]",
            "ops_97a00f.py:329: error: Item \"Op\" of \"Term | Op\" has no attribute \"value\"  [union-attr]",
            "ops_97a00f.py:335: error: Item \"Op\" of \"Term | Op\" has no attribute \"update\"  [union-attr]",
            "ops_97a00f.py:337: error: Item \"Op\" of \"Term | Op\" has no attribute \"value\"  [union-attr]",
            "ops_97a00f.py:343: error: Item \"Op\" of \"Term | Op\" has no attribute \"update\"  [union-attr]",
            "ops_97a00f.py:353: error: Argument 1 to \"issubclass\" has incompatible type \"Callable[[], Any] | Any\"; expected \"type\"  [arg-type]",
            "ops_97a00f.py:354: error: Argument 1 to \"issubclass\" has incompatible type \"Callable[[], Any] | Any\"; expected \"type\"  [arg-type]",
            "ops_97a00f.py:390: error: \"Op\" not callable  [operator]",
            "Found 12 errors in 1 file (checked 1 source file)"
        ]
    },
    "sensor_07dce7.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "sensor_07dce7.py:172: error: f-string: unmatched '['  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "__init___97fa7b.py": {
        "stats": {
            "total_parameters": 31,
            "parameters_with_annotations": 27
        },
        "error_count": 10,
        "isCompiled": false,
        "errors": [
            "__init___97fa7b.py:53: error: Name \"discover_scripts\" is not defined  [name-defined]",
            "__init___97fa7b.py:57: error: Name \"discover_scripts\" is not defined  [name-defined]",
            "__init___97fa7b.py:58: error: Name \"reload_scripts_handler\" is not defined  [name-defined]",
            "__init___97fa7b.py:70: error: Name \"execute_script\" is not defined  [name-defined]",
            "__init___97fa7b.py:83: error: Name \"python_script_service_handler\" is not defined  [name-defined]",
            "__init___97fa7b.py:126: error: Name \"execute\" is not defined  [name-defined]",
            "__init___97fa7b.py:156: error: Name \"guarded_import\" is not defined  [name-defined]",
            "__init___97fa7b.py:178: error: Name \"protected_getattr\" is not defined  [name-defined]",
            "__init___97fa7b.py:184: error: Name \"guarded_inplacevar\" is not defined  [name-defined]",
            "__init___97fa7b.py:243: error: Name \"wrapper\" is not defined  [name-defined]",
            "Found 10 errors in 1 file (checked 1 source file)"
        ]
    },
    "switch_813f86.py": {
        "stats": {
            "total_parameters": 12,
            "parameters_with_annotations": 8
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "sensor_1c6e89.py": {
        "stats": {
            "total_parameters": 13,
            "parameters_with_annotations": 11
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "sensor_e4b539.py": {
        "stats": {
            "total_parameters": 12,
            "parameters_with_annotations": 4
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "floats_47251e.py": {
        "stats": {
            "total_parameters": 30,
            "parameters_with_annotations": 30
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "test_proxy_functional_150ce7.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_proxy_functional_150ce7.py:382: error: '[' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "__init___916118.py": {
        "stats": {
            "total_parameters": 17,
            "parameters_with_annotations": 13
        },
        "error_count": 8,
        "isCompiled": false,
        "errors": [
            "__init___916118.py:38: error: Incompatible types in assignment (expression has type \"None\", variable has type \"dict[str, Any]\")  [assignment]",
            "__init___916118.py:39: error: Incompatible types in assignment (expression has type \"None\", variable has type \"dict[str, Any]\")  [assignment]",
            "__init___916118.py:173: error: \"PrinterAPI\" has no attribute \"update\"  [attr-defined]",
            "__init___916118.py:174: error: \"PrinterAPI\" has no attribute \"update\"  [attr-defined]",
            "__init___916118.py:226: error: \"PrinterAPI\" has no attribute \"_load_entities\"; maybe \"_known_entities\"?  [attr-defined]",
            "__init___916118.py:235: error: Incompatible types in assignment (expression has type \"int\", target has type \"str\")  [assignment]",
            "__init___916118.py:248: error: Incompatible types in assignment (expression has type \"int\", target has type \"str\")  [assignment]",
            "__init___916118.py:251: error: Incompatible types in assignment (expression has type \"None\", target has type \"str\")  [assignment]",
            "Found 8 errors in 1 file (checked 1 source file)"
        ]
    },
    "__init___733adb.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "__init___733adb.py:69: error: '[' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "control_e5bc2a.py": {
        "stats": {
            "total_parameters": 31,
            "parameters_with_annotations": 22
        },
        "error_count": 11,
        "isCompiled": false,
        "errors": [
            "control_e5bc2a.py:26: error: \"FrameInfo\" has no attribute \"f_back\"  [attr-defined]",
            "control_e5bc2a.py:35: error: Argument 2 to \"func_egv6qgn6\" has incompatible type \"FrameType | None\"; expected \"FrameInfo\"  [arg-type]",
            "control_e5bc2a.py:36: error: Name \"currently_in_test_context\" is not defined  [name-defined]",
            "control_e5bc2a.py:37: error: Name \"current_build_context\" is not defined  [name-defined]",
            "control_e5bc2a.py:54: error: Argument 2 to \"func_egv6qgn6\" has incompatible type \"FrameType | None\"; expected \"FrameInfo\"  [arg-type]",
            "control_e5bc2a.py:55: error: Name \"currently_in_test_context\" is not defined  [name-defined]",
            "control_e5bc2a.py:56: error: Name \"current_build_context\" is not defined  [name-defined]",
            "control_e5bc2a.py:127: error: Cannot infer type of lambda  [misc]",
            "control_e5bc2a.py:206: error: Name \"_event_to_string\" is not defined  [name-defined]",
            "control_e5bc2a.py:207: error: Name \"_event_to_string\" is not defined  [name-defined]",
            "control_e5bc2a.py:210: error: Need type annotation for \"_events_to_strings\"  [var-annotated]",
            "Found 11 errors in 1 file (checked 1 source file)"
        ]
    },
    "querysets_ea35a5.py": {
        "stats": {
            "total_parameters": 16,
            "parameters_with_annotations": 16
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "querysets_ea35a5.py:59: error: Name \"resolve_field_lookups\" is not defined  [name-defined]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "template_0e4e35.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "template_0e4e35.py:461: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "filters_a79ada.py": {
        "stats": {
            "total_parameters": 33,
            "parameters_with_annotations": 24
        },
        "error_count": 8,
        "isCompiled": false,
        "errors": [
            "filters_a79ada.py:126: error: Incompatible return value type (got \"ColumnElement[bool]\", expected \"BinaryExpression[Any]\")  [return-value]",
            "filters_a79ada.py:128: error: Incompatible return value type (got \"ColumnElement[bool | Any]\", expected \"BinaryExpression[Any]\")  [return-value]",
            "filters_a79ada.py:130: error: Incompatible return value type (got \"ColumnElement[bool]\", expected \"BinaryExpression[Any]\")  [return-value]",
            "filters_a79ada.py:133: error: Incompatible return value type (got \"BooleanClauseList | Grouping[bool]\", expected \"BinaryExpression[Any]\")  [return-value]",
            "filters_a79ada.py:159: error: Incompatible return value type (got \"ColumnElement[bool]\", expected \"BinaryExpression[Any]\")  [return-value]",
            "filters_a79ada.py:175: error: Incompatible return value type (got \"ColumnElement[bool]\", expected \"BinaryExpression[Any]\")  [return-value]",
            "filters_a79ada.py:185: error: Incompatible return value type (got \"ColumnElement[bool]\", expected \"BinaryExpression[Any]\")  [return-value]",
            "filters_a79ada.py:196: error: Incompatible return value type (got \"ColumnElement[bool]\", expected \"BinaryExpression[Any]\")  [return-value]",
            "Found 8 errors in 1 file (checked 1 source file)"
        ]
    },
    "test_manifest_190497.py": {
        "stats": {
            "total_parameters": 53,
            "parameters_with_annotations": 41
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_manifest_190497.py:219: error: Name \"func_kajcc7go\" is not defined  [name-defined]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "entropy_test_fa6663.py": {
        "stats": {
            "total_parameters": 15,
            "parameters_with_annotations": 10
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "entropy_test_fa6663.py:44: error: Incompatible types in assignment (expression has type \"list[Tensor]\", variable has type \"Tensor\")  [assignment]",
            "entropy_test_fa6663.py:52: error: Incompatible types in assignment (expression has type \"list[Tensor]\", variable has type \"Tensor\")  [assignment]",
            "entropy_test_fa6663.py:55: error: Name \"multiple_runs\" is not defined  [name-defined]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "_api_8facbb.py": {
        "stats": {
            "total_parameters": 11,
            "parameters_with_annotations": 11
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "train_test_b790e4.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "train_test_b790e4.py:312: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "arraylike_473d9a.py": {
        "stats": {
            "total_parameters": 82,
            "parameters_with_annotations": 82
        },
        "error_count": 36,
        "isCompiled": false,
        "errors": [
            "arraylike_473d9a.py:34: error: \"T\" has no attribute \"_cmp_method\"  [attr-defined]",
            "arraylike_473d9a.py:38: error: \"T\" has no attribute \"_cmp_method\"  [attr-defined]",
            "arraylike_473d9a.py:42: error: \"T\" has no attribute \"_cmp_method\"  [attr-defined]",
            "arraylike_473d9a.py:46: error: \"T\" has no attribute \"_cmp_method\"  [attr-defined]",
            "arraylike_473d9a.py:50: error: \"T\" has no attribute \"_cmp_method\"  [attr-defined]",
            "arraylike_473d9a.py:54: error: \"T\" has no attribute \"_cmp_method\"  [attr-defined]",
            "arraylike_473d9a.py:61: error: \"T\" has no attribute \"_logical_method\"  [attr-defined]",
            "arraylike_473d9a.py:65: error: \"T\" has no attribute \"_logical_method\"  [attr-defined]",
            "arraylike_473d9a.py:69: error: \"T\" has no attribute \"_logical_method\"  [attr-defined]",
            "arraylike_473d9a.py:73: error: \"T\" has no attribute \"_logical_method\"  [attr-defined]",
            "arraylike_473d9a.py:77: error: \"T\" has no attribute \"_logical_method\"  [attr-defined]",
            "arraylike_473d9a.py:81: error: \"T\" has no attribute \"_logical_method\"  [attr-defined]",
            "arraylike_473d9a.py:88: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:92: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:96: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:100: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:104: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:108: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:112: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:116: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:120: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:124: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:128: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:132: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:136: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:140: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:144: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:148: error: \"T\" has no attribute \"_arith_method\"  [attr-defined]",
            "arraylike_473d9a.py:153: error: Name \"_standardize_out_kwarg\" is not defined  [name-defined]",
            "arraylike_473d9a.py:193: error: Name \"_reconstruct\" is not defined  [name-defined]",
            "arraylike_473d9a.py:194: error: Name \"_reconstruct\" is not defined  [name-defined]",
            "arraylike_473d9a.py:212: error: Name \"dispatch_ufunc_with_out\" is not defined  [name-defined]",
            "arraylike_473d9a.py:216: error: Name \"dispatch_reduction_ufunc\" is not defined  [name-defined]",
            "arraylike_473d9a.py:230: error: Name \"default_array_ufunc\" is not defined  [name-defined]",
            "arraylike_473d9a.py:255: error: Name \"_assign_where\" is not defined  [name-defined]",
            "arraylike_473d9a.py:262: error: Name \"_assign_where\" is not defined  [name-defined]",
            "Found 36 errors in 1 file (checked 1 source file)"
        ]
    },
    "test_denodo_4cd030.py": {
        "stats": {
            "total_parameters": 11,
            "parameters_with_annotations": 11
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "nlp_fe0862.py": {
        "stats": {
            "total_parameters": 38,
            "parameters_with_annotations": 32
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "conftest_f547b4.py": {
        "stats": {
            "total_parameters": 28,
            "parameters_with_annotations": 28
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "conftest_f547b4.py:29: error: Name \"assert_sensor_registered\" is not defined  [name-defined]",
            "conftest_f547b4.py:35: error: Name \"assert_sensor_registered\" is not defined  [name-defined]",
            "conftest_f547b4.py:41: error: Name \"assert_sensor_registered\" is not defined  [name-defined]",
            "conftest_f547b4.py:48: error: Name \"assert_sensor_registered\" is not defined  [name-defined]",
            "Found 4 errors in 1 file (checked 1 source file)"
        ]
    },
    "steps_1f3861.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "steps_1f3861.py:1: error: unterminated triple-quoted string literal (detected at line 10)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "adversarial_bias_mitigator_3ad2a0.py": {
        "stats": {
            "total_parameters": 39,
            "parameters_with_annotations": 20
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "adversarial_bias_mitigator_3ad2a0.py:98: error: \"None\" not callable  [misc]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "test_hls_610af1.py": {
        "stats": {
            "total_parameters": 15,
            "parameters_with_annotations": 14
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "test_hls_610af1.py:85: error: Unsupported operand types for * (\"int\" and \"None\")  [operator]",
            "test_hls_610af1.py:85: note: Right operand is of type \"float | None\"",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "core_6bd602.py": {
        "stats": {
            "total_parameters": 24,
            "parameters_with_annotations": 11
        },
        "error_count": 28,
        "isCompiled": false,
        "errors": [
            "core_6bd602.py:74: error: \"HypervolumePareto\" has no attribute \"add\"  [attr-defined]",
            "core_6bd602.py:100: error: \"ParetoFront\" has no attribute \"add_to_pareto\"  [attr-defined]",
            "core_6bd602.py:107: error: \"ParetoFront\" has no attribute \"add_to_pareto\"  [attr-defined]",
            "core_6bd602.py:110: error: \"ParetoFront\" has no attribute \"add_to_pareto\"  [attr-defined]",
            "core_6bd602.py:112: error: \"HypervolumePareto\" has no attribute \"_calc_hypervolume\"; maybe \"_hypervolume\" or \"_no_hypervolume\"?  [attr-defined]",
            "core_6bd602.py:118: error: \"ParetoFront\" has no attribute \"get_raw\"  [attr-defined]",
            "core_6bd602.py:121: error: \"ParetoFront\" has no attribute \"add_to_pareto\"  [attr-defined]",
            "core_6bd602.py:125: error: \"ParetoFront\" has no attribute \"get_front\"  [attr-defined]",
            "core_6bd602.py:152: error: \"ParetoFront\" has no attribute \"get_front\"  [attr-defined]",
            "core_6bd602.py:155: error: \"ParetoFront\" has no attribute \"get_raw\"  [attr-defined]",
            "core_6bd602.py:210: error: \"ParetoFront\" has no attribute \"_filter_pareto_front\"  [attr-defined]",
            "core_6bd602.py:222: error: Item \"None\" of \"Any | None\" has no attribute \"compute\"  [union-attr]",
            "core_6bd602.py:229: error: No overload variant of \"min\" matches argument types \"float\", \"floating[Any]\"  [call-overload]",
            "core_6bd602.py:229: note: Possible overload variants:",
            "core_6bd602.py:229: note:     def [SupportsRichComparisonT: SupportsDunderLT[Any] | SupportsDunderGT[Any]] min(SupportsRichComparisonT, SupportsRichComparisonT, /, *_args: SupportsRichComparisonT, key: None = ...) -> SupportsRichComparisonT",
            "core_6bd602.py:229: note:     def [_T] min(_T, _T, /, *_args: _T, key: Callable[[_T], SupportsDunderLT[Any] | SupportsDunderGT[Any]]) -> _T",
            "core_6bd602.py:229: note:     def [SupportsRichComparisonT: SupportsDunderLT[Any] | SupportsDunderGT[Any]] min(Iterable[SupportsRichComparisonT], /, *, key: None = ...) -> SupportsRichComparisonT",
            "core_6bd602.py:229: note:     def [_T] min(Iterable[_T], /, *, key: Callable[[_T], SupportsDunderLT[Any] | SupportsDunderGT[Any]]) -> _T",
            "core_6bd602.py:229: note:     def [SupportsRichComparisonT: SupportsDunderLT[Any] | SupportsDunderGT[Any], _T] min(Iterable[SupportsRichComparisonT], /, *, key: None = ..., default: _T) -> SupportsRichComparisonT | _T",
            "core_6bd602.py:229: note:     def [_T1, _T2] min(Iterable[_T1], /, *, key: Callable[[_T1], SupportsDunderLT[Any] | SupportsDunderGT[Any]], default: _T2) -> _T1 | _T2",
            "core_6bd602.py:233: error: No overload variant of \"min\" matches argument types \"float\", \"floating[Any]\"  [call-overload]",
            "core_6bd602.py:233: note: Possible overload variants:",
            "core_6bd602.py:233: note:     def [SupportsRichComparisonT: SupportsDunderLT[Any] | SupportsDunderGT[Any]] min(SupportsRichComparisonT, SupportsRichComparisonT, /, *_args: SupportsRichComparisonT, key: None = ...) -> SupportsRichComparisonT",
            "core_6bd602.py:233: note:     def [_T] min(_T, _T, /, *_args: _T, key: Callable[[_T], SupportsDunderLT[Any] | SupportsDunderGT[Any]]) -> _T",
            "core_6bd602.py:233: note:     def [SupportsRichComparisonT: SupportsDunderLT[Any] | SupportsDunderGT[Any]] min(Iterable[SupportsRichComparisonT], /, *, key: None = ...) -> SupportsRichComparisonT",
            "core_6bd602.py:233: note:     def [_T] min(Iterable[_T], /, *, key: Callable[[_T], SupportsDunderLT[Any] | SupportsDunderGT[Any]]) -> _T",
            "core_6bd602.py:233: note:     def [SupportsRichComparisonT: SupportsDunderLT[Any] | SupportsDunderGT[Any], _T] min(Iterable[SupportsRichComparisonT], /, *, key: None = ..., default: _T) -> SupportsRichComparisonT | _T",
            "core_6bd602.py:233: note:     def [_T1, _T2] min(Iterable[_T1], /, *, key: Callable[[_T1], SupportsDunderLT[Any] | SupportsDunderGT[Any]], default: _T2) -> _T1 | _T2",
            "Found 14 errors in 1 file (checked 1 source file)"
        ]
    },
    "conftest_bc6db5.py": {
        "stats": {
            "total_parameters": 8,
            "parameters_with_annotations": 8
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "switch_083dac.py": {
        "stats": {
            "total_parameters": 16,
            "parameters_with_annotations": 8
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "sampler_d1337e.py": {
        "stats": {
            "total_parameters": 52,
            "parameters_with_annotations": 35
        },
        "error_count": 23,
        "isCompiled": false,
        "errors": [
            "sampler_d1337e.py:30: error: Incompatible types in assignment (expression has type \"FrameType | None\", variable has type \"FrameType\")  [assignment]",
            "sampler_d1337e.py:43: error: Incompatible types in assignment (expression has type \"float\", target has type \"int\")  [assignment]",
            "sampler_d1337e.py:123: error: \"TraceSampler\" has no attribute \"_greenlet_profiler\"  [attr-defined]",
            "sampler_d1337e.py:124: error: \"TraceSampler\" has no attribute \"_thread_profiler\"  [attr-defined]",
            "sampler_d1337e.py:138: error: \"TraceSampler\" has no attribute \"_should_sample\"  [attr-defined]",
            "sampler_d1337e.py:139: error: Item \"FlameGraphCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"collect\"  [union-attr]",
            "sampler_d1337e.py:139: error: Item \"MemoryCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"collect\"  [union-attr]",
            "sampler_d1337e.py:139: error: Item \"ObjectCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"collect\"  [union-attr]",
            "sampler_d1337e.py:147: error: \"TraceSampler\" has no attribute \"_should_sample\"  [attr-defined]",
            "sampler_d1337e.py:148: error: Item \"FlameGraphCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"collect\"  [union-attr]",
            "sampler_d1337e.py:148: error: Item \"MemoryCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"collect\"  [union-attr]",
            "sampler_d1337e.py:148: error: Item \"ObjectCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"collect\"  [union-attr]",
            "sampler_d1337e.py:155: error: Item \"FlameGraphCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"stop\"  [union-attr]",
            "sampler_d1337e.py:155: error: Item \"MemoryCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"stop\"  [union-attr]",
            "sampler_d1337e.py:155: error: Item \"ObjectCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"stop\"  [union-attr]",
            "sampler_d1337e.py:156: error: Incompatible types in assignment (expression has type \"None\", variable has type \"FlameGraphCollector | MemoryCollector | ObjectCollector\")  [assignment]",
            "sampler_d1337e.py:165: error: \"SignalSampler\" has no attribute \"_timer_callback\"  [attr-defined]",
            "sampler_d1337e.py:170: error: Item \"FlameGraphCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"collect\"  [union-attr]",
            "sampler_d1337e.py:170: error: Item \"MemoryCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"collect\"  [union-attr]",
            "sampler_d1337e.py:170: error: Item \"ObjectCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"collect\"  [union-attr]",
            "sampler_d1337e.py:178: error: Item \"FlameGraphCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"stop\"  [union-attr]",
            "sampler_d1337e.py:178: error: Item \"MemoryCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"stop\"  [union-attr]",
            "sampler_d1337e.py:178: error: Item \"ObjectCollector\" of \"FlameGraphCollector | MemoryCollector | ObjectCollector\" has no attribute \"stop\"  [union-attr]",
            "Found 23 errors in 1 file (checked 1 source file)"
        ]
    },
    "gallery_2bb1c1.py": {
        "stats": {
            "total_parameters": 32,
            "parameters_with_annotations": 32
        },
        "error_count": 5,
        "isCompiled": false,
        "errors": [
            "gallery_2bb1c1.py:23: error: Incompatible types in assignment (expression has type \"partial[CompletedProcess[str]]\", variable has type overloaded function)  [assignment]",
            "gallery_2bb1c1.py:26: error: Name \"NamedTuple\" is not defined  [name-defined]",
            "gallery_2bb1c1.py:145: error: Argument 1 to \"func_lgj92zbn\" has incompatible type \"Path | None\"; expected \"Path\"  [arg-type]",
            "gallery_2bb1c1.py:150: error: Incompatible return value type (got \"tuple[Path | None, ...]\", expected \"tuple[Path, ...]\")  [return-value]",
            "gallery_2bb1c1.py:171: error: Argument 1 to \"run\" has incompatible type \"list[object]\"; expected \"str | bytes | PathLike[str] | PathLike[bytes] | Sequence[str | bytes | PathLike[str] | PathLike[bytes]]\"  [arg-type]",
            "Found 5 errors in 1 file (checked 1 source file)"
        ]
    },
    "xml_da8497.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "xml_da8497.py:101: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "user_groups_e1e474.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "user_groups_e1e474.py:295: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_categorical_e04b8e.py": {
        "stats": {
            "total_parameters": 33,
            "parameters_with_annotations": 22
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "staticfiles_164434.py": {
        "stats": {
            "total_parameters": 18,
            "parameters_with_annotations": 11
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "warnings_2ab542.py": {
        "stats": {
            "total_parameters": 13,
            "parameters_with_annotations": 6
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "binary_sensor_950ee8.py": {
        "stats": {
            "total_parameters": 38,
            "parameters_with_annotations": 20
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "_robot_tester_77d42f.py": {
        "stats": {
            "total_parameters": 32,
            "parameters_with_annotations": 26
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "base_tests_a1e90e.py": {
        "stats": {
            "total_parameters": 92,
            "parameters_with_annotations": 72
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "base_tests_a1e90e.py:87: error: \"type[T]\" has no attribute \"id\"  [attr-defined]",
            "base_tests_a1e90e.py:203: error: Name \"func_qs4bu81t\" is not defined  [name-defined]",
            "base_tests_a1e90e.py:327: error: Name \"mock_get_dialect\" is not defined  [name-defined]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "conftest_7752c7.py": {
        "stats": {
            "total_parameters": 13,
            "parameters_with_annotations": 8
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "string__8c20b1.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "string__8c20b1.py:394: error: expected an indented block after function definition on line 393  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "excel_26f18f.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "excel_26f18f.py:61: error: closing parenthesis ')' does not match opening parenthesis '[' on line 59  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "cache_helpers_e012c1.py": {
        "stats": {
            "total_parameters": 16,
            "parameters_with_annotations": 14
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "cache_helpers_e012c1.py:22: error: Name \"get_active_realm_ids\" is not defined  [name-defined]",
            "cache_helpers_e012c1.py:32: error: Name \"get_active_realm_ids\" is not defined  [name-defined]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "conftest_81d476.py": {
        "stats": {
            "total_parameters": 19,
            "parameters_with_annotations": 19
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "dataset_reader_test_19a9b5.py": {
        "stats": {
            "total_parameters": 24,
            "parameters_with_annotations": 13
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "upnp_cf635d.py": {
        "stats": {
            "total_parameters": 24,
            "parameters_with_annotations": 14
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "upnp_cf635d.py:72: error: \"UPNPResponderProtocol\" has no attribute \"_prepare_response\"  [attr-defined]",
            "upnp_cf635d.py:74: error: \"UPNPResponderProtocol\" has no attribute \"_prepare_response\"  [attr-defined]",
            "upnp_cf635d.py:90: error: \"UPNPResponderProtocol\" has no attribute \"_handle_request\"  [attr-defined]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "notify_1817bd.py": {
        "stats": {
            "total_parameters": 43,
            "parameters_with_annotations": 33
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "switch_d3c2da.py": {
        "stats": {
            "total_parameters": 33,
            "parameters_with_annotations": 17
        },
        "error_count": 10,
        "isCompiled": false,
        "errors": [
            "switch_d3c2da.py:82: error: Name \"FritzBoxWifiSwitch\" is not defined  [name-defined]",
            "switch_d3c2da.py:97: error: Name \"FritzBoxWifiSwitch\" is not defined  [name-defined]",
            "switch_d3c2da.py:116: error: Name \"FritzBoxWifiSwitch\" is not defined  [name-defined]",
            "switch_d3c2da.py:264: error: TypedDict key must be a string literal; expected one of (\"NewInternalClient\", \"NewInternalPort\", \"NewExternalPort\", \"NewProtocol\", \"NewPortMappingDescription\", ...)  [literal-required]",
            "switch_d3c2da.py:269: error: Value of \"NewEnabled\" has incompatible type \"str\"; expected \"bool\"  [typeddict-item]",
            "switch_d3c2da.py:284: error: Signature of \"data\" incompatible with supertype \"FritzBoxBaseCoordinatorSwitch\"  [override]",
            "switch_d3c2da.py:284: note:      Superclass:",
            "switch_d3c2da.py:284: note:          dict[str, Any]",
            "switch_d3c2da.py:284: note:      Subclass:",
            "switch_d3c2da.py:284: note:          DeflectionInfo",
            "Found 6 errors in 1 file (checked 1 source file)"
        ]
    },
    "accessor_0c5289.py": {
        "stats": {
            "total_parameters": 42,
            "parameters_with_annotations": 34
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "accessor_0c5289.py:122: error: Incompatible types in assignment (expression has type \"Callable[..., Any]\", variable has type \"property\")  [assignment]",
            "accessor_0c5289.py:161: error: Incompatible return value type (got \"type[AccessorT@__init__]\", expected \"type[AccessorT@__get__] | AccessorT@__get__\")  [return-value]",
            "accessor_0c5289.py:162: error: Missing positional argument \"accessor\" in call to \"Accessor\"  [call-arg]",
            "accessor_0c5289.py:162: error: Incompatible return value type (got \"AccessorT@__init__\", expected \"type[AccessorT@__get__] | AccessorT@__get__\")  [return-value]",
            "Found 4 errors in 1 file (checked 1 source file)"
        ]
    },
    "camera_4798a7.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "camera_4798a7.py:81: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_sensor_062284.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_sensor_062284.py:268: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "base_7e78cf.py": {
        "stats": {
            "total_parameters": 37,
            "parameters_with_annotations": 18
        },
        "error_count": 13,
        "isCompiled": false,
        "errors": [
            "base_7e78cf.py:46: error: \"BasePackage\" has no attribute \"name\"  [attr-defined]",
            "base_7e78cf.py:58: error: \"PinnedPackage\" has no attribute \"get_version\"  [attr-defined]",
            "base_7e78cf.py:60: error: \"PinnedPackage\" has no attribute \"name\"  [attr-defined]",
            "base_7e78cf.py:61: error: \"PinnedPackage\" has no attribute \"name\"  [attr-defined]",
            "base_7e78cf.py:85: error: \"PinnedPackage\" has no attribute \"_fetch_metadata\"; maybe \"_cached_metadata\"?  [attr-defined]",
            "base_7e78cf.py:89: error: \"PinnedPackage\" has no attribute \"fetch_metadata\"  [attr-defined]",
            "base_7e78cf.py:93: error: \"PinnedPackage\" has no attribute \"get_project_name\"  [attr-defined]",
            "base_7e78cf.py:100: error: \"PinnedPackage\" has no attribute \"fetch_metadata\"  [attr-defined]",
            "base_7e78cf.py:101: error: \"PinnedPackage\" has no attribute \"package\"  [attr-defined]",
            "base_7e78cf.py:101: error: \"PinnedPackage\" has no attribute \"version\"  [attr-defined]",
            "base_7e78cf.py:102: error: Argument 1 to \"Path\" has incompatible type \"str | None\"; expected \"str | PathLike[str]\"  [arg-type]",
            "base_7e78cf.py:106: error: \"PinnedPackage\" has no attribute \"get_project_name\"  [attr-defined]",
            "base_7e78cf.py:107: error: \"PinnedPackage\" has no attribute \"download_and_untar\"  [attr-defined]",
            "Found 13 errors in 1 file (checked 1 source file)"
        ]
    },
    "jsondatahandler_96667e.py": {
        "stats": {
            "total_parameters": 27,
            "parameters_with_annotations": 20
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "channel_771f46.py": {
        "stats": {
            "total_parameters": 15,
            "parameters_with_annotations": 6
        },
        "error_count": 2,
        "isCompiled": false,
        "errors": [
            "channel_771f46.py:72: error: \"WebSocketChannel\" has no attribute \"_wrapped_ws\"  [attr-defined]",
            "channel_771f46.py:86: error: \"WebSocketChannel\" has no attribute \"_wrapped_ws\"  [attr-defined]",
            "Found 2 errors in 1 file (checked 1 source file)"
        ]
    },
    "number_9501ee.py": {
        "stats": {
            "total_parameters": 18,
            "parameters_with_annotations": 16
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "number_9501ee.py:137: error: Type variable \"number_9501ee.T\" is unbound  [valid-type]",
            "number_9501ee.py:137: note: (Hint: Use \"Generic[T]\" or \"Protocol[T]\" base class to bind \"T\" inside a class)",
            "number_9501ee.py:137: note: (Hint: Use \"T\" in function signature to bind \"T\" inside a function)",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "linegen_ea8858.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "linegen_ea8858.py:383: error: invalid syntax  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "forms_6e49d8.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "forms_6e49d8.py:370: error: unterminated string literal (detected at line 370)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "presence_ce7e57.py": {
        "stats": {
            "total_parameters": 26,
            "parameters_with_annotations": 26
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "realm_linkifiers_90aa4a.py": {
        "stats": {
            "total_parameters": 14,
            "parameters_with_annotations": 14
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "__init___344c2e.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "__init___344c2e.py:393: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "entity_9725b3.py": {
        "stats": {
            "total_parameters": 12,
            "parameters_with_annotations": 7
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "test_history_818171.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_history_818171.py:215: error: cannot assign to subscript here. Maybe you meant '==' instead of '='?  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "_parser_ad554d.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "_parser_ad554d.py:413: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "users_e2ac2d.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "users_e2ac2d.py:358: error: expected ':'  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "indexing_d02a25.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "indexing_d02a25.py:375: error: '[' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_mediatedtransfer_b63130.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_mediatedtransfer_b63130.py:309: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "dataset_reader_e7f129.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "dataset_reader_e7f129.py:103: error: unterminated triple-quoted string literal (detected at line 109)  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "media_player_d56fd8.py": {
        "stats": {
            "total_parameters": 34,
            "parameters_with_annotations": 16
        },
        "error_count": 6,
        "isCompiled": false,
        "errors": [
            "media_player_d56fd8.py:19: error: Need type annotation for \"DEFAULT_SOURCES\" (hint: \"DEFAULT_SOURCES: dict[<type>, <type>] = ...\")  [var-annotated]",
            "media_player_d56fd8.py:91: error: Module \"telnetlib\" does not explicitly export attribute \"socket\"  [attr-defined]",
            "media_player_d56fd8.py:104: error: Argument 3 to \"Telnet\" has incompatible type \"float | None\"; expected \"float\"  [arg-type]",
            "media_player_d56fd8.py:111: error: Module \"telnetlib\" does not explicitly export attribute \"socket\"  [attr-defined]",
            "media_player_d56fd8.py:117: error: Argument 3 to \"Telnet\" has incompatible type \"float | None\"; expected \"float\"  [arg-type]",
            "media_player_d56fd8.py:142: error: Incompatible types in assignment (expression has type \"str | None\", variable has type \"str\")  [assignment]",
            "Found 6 errors in 1 file (checked 1 source file)"
        ]
    },
    "conftest_ee8a90.py": {
        "stats": {
            "total_parameters": 13,
            "parameters_with_annotations": 13
        },
        "error_count": 3,
        "isCompiled": false,
        "errors": [
            "conftest_ee8a90.py:56: error: Name \"json_loads\" is not defined  [name-defined]",
            "conftest_ee8a90.py:62: error: Name \"json_loads\" is not defined  [name-defined]",
            "conftest_ee8a90.py:74: error: Name \"json_loads\" is not defined  [name-defined]",
            "Found 3 errors in 1 file (checked 1 source file)"
        ]
    },
    "light_1f4c8c.py": {
        "stats": {
            "total_parameters": 13,
            "parameters_with_annotations": 9
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "conftest_721c82.py": {
        "stats": {
            "total_parameters": 22,
            "parameters_with_annotations": 17
        },
        "error_count": 8,
        "isCompiled": false,
        "errors": [
            "conftest_721c82.py:23: error: \"BaseParser\" has no attribute \"update_kwargs\"  [attr-defined]",
            "conftest_721c82.py:24: error: Name \"func_dxeiofh4\" is not defined  [name-defined]",
            "conftest_721c82.py:29: error: \"BaseParser\" has no attribute \"update_kwargs\"  [attr-defined]",
            "conftest_721c82.py:33: error: Name \"func_dxeiofh4\" is not defined  [name-defined]",
            "conftest_721c82.py:36: error: \"BaseParser\" has no attribute \"update_kwargs\"  [attr-defined]",
            "conftest_721c82.py:37: error: Name \"func_kfqkzbey\" is not defined  [name-defined]",
            "conftest_721c82.py:41: error: \"BaseParser\" has no attribute \"update_kwargs\"  [attr-defined]",
            "conftest_721c82.py:44: error: Name \"func_kfqkzbey\" is not defined  [name-defined]",
            "Found 8 errors in 1 file (checked 1 source file)"
        ]
    },
    "pytables_a9636c.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "pytables_a9636c.py:434: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "message_send_b7048c.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "message_send_b7048c.py:298: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "test_shrinker_1f54e0.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "test_shrinker_1f54e0.py:367: error: expected ':'  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "stats_logger_411bed.py": {
        "stats": {
            "total_parameters": 39,
            "parameters_with_annotations": 24
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "websocket_api_f30f86.py": {
        "stats": {
            "total_parameters": 18,
            "parameters_with_annotations": 18
        },
        "error_count": 13,
        "isCompiled": false,
        "errors": [
            "websocket_api_f30f86.py:36: error: Incompatible types in assignment (expression has type \"None\", variable has type \"list[Any]\")  [assignment]",
            "websocket_api_f30f86.py:37: error: Incompatible types in assignment (expression has type \"None\", variable has type \"Queue[Any]\")  [assignment]",
            "websocket_api_f30f86.py:42: error: Name \"ws_get_events\" is not defined  [name-defined]",
            "websocket_api_f30f86.py:43: error: Name \"ws_event_stream\" is not defined  [name-defined]",
            "websocket_api_f30f86.py:50: error: Name \"_generate_stream_message\" is not defined  [name-defined]",
            "websocket_api_f30f86.py:74: error: Name \"_async_get_ws_stream_events\" is not defined  [name-defined]",
            "websocket_api_f30f86.py:84: error: Name \"_async_get_ws_stream_events\" is not defined  [name-defined]",
            "websocket_api_f30f86.py:93: error: Name \"_async_get_ws_stream_events\" is not defined  [name-defined]",
            "websocket_api_f30f86.py:112: error: Name \"_ws_stream_get_events\" is not defined  [name-defined]",
            "websocket_api_f30f86.py:233: error: Name \"_unsub\" is not defined  [name-defined]",
            "websocket_api_f30f86.py:249: error: Name \"_queue_or_cancel\" is not defined  [name-defined]",
            "websocket_api_f30f86.py:252: error: Name \"_unsub\" is not defined  [name-defined]",
            "websocket_api_f30f86.py:332: error: Name \"_ws_formatted_get_events\" is not defined  [name-defined]",
            "Found 13 errors in 1 file (checked 1 source file)"
        ]
    },
    "states_ff542b.py": {
        "stats": {
            "total_parameters": 59,
            "parameters_with_annotations": 36
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "states_ff542b.py:166: error: A function returning TypeVar should receive at least one argument containing the same TypeVar  [type-var]",
            "states_ff542b.py:195: error: Item \"None\" of \"StateType | None\" has no attribute \"value\"  [union-attr]",
            "states_ff542b.py:207: error: Item \"None\" of \"StateType | None\" has no attribute \"value\"  [union-attr]",
            "states_ff542b.py:208: error: Item \"None\" of \"StateType | None\" has no attribute \"value\"  [union-attr]",
            "Found 4 errors in 1 file (checked 1 source file)"
        ]
    },
    "rouge_test_960688.py": {
        "stats": {
            "total_parameters": 14,
            "parameters_with_annotations": 9
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "rouge_test_960688.py:83: error: Name \"global_distributed_rouge\" is not defined  [name-defined]",
            "Found 1 error in 1 file (checked 1 source file)"
        ]
    },
    "unit_system_a3b7c4.py": {
        "stats": {
            "total_parameters": 31,
            "parameters_with_annotations": 21
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "s3_e58a82.py": {
        "stats": {
            "total_parameters": 0,
            "parameters_with_annotations": 0
        },
        "error_count": 1,
        "isCompiled": false,
        "errors": [
            "s3_e58a82.py:293: error: '(' was never closed  [syntax]",
            "Found 1 error in 1 file (errors prevented further checking)"
        ]
    },
    "metrics_195f9f.py": {
        "stats": {
            "total_parameters": 14,
            "parameters_with_annotations": 14
        },
        "error_count": 0,
        "isCompiled": true,
        "errors": []
    },
    "secret_registry_13acaf.py": {
        "stats": {
            "total_parameters": 19,
            "parameters_with_annotations": 13
        },
        "error_count": 4,
        "isCompiled": false,
        "errors": [
            "secret_registry_13acaf.py:45: error: \"SecretRegistry\" has no attribute \"register_secret_batch\"  [attr-defined]",
            "secret_registry_13acaf.py:66: error: \"SecretRegistry\" has no attribute \"is_secret_registered\"  [attr-defined]",
            "secret_registry_13acaf.py:74: error: \"SecretRegistry\" has no attribute \"_register_secret_batch\"  [attr-defined]",
            "secret_registry_13acaf.py:159: error: \"SecretRegistry\" has no attribute \"get_secret_registration_block_by_secrethash\"  [attr-defined]",
            "Found 4 errors in 1 file (checked 1 source file)"
        ]
    }
}