{
    "alert_tests.py_deepseek_d23b3a38.py": "temp_file.py:95: error: \"object\" has no attribute \"__enter__\"  [attr-defined]\ntemp_file.py:95: error: \"object\" has no attribute \"__exit__\"  [attr-defined]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "test_usecols_basic.py_deepseek_c777d637.py": "temp_file.py:112: error: Unexpected keyword argument \"reason\" for \"skip\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\_pytest\\outcomes.py:119: note: \"skip\" defined here\ntemp_file.py:456: error: Unexpected keyword argument \"reason\" for \"skip\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\_pytest\\outcomes.py:119: note: \"skip\" defined here\ntemp_file.py:478: error: Unexpected keyword argument \"reason\" for \"skip\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\_pytest\\outcomes.py:119: note: \"skip\" defined here\nFound 3 errors in 1 file (checked 1 source file)\n",
    "sensor.py_deepseek_38c42a0d.py": "temp_file.py:31: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "validator.py_deepseek_af420d1c.py": "temp_file.py:109: error: Incompatible return value type (got \"Tuple[zip[Tuple[Any, Any]], List[Any]]\", expected \"Tuple[List[Tuple[Any, Any]], List[Any]]\")  [return-value]\nFound 1 error in 1 file (checked 1 source file)\n",
    "testclient.py_deepseek_b53c0624.py": "temp_file.py:98: error: Missing return statement  [return]\nFound 1 error in 1 file (checked 1 source file)\n",
    "test_string.py_deepseek_7c5cc6f9.py": "temp_file.py:39: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:118: error: Unexpected keyword argument \"reason\" for \"skip\"  [call-arg]\ntemp_file.py:208: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:221: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\nD:\\python3.8\\lib\\site-packages\\_pytest\\outcomes.py:119: note: \"skip\" defined here\ntemp_file.py:127: error: Unexpected keyword argument \"reason\" for \"skip\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\_pytest\\outcomes.py:119: note: \"skip\" defined here\ntemp_file.py:132: error: Unexpected keyword argument \"reason\" for \"skip\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\_pytest\\outcomes.py:119: note: \"skip\" defined here\ntemp_file.py:209: error: No overload variant of \"next\" matches argument type \"List[Union[Any, Any]]\"  [call-overload]\ntemp_file.py:209: note: Possible overload variants:\ntemp_file.py:209: note:     def [_T] next(SupportsNext[_T], /) -> _T\ntemp_file.py:209: note:     def [_T, _VT] next(SupportsNext[_T], _VT, /) -> Union[_T, _VT]\ntemp_file.py:243: error: Unexpected keyword argument \"reason\" for \"skip\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\_pytest\\outcomes.py:119: note: \"skip\" defined here\nFound 8 errors in 1 file (checked 1 source file)\n",
    "generic_test_builders.py_deepseek_dbe9f303.py": "temp_file.py:181: error: Incompatible types in assignment (expression has type \"List[Tuple[str, Any]]\", variable has type \"Dict[str, Any]\")  [assignment]\ntemp_file.py:184: error: Invalid index type \"int\" for \"Dict[str, Any]\"; expected type \"str\"  [index]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "sensor.py_deepseek_ec1ed581.py": "temp_file.py:14: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "test_conversion.py_deepseek_43da3ab9.py": "temp_file.py:131: error: Incompatible types in assignment (expression has type \"Tuple[type]\", variable has type \"type\")  [assignment]\ntemp_file.py:132: error: Unsupported right operand type for in (\"type\")  [operator]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "instrumentations_examples.py_deepseek_4572d1a8.py": "temp_file.py:57: error: Module has no attribute \"SIGALRM\"  [attr-defined]\ntemp_file.py:58: error: Module has no attribute \"alarm\"  [attr-defined]\ntemp_file.py:78: error: Module has no attribute \"alarm\"  [attr-defined]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "worker.py_deepseek_223fa64d.py": "temp_file.py:45: error: Name \"jsHandleFactory\" is already defined in local scope before nonlocal declaration  [misc]\nFound 1 error in 1 file (checked 1 source file)\n",
    "pretrained_transformer_embedder.py_deepseek_193bb568.py": "temp_file.py:135: error: Argument 2 to \"_fold_long_sequences\" of \"PretrainedTransformerEmbedder\" has incompatible type \"Optional[BoolTensor]\"; expected \"BoolTensor\"  [arg-type]\ntemp_file.py:154: error: Argument 2 to \"_unfold_long_sequences\" of \"PretrainedTransformerEmbedder\" has incompatible type \"Optional[BoolTensor]\"; expected \"BoolTensor\"  [arg-type]\ntemp_file.py:172: error: Argument 2 to \"reshape\" of \"TensorBase\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]\ntemp_file.py:174: error: Incompatible return value type (got \"Tuple[Tensor, Tensor, Optional[Tensor]]\", expected \"Tuple[LongTensor, BoolTensor, Optional[LongTensor]]\")  [return-value]\ntemp_file.py:206: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:206: error: Argument 3 to \"reshape\" of \"TensorBase\" has incompatible type \"Optional[int]\"; expected \"int\"  [arg-type]\ntemp_file.py:207: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:210: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:218: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:223: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:225: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\nFound 11 errors in 1 file (checked 1 source file)\n",
    "conditional_random_field.py_deepseek_b0709573.py": "temp_file.py:236: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"BoolTensor\")  [assignment]\ntemp_file.py:298: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"BoolTensor\")  [assignment]\ntemp_file.py:305: error: Incompatible types in assignment (expression has type \"float\", variable has type \"Tensor\")  [assignment]\ntemp_file.py:331: error: Incompatible types in assignment (expression has type \"float\", variable has type \"Tensor\")  [assignment]\ntemp_file.py:357: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[BoolTensor]\")  [assignment]\ntemp_file.py:360: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[BoolTensor]\")  [assignment]\ntemp_file.py:362: error: Argument 3 to \"_input_likelihood\" of \"ConditionalRandomField\" has incompatible type \"Optional[BoolTensor]\"; expected \"BoolTensor\"  [arg-type]\ntemp_file.py:363: error: Argument 4 to \"_joint_likelihood\" of \"ConditionalRandomField\" has incompatible type \"Optional[BoolTensor]\"; expected \"BoolTensor\"  [arg-type]\ntemp_file.py:382: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[BoolTensor]\")  [assignment]\ntemp_file.py:393: error: Item \"None\" of \"Optional[BoolTensor]\" has no attribute \"data\"  [union-attr]\ntemp_file.py:393: error: Incompatible types in assignment (expression has type \"Union[Tensor, Any]\", variable has type \"Optional[BoolTensor]\")  [assignment]\ntemp_file.py:429: error: Argument 2 to \"zip\" has incompatible type \"Optional[BoolTensor]\"; expected \"Iterable[Any]\"  [arg-type]\nFound 12 errors in 1 file (checked 1 source file)\n",
    "regions.py_deepseek_08792844.py": "temp_file.py:119: error: Signature of \"construct_endpoint\" incompatible with supertype \"BaseEndpointResolver\"  [override]\ntemp_file.py:119: note:      Superclass:\ntemp_file.py:119: note:          def construct_endpoint(self, service_name: str, region_name: Optional[str] = ...) -> Dict[str, Any]\ntemp_file.py:119: note:      Subclass:\ntemp_file.py:119: note:          def construct_endpoint(self, service_name: str, region_name: Optional[str] = ..., partition_name: Optional[str] = ...) -> Optional[Dict[str, Any]]\ntemp_file.py:154: error: Argument 4 to \"_resolve\" of \"EndpointResolver\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\ntemp_file.py:156: error: Argument 2 to \"_region_match\" of \"EndpointResolver\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\ntemp_file.py:168: error: Argument 4 to \"_resolve\" of \"EndpointResolver\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "_models.py_deepseek_5798ddfd.py": "temp_file.py:193: error: Signature of \"get\" incompatible with supertype \"Mapping\"  [override]\ntemp_file.py:193: note:      Superclass:\ntemp_file.py:193: note:          @overload\ntemp_file.py:193: note:          def get(self, str, /) -> Optional[str]\ntemp_file.py:193: note:          @overload\ntemp_file.py:193: note:          def [_T] get(self, str, /, default: Union[str, _T]) -> Union[str, _T]\ntemp_file.py:193: note:      Subclass:\ntemp_file.py:193: note:          def get(self, key: str, default: Optional[Any] = ...) -> Optional[Any]\ntemp_file.py:216: error: Signature of \"update\" incompatible with supertype \"MutableMapping\"  [override]\ntemp_file.py:216: note:      Superclass:\ntemp_file.py:216: note:          @overload\ntemp_file.py:216: note:          def update(self, SupportsKeysAndGetItem[str, str], /, **kwargs: str) -> None\ntemp_file.py:216: note:          @overload\ntemp_file.py:216: note:          def update(self, Iterable[Tuple[str, str]], /, **kwargs: str) -> None\ntemp_file.py:216: note:          @overload\ntemp_file.py:216: note:          def update(self, **kwargs: str) -> None\ntemp_file.py:216: note:      Subclass:\ntemp_file.py:216: note:          def update(self, headers: Optional[Any] = ...) -> None\ntemp_file.py:957: error: Signature of \"update\" incompatible with supertype \"MutableMapping\"  [override]\ntemp_file.py:957: note:      Superclass:\ntemp_file.py:957: note:          @overload\ntemp_file.py:957: note:          def update(self, SupportsKeysAndGetItem[str, str], /, **kwargs: str) -> None\ntemp_file.py:957: note:          @overload\ntemp_file.py:957: note:          def update(self, Iterable[Tuple[str, str]], /, **kwargs: str) -> None\ntemp_file.py:957: note:          @overload\ntemp_file.py:957: note:          def update(self, **kwargs: str) -> None\ntemp_file.py:957: note:      Subclass:\ntemp_file.py:957: note:          def update(self, cookies: Optional[Any] = ...) -> None\nFound 3 errors in 1 file (checked 1 source file)\n",
    "decoder.py_deepseek_b90fbe5f.py": "temp_file.py:24: error: No parent module -- cannot perform relative import\ntemp_file.py:25: error: No parent module -- cannot perform relative import\ntemp_file.py:26: error: No parent module -- cannot perform relative import\nFound 3 errors in 1 file (errors prevented further checking)\n",
    "cache.py_deepseek_397aeb92.py": "temp_file.py:55: error: Missing return statement  [return]\ntemp_file.py:76: error: Argument 1 to \"getmtime\" has incompatible type \"Optional[Path]\"; expected \"Union[int, Union[str, bytes, PathLike[str], PathLike[bytes]]]\"  [arg-type]\ntemp_file.py:79: error: Argument 1 to \"open\" has incompatible type \"Optional[Path]\"; expected \"Union[int, Union[str, bytes, PathLike[str], PathLike[bytes]]]\"  [arg-type]\ntemp_file.py:113: error: Argument 2 to \"_set_cache_item\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\ntemp_file.py:178: error: No return value expected  [return-value]\ntemp_file.py:186: error: Incompatible return value type (got \"str\", expected \"Path\")  [return-value]\nFound 6 errors in 1 file (checked 1 source file)\n",
    "training.py_deepseek_79729440.py": "temp_file.py:40: error: No parent module -- cannot perform relative import\ntemp_file.py:41: error: No parent module -- cannot perform relative import\ntemp_file.py:42: error: No parent module -- cannot perform relative import\ntemp_file.py:43: error: No parent module -- cannot perform relative import\ntemp_file.py:44: error: No parent module -- cannot perform relative import\ntemp_file.py:45: error: No parent module -- cannot perform relative import\ntemp_file.py:46: error: No parent module -- cannot perform relative import\ntemp_file.py:47: error: No parent module -- cannot perform relative import\ntemp_file.py:48: error: No parent module -- cannot perform relative import\ntemp_file.py:49: error: No parent module -- cannot perform relative import\nFound 10 errors in 1 file (errors prevented further checking)\n",
    "tools.py_deepseek_d6227bc0.py": "temp_file.py:260: error: Item \"Sequence[Any]\" of \"Union[Any, Sequence[Any]]\" has no attribute \"get_figure\"  [union-attr]\nFound 1 error in 1 file (checked 1 source file)\n",
    "blocks.py_deepseek_5859508d.py": "temp_file.py:23: error: Relative import climbs too many namespaces  [misc]\ntemp_file.py:24: error: Relative import climbs too many namespaces  [misc]\ntemp_file.py:58: error: Incompatible default for argument \"timestamp\" (default has type \"None\", argument has type \"int\")  [assignment]\ntemp_file.py:58: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True\ntemp_file.py:58: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase\nFound 3 errors in 1 file (checked 1 source file)\n",
    "utils.py_deepseek_04b66f49.py": "temp_file.py:116: error: \"Type[ReusedSQLTestCase]\" has no attribute \"spark\"  [attr-defined]\ntemp_file.py:117: error: \"Type[ReusedSQLTestCase]\" has no attribute \"spark\"  [attr-defined]\ntemp_file.py:389: error: Argument 1 to \"simplefilter\" has incompatible type \"str\"; expected \"Literal['default', 'error', 'ignore', 'always', 'module', 'once']\"  [arg-type]\ntemp_file.py:394: error: Argument 2 to \"issubclass\" has incompatible type \"Union[Type[Warning], Literal[True]]\"; expected \"_ClassInfo\"  [arg-type]\ntemp_file.py:419: error: Incompatible types in assignment (expression has type \"str\", variable has type \"Tuple[str, str, str]\")  [assignment]\ntemp_file.py:419: error: Item \"bool\" of \"Union[Type[Warning], Literal[True]]\" has no attribute \"__name__\"  [union-attr]\nFound 6 errors in 1 file (checked 1 source file)\n",
    "transformer_layer.py_deepseek_238a1cf9.py": "temp_file.py:50: error: Incompatible types in assignment (expression has type \"Optional[BoolTensor]\", variable has type \"BoolTensor\")  [assignment]\nFound 1 error in 1 file (checked 1 source file)\n",
    "featureflags.py_deepseek_7d9b2b1c.py": "temp_file.py:42: error: Item \"None\" of \"Optional[Any]\" has no attribute \"draw_integer\"  [union-attr]\ntemp_file.py:75: error: Name \"List\" is not defined  [name-defined]\ntemp_file.py:75: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import List\")\ntemp_file.py:76: error: Name \"List\" is not defined  [name-defined]\ntemp_file.py:76: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import List\")\ntemp_file.py:91: error: Argument \"at_least_one_of\" to \"FeatureFlags\" has incompatible type \"FrozenSet[str]\"; expected \"Tuple[str, ...]\"  [arg-type]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "misc.py_deepseek_3b346c4e.py": "temp_file.py:467: error: Incompatible return value type (got \"Union[List[str], str]\", expected \"str\")  [return-value]\nFound 1 error in 1 file (checked 1 source file)\n",
    "sensor.py_deepseek_9cbe391f.py": "temp_file.py:171: error: \"str\" has no attribute \"render\"  [attr-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "cover.py_deepseek_b6c0275f.py": "temp_file.py:104: error: Cannot determine type of \"_attr_unique_id\"  [has-type]\nFound 1 error in 1 file (checked 1 source file)\n",
    "melt.py_deepseek_713be946.py": "temp_file.py:28: error: List item 0 has incompatible type \"Union[Hashable, Any, List[Hashable]]\"; expected \"Hashable\"  [list-item]\ntemp_file.py:34: error: Argument 1 to \"list\" has incompatible type \"Union[Hashable, Any, List[Hashable]]\"; expected \"Iterable[Hashable]\"  [arg-type]\ntemp_file.py:95: error: Argument 1 to \"list\" has incompatible type \"Union[Hashable, List[Hashable]]\"; expected \"Iterable[Hashable]\"  [arg-type]\ntemp_file.py:96: error: Argument 1 to \"len\" has incompatible type \"Union[Hashable, List[Hashable]]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:98: error: Argument 1 to \"len\" has incompatible type \"Union[Hashable, List[Hashable]]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:104: error: List item 0 has incompatible type \"Union[Hashable, List[Hashable]]\"; expected \"Hashable\"  [list-item]\ntemp_file.py:120: error: No overload variant of \"__add__\" of \"list\" matches argument type \"Hashable\"  [operator]\ntemp_file.py:120: note: Possible overload variants:\ntemp_file.py:120: note:     def __add__(self, List[Hashable], /) -> List[Hashable]\ntemp_file.py:120: note:     def [_S] __add__(self, List[_S], /) -> List[Union[_S, Hashable]]\ntemp_file.py:120: note: Right operand is of type \"Union[Hashable, Any, List[Hashable]]\"\ntemp_file.py:130: error: Argument 1 to \"enumerate\" has incompatible type \"Union[Hashable, Any, List[Hashable]]\"; expected \"Iterable[Any]\"  [arg-type]\ntemp_file.py:209: error: List item 0 has incompatible type \"Union[str, List[str]]\"; expected \"str\"  [list-item]\ntemp_file.py:217: error: List item 0 has incompatible type \"Union[str, List[str]]\"; expected \"str\"  [list-item]\nFound 10 errors in 1 file (checked 1 source file)\n",
    "test_arithmetics.py_deepseek_1d2db0a9.py": "temp_file.py:14: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:20: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:143: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:182: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:371: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:544: error: \"str\" not callable  [operator]\ntemp_file.py:546: error: \"str\" not callable  [operator]\ntemp_file.py:551: error: \"str\" not callable  [operator]\ntemp_file.py:555: error: \"str\" not callable  [operator]\ntemp_file.py:559: error: \"str\" not callable  [operator]\ntemp_file.py:564: error: \"str\" not callable  [operator]\ntemp_file.py:565: error: \"str\" not callable  [operator]\nFound 12 errors in 1 file (checked 1 source file)\n",
    "test_api.py_deepseek_9fa83db7.py": "temp_file.py:379: error: \"List[Union[str, float]]\" has no attribute \"tolist\"  [attr-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "git.py_deepseek_08af83e3.py": "temp_file.py:47: error: Item \"None\" of \"Optional[Match[str]]\" has no attribute \"group\"  [union-attr]\ntemp_file.py:57: error: List item 1 has incompatible type \"Optional[str]\"; expected \"str\"  [list-item]\ntemp_file.py:77: error: Argument 1 to \"join\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\ntemp_file.py:149: error: No overload variant of \"match\" matches argument types \"str\", \"bytes\"  [call-overload]\ntemp_file.py:149: note: Possible overload variants:\ntemp_file.py:149: note:     def match(pattern: Union[str, Pattern[str]], string: str, flags: Union[int, RegexFlag] = ...) -> Optional[Match[str]]\ntemp_file.py:149: note:     def match(pattern: Union[bytes, Pattern[bytes]], string: Buffer, flags: Union[int, RegexFlag] = ...) -> Optional[Match[bytes]]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "categorical.py_deepseek_f99b3282.py": "temp_file.py:157: error: Incompatible default for argument \"ordered\" (default has type \"None\", argument has type \"bool\")  [assignment]\ntemp_file.py:157: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True\ntemp_file.py:157: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase\ntemp_file.py:161: error: Incompatible default for argument \"ordered\" (default has type \"None\", argument has type \"bool\")  [assignment]\ntemp_file.py:161: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True\ntemp_file.py:161: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase\nFound 2 errors in 1 file (checked 1 source file)\n",
    "conftest.py_deepseek_c0d9dac1.py": "temp_file.py:123: error: invalid syntax  [syntax]\nFound 1 error in 1 file (errors prevented further checking)\n",
    "monitor.py_deepseek_121c517b.py": "temp_file.py:353: error: Incompatible default for argument \"state\" (default has type \"None\", argument has type \"Dict[Any, Any]\")  [assignment]\ntemp_file.py:353: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True\ntemp_file.py:353: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase\nFound 1 error in 1 file (checked 1 source file)\n",
    "test_info.py_deepseek_0c6b742d.py": "temp_file.py:82: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:384: error: \"List[str]\" has no attribute \"values\"  [attr-defined]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "multi.py_deepseek_ac01e7fb.py": "temp_file.py:316: error: List comprehension has incompatible type List[Sequence[str]]; expected List[str]  [misc]\ntemp_file.py:383: error: Incompatible types in assignment (expression has type \"Tuple[str]\", variable has type \"Union[int, str, None]\")  [assignment]\ntemp_file.py:445: error: \"None\" not callable  [misc]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "expr.py_deepseek_e4a118ef.py": "temp_file.py:351: error: Argument 1 to \"disallow\" has incompatible type \"FrozenSet[str]\"; expected \"Set[str]\"  [arg-type]\ntemp_file.py:438: error: \"Compare\" has no attribute \"op\"; maybe \"ops\"?  [attr-defined]\ntemp_file.py:467: error: \"Compare\" has no attribute \"right\"  [attr-defined]\ntemp_file.py:528: error: Argument 2 to \"_maybe_eval\" of \"BaseExprVisitor\" has incompatible type \"List[str]\"; expected \"Tuple[str, ...]\"  [arg-type]\ntemp_file.py:546: error: Argument 1 to \"_maybe_transform_eq_ne\" of \"BaseExprVisitor\" has incompatible type \"BinOp\"; expected \"Compare\"  [arg-type]\ntemp_file.py:578: error: Incompatible types in assignment (expression has type \"Callable[[_ast.List, KwArg(Any)], Any]\", base class \"NodeVisitor\" defined the type as \"Callable[[_ast.Tuple], Any]\")  [assignment]\ntemp_file.py:752: error: Argument 1 to \"_maybe_transform_eq_ne\" of \"BaseExprVisitor\" has incompatible type \"BoolOp\"; expected \"Compare\"  [arg-type]\ntemp_file.py:753: error: Argument 2 to \"_maybe_evaluate_binop\" of \"BaseExprVisitor\" has incompatible type \"boolop\"; expected \"type\"  [arg-type]\ntemp_file.py:764: error: Argument 1 to \"disallow\" has incompatible type \"FrozenSet[str]\"; expected \"Set[str]\"  [arg-type]\ntemp_file.py:781: error: Argument 1 to \"disallow\" has incompatible type \"FrozenSet[str]\"; expected \"Set[str]\"  [arg-type]\nFound 10 errors in 1 file (checked 1 source file)\n",
    "show.py_deepseek_19112c41.py": "temp_file.py:33: error: Type cannot be declared in assignment to non-self attribute  [misc]\ntemp_file.py:71: error: \"type\" expects no type arguments, but 1 given  [type-arg]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "main.py_deepseek_3f8c7064.py": "temp_file.py:15: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "entropy_test.py_deepseek_6f9156a1.py": "temp_file.py:55: error: Incompatible types in assignment (expression has type \"List[Tensor]\", variable has type \"Tensor\")  [assignment]\ntemp_file.py:69: error: Incompatible types in assignment (expression has type \"List[Tensor]\", variable has type \"Tensor\")  [assignment]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "test_btanalysis.py_deepseek_5d81f97b.py": "temp_file.py:515: error: No overload variant of \"zip\" matches argument types \"List[float]\", \"List[datetime]\", \"bool\"  [call-overload]\ntemp_file.py:515: note: Possible overload variants:\ntemp_file.py:515: note:     def [_T_co, _T1] __new__(cls, Iterable[_T1], /) -> zip[Tuple[_T1]]\ntemp_file.py:515: note:     def [_T_co, _T1, _T2] __new__(cls, Iterable[_T1], Iterable[_T2], /) -> zip[Tuple[_T1, _T2]]\ntemp_file.py:515: note:     def [_T_co, _T1, _T2, _T3] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], /) -> zip[Tuple[_T1, _T2, _T3]]\ntemp_file.py:515: note:     def [_T_co, _T1, _T2, _T3, _T4] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], /) -> zip[Tuple[_T1, _T2, _T3, _T4]]\ntemp_file.py:515: note:     def [_T_co, _T1, _T2, _T3, _T4, _T5] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], Iterable[_T5], /) -> zip[Tuple[_T1, _T2, _T3, _T4, _T5]]\ntemp_file.py:515: note:     def [_T_co] __new__(cls, Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], /, *iterables: Iterable[Any]) -> zip[Tuple[Any, ...]]\ntemp_file.py:534: error: No overload variant of \"zip\" matches argument types \"List[float]\", \"List[datetime]\", \"bool\"  [call-overload]\ntemp_file.py:534: note: Possible overload variants:\ntemp_file.py:534: note:     def [_T_co, _T1] __new__(cls, Iterable[_T1], /) -> zip[Tuple[_T1]]\ntemp_file.py:534: note:     def [_T_co, _T1, _T2] __new__(cls, Iterable[_T1], Iterable[_T2], /) -> zip[Tuple[_T1, _T2]]\ntemp_file.py:534: note:     def [_T_co, _T1, _T2, _T3] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], /) -> zip[Tuple[_T1, _T2, _T3]]\ntemp_file.py:534: note:     def [_T_co, _T1, _T2, _T3, _T4] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], /) -> zip[Tuple[_T1, _T2, _T3, _T4]]\ntemp_file.py:534: note:     def [_T_co, _T1, _T2, _T3, _T4, _T5] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], Iterable[_T5], /) -> zip[Tuple[_T1, _T2, _T3, _T4, _T5]]\ntemp_file.py:534: note:     def [_T_co] __new__(cls, Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], /, *iterables: Iterable[Any]) -> zip[Tuple[Any, ...]]\ntemp_file.py:538: error: No overload variant of \"zip\" matches argument types \"List[float]\", \"List[datetime]\", \"bool\"  [call-overload]\ntemp_file.py:538: note: Possible overload variants:\ntemp_file.py:538: note:     def [_T_co, _T1] __new__(cls, Iterable[_T1], /) -> zip[Tuple[_T1]]\ntemp_file.py:538: note:     def [_T_co, _T1, _T2] __new__(cls, Iterable[_T1], Iterable[_T2], /) -> zip[Tuple[_T1, _T2]]\ntemp_file.py:538: note:     def [_T_co, _T1, _T2, _T3] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], /) -> zip[Tuple[_T1, _T2, _T3]]\ntemp_file.py:538: note:     def [_T_co, _T1, _T2, _T3, _T4] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], /) -> zip[Tuple[_T1, _T2, _T3, _T4]]\ntemp_file.py:538: note:     def [_T_co, _T1, _T2, _T3, _T4, _T5] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], Iterable[_T5], /) -> zip[Tuple[_T1, _T2, _T3, _T4, _T5]]\ntemp_file.py:538: note:     def [_T_co] __new__(cls, Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], /, *iterables: Iterable[Any]) -> zip[Tuple[Any, ...]]\ntemp_file.py:567: error: No overload variant of \"zip\" matches argument types \"List[float]\", \"List[datetime]\", \"bool\"  [call-overload]\ntemp_file.py:567: note: Possible overload variants:\ntemp_file.py:567: note:     def [_T_co, _T1] __new__(cls, Iterable[_T1], /) -> zip[Tuple[_T1]]\ntemp_file.py:567: note:     def [_T_co, _T1, _T2] __new__(cls, Iterable[_T1], Iterable[_T2], /) -> zip[Tuple[_T1, _T2]]\ntemp_file.py:567: note:     def [_T_co, _T1, _T2, _T3] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], /) -> zip[Tuple[_T1, _T2, _T3]]\ntemp_file.py:567: note:     def [_T_co, _T1, _T2, _T3, _T4] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], /) -> zip[Tuple[_T1, _T2, _T3, _T4]]\ntemp_file.py:567: note:     def [_T_co, _T1, _T2, _T3, _T4, _T5] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], Iterable[_T5], /) -> zip[Tuple[_T1, _T2, _T3, _T4, _T5]]\ntemp_file.py:567: note:     def [_T_co] __new__(cls, Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], /, *iterables: Iterable[Any]) -> zip[Tuple[Any, ...]]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "switch.py_deepseek_6d2bb2c2.py": "temp_file.py:22: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "datetimes.py_deepseek_289303b4.py": "temp_file.py:106: error: Name \"np\" is not defined  [name-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "event_schema.py_deepseek_05532cab.py": "temp_file.py:3: error: Name \"BaseModel\" is not defined  [name-defined]\ntemp_file.py:10: error: Name \"BaseEvent\" is not defined  [name-defined]\ntemp_file.py:10: error: Name \"Callable\" is not defined  [name-defined]\ntemp_file.py:10: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Callable\")\ntemp_file.py:34: error: Name \"PrettyPrinter\" is not defined  [name-defined]\ntemp_file.py:46: error: Name \"_check_delete_message\" is not defined  [name-defined]\ntemp_file.py:74: error: Name \"_check_has_zoom_token\" is not defined  [name-defined]\ntemp_file.py:84: error: Name \"_check_presence\" is not defined  [name-defined]\ntemp_file.py:99: error: Name \"_check_realm_bot_add\" is not defined  [name-defined]\ntemp_file.py:106: error: Name \"UserProfile\" is not defined  [name-defined]\ntemp_file.py:108: error: Name \"UserProfile\" is not defined  [name-defined]\ntemp_file.py:110: error: Name \"BotServicesOutgoing\" is not defined  [name-defined]\ntemp_file.py:111: error: Name \"UserProfile\" is not defined  [name-defined]\ntemp_file.py:113: error: Name \"BotServicesEmbedded\" is not defined  [name-defined]\ntemp_file.py:122: error: Name \"_check_realm_bot_update\" is not defined  [name-defined]\ntemp_file.py:128: error: Name \"_check_realm_emoji_update\" is not defined  [name-defined]\ntemp_file.py:141: error: Name \"_check_realm_export\" is not defined  [name-defined]\ntemp_file.py:156: error: Name \"_check_realm_update\" is not defined  [name-defined]\ntemp_file.py:171: error: Name \"Realm\" is not defined  [name-defined]\ntemp_file.py:179: error: Name \"_check_realm_default_update\" is not defined  [name-defined]\ntemp_file.py:183: error: Name \"RealmUserDefault\" is not defined  [name-defined]\ntemp_file.py:185: error: Name \"RealmUserDefault\" is not defined  [name-defined]\ntemp_file.py:192: error: Name \"_check_realm_update_dict\" is not defined  [name-defined]\ntemp_file.py:198: error: Name \"BaseModel\" is not defined  [name-defined]\ntemp_file.py:198: error: Name \"AllowMessageEditingData\" is not defined  [name-defined]\ntemp_file.py:200: error: Name \"MessageContentEditLimitSecondsData\" is not defined  [name-defined]\ntemp_file.py:202: error: Name \"AuthenticationData\" is not defined  [name-defined]\ntemp_file.py:204: error: Name \"Realm\" is not defined  [name-defined]\ntemp_file.py:206: error: Name \"GroupSettingUpdateData\" is not defined  [name-defined]\ntemp_file.py:208: error: Name \"PlanTypeData\" is not defined  [name-defined]\ntemp_file.py:213: error: Name \"IconData\" is not defined  [name-defined]\ntemp_file.py:215: error: Name \"LogoData\" is not defined  [name-defined]\ntemp_file.py:217: error: Name \"NightLogoData\" is not defined  [name-defined]\ntemp_file.py:221: error: Name \"cast\" is not defined  [name-defined]\ntemp_file.py:221: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import cast\")\ntemp_file.py:228: error: Name \"_check_realm_user_update\" is not defined  [name-defined]\ntemp_file.py:230: error: Name \"PERSON_TYPES\" is not defined  [name-defined]\ntemp_file.py:231: error: Name \"cast\" is not defined  [name-defined]\ntemp_file.py:231: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import cast\")\ntemp_file.py:237: error: Name \"_check_stream_update\" is not defined  [name-defined]\ntemp_file.py:267: error: Name \"Stream\" is not defined  [name-defined]\ntemp_file.py:268: error: Name \"Stream\" is not defined  [name-defined]\ntemp_file.py:270: error: Argument 2 to \"isinstance\" has incompatible type \"object\"; expected \"_ClassInfo\"  [arg-type]\ntemp_file.py:270: error: Name \"AnonymousSettingGroupDict\" is not defined  [name-defined]\ntemp_file.py:286: error: Name \"_check_subscription_update\" is not defined  [name-defined]\ntemp_file.py:294: error: Name \"_check_update_display_settings\" is not defined  [name-defined]\ntemp_file.py:302: error: Name \"UserProfile\" is not defined  [name-defined]\ntemp_file.py:314: error: Name \"_check_user_settings_update\" is not defined  [name-defined]\ntemp_file.py:322: error: Name \"UserProfile\" is not defined  [name-defined]\ntemp_file.py:335: error: Name \"_check_update_global_notifications\" is not defined  [name-defined]\ntemp_file.py:341: error: Name \"UserProfile\" is not defined  [name-defined]\ntemp_file.py:353: error: Name \"_check_update_message\" is not defined  [name-defined]\ntemp_file.py:385: error: Name \"ORIG_TOPIC\" is not defined  [name-defined]\ntemp_file.py:386: error: Name \"TOPIC_NAME\" is not defined  [name-defined]\ntemp_file.py:393: error: Name \"ORIG_TOPIC\" is not defined  [name-defined]\ntemp_file.py:410: error: Name \"_check_user_group_update\" is not defined  [name-defined]\ntemp_file.py:417: error: Name \"_check_user_status\" is not defined  [name-defined]\nFound 54 errors in 1 file (checked 1 source file)\n",
    "common.py_deepseek_94644383.py": "temp_file.py:196: error: Incompatible types in assignment (expression has type \"str\", variable has type \"List[str]\")  [assignment]\ntemp_file.py:208: error: \"List[str]\" has no attribute \"split\"  [attr-defined]\ntemp_file.py:216: error: Incompatible types in assignment (expression has type \"str\", variable has type \"List[str]\")  [assignment]\ntemp_file.py:228: error: \"List[str]\" has no attribute \"split\"  [attr-defined]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "embedding.py_deepseek_64e6a5c5.py": "temp_file.py:107: error: Incompatible types in assignment (expression has type \"None\", variable has type \"Linear\")  [assignment]\ntemp_file.py:189: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"FloatTensor\")  [assignment]\ntemp_file.py:264: error: Incompatible return value type (got \"Tensor\", expected \"FloatTensor\")  [return-value]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "test_strategy_state.py_deepseek_f335305e.py": "temp_file.py:105: error: Function \"temp_file.HypothesisSpec.float\" is not valid as a type  [valid-type]\ntemp_file.py:105: note: Perhaps you need \"Callable[...]\" or a callback protocol?\ntemp_file.py:109: error: Function \"temp_file.HypothesisSpec.float\" is not valid as a type  [valid-type]\ntemp_file.py:109: note: Perhaps you need \"Callable[...]\" or a callback protocol?\ntemp_file.py:112: error: Unsupported left operand type for <= (float?)  [operator]\ntemp_file.py:125: error: Function \"temp_file.HypothesisSpec.float\" is not valid as a type  [valid-type]\ntemp_file.py:125: note: Perhaps you need \"Callable[...]\" or a callback protocol?\nFound 4 errors in 1 file (checked 1 source file)\n",
    "withdrawals.py_deepseek_68b4d798.py": "temp_file.py:185: error: Return value expected  [return-value]\ntemp_file.py:207: error: Argument 4 to \"verify_post_state\" has incompatible type \"Optional[List[int]]\"; expected \"List[int]\"  [arg-type]\ntemp_file.py:207: error: Argument 5 to \"verify_post_state\" has incompatible type \"Optional[List[int]]\"; expected \"List[int]\"  [arg-type]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "test_dtypes_basic.py_deepseek_3cac3357.py": "temp_file.py:600: error: List item 0 has incompatible type \"str\"; expected \"int\"  [list-item]\ntemp_file.py:600: error: List item 1 has incompatible type \"str\"; expected \"int\"  [list-item]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "value.py_deepseek_6a3b30ed.py": "temp_file.py:121: error: The return type of a generator function should be \"Generator\" or one of its supertypes  [misc]\ntemp_file.py:396: error: Incompatible return value type (got \"Literal[_ParameterKind.POSITIONAL_ONLY]\", expected \"Parameter\")  [return-value]\ntemp_file.py:451: error: Unexpected keyword argument \"safe\"  [call-arg]\ntemp_file.py:566: error: Item \"None\" of \"Optional[Match[str]]\" has no attribute \"group\"  [union-attr]\ntemp_file.py:583: error: \"None\" has no attribute \"as_context\"  [attr-defined]\ntemp_file.py:601: error: \"None\" has no attribute \"as_context\"  [attr-defined]\nFound 6 errors in 1 file (checked 1 source file)\n",
    "helpers.py_deepseek_d76a9f4a.py": "temp_file.py:98: error: No overload variant of \"zip\" matches argument types \"Tuple[Any, ...]\", \"Tuple[Any, ...]\", \"bool\"  [call-overload]\ntemp_file.py:98: note: Possible overload variants:\ntemp_file.py:98: note:     def [_T_co, _T1] __new__(cls, Iterable[_T1], /) -> zip[Tuple[_T1]]\ntemp_file.py:98: note:     def [_T_co, _T1, _T2] __new__(cls, Iterable[_T1], Iterable[_T2], /) -> zip[Tuple[_T1, _T2]]\ntemp_file.py:98: note:     def [_T_co, _T1, _T2, _T3] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], /) -> zip[Tuple[_T1, _T2, _T3]]\ntemp_file.py:98: note:     def [_T_co, _T1, _T2, _T3, _T4] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], /) -> zip[Tuple[_T1, _T2, _T3, _T4]]\ntemp_file.py:98: note:     def [_T_co, _T1, _T2, _T3, _T4, _T5] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], Iterable[_T5], /) -> zip[Tuple[_T1, _T2, _T3, _T4, _T5]]\ntemp_file.py:98: note:     def [_T_co] __new__(cls, Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], /, *iterables: Iterable[Any]) -> zip[Tuple[Any, ...]]\nFound 1 error in 1 file (checked 1 source file)\n",
    "manifest.py_deepseek_c8979c4a.py": "temp_file.py:97: error: Name \"RefArgs\" is not defined  [name-defined]\ntemp_file.py:284: error: Name \"RefArgs\" is not defined  [name-defined]\ntemp_file.py:323: error: Name \"RefArgs\" is not defined  [name-defined]\ntemp_file.py:412: error: Name \"RefArgs\" is not defined  [name-defined]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "message_cache.py_deepseek_ef44c5a4.py": "temp_file.py:104: error: Incompatible return value type (got \"Optional[str]\", expected \"str\")  [return-value]\nFound 1 error in 1 file (checked 1 source file)\n",
    "fork_transition.py_deepseek_de86aa91.py": "temp_file.py:365: error: Argument 5 to \"_transition_until_active\" has incompatible type \"Optional[Any]\"; expected \"int\"  [arg-type]\ntemp_file.py:375: error: Argument \"ignoring_proposers\" to \"transition_to_next_epoch_and_append_blocks\" has incompatible type \"Optional[List[Optional[Any]]]\"; expected \"Optional[Set[int]]\"  [arg-type]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "test_filter_rewriting.py_deepseek_5e8e5461.py": "temp_file.py:269: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:339: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:492: error: Unexpected \"...\"  [misc]\ntemp_file.py:492: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:492: error: \"set\" is not subscriptable, use \"typing.Set\" instead  [misc]\ntemp_file.py:492: error: \"frozenset\" is not subscriptable, use \"typing.FrozenSet\" instead  [misc]\ntemp_file.py:492: error: \"dict\" is not subscriptable, use \"typing.Dict\" instead  [misc]\ntemp_file.py:492: error: \"tuple\" is not subscriptable, use \"typing.Tuple\" instead  [misc]\ntemp_file.py:517: error: Unexpected \"...\"  [misc]\ntemp_file.py:517: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:517: error: \"set\" is not subscriptable, use \"typing.Set\" instead  [misc]\ntemp_file.py:517: error: \"frozenset\" is not subscriptable, use \"typing.FrozenSet\" instead  [misc]\ntemp_file.py:517: error: \"dict\" is not subscriptable, use \"typing.Dict\" instead  [misc]\ntemp_file.py:517: error: \"tuple\" is not subscriptable, use \"typing.Tuple\" instead  [misc]\ntemp_file.py:561: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:572: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:584: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\nFound 17 errors in 1 file (checked 1 source file)\n",
    "test_incremental_unique_id.py_deepseek_5edd8e87.py": "temp_file.py:336: error: Dict entry 10 has incompatible type \"str\": \"Dict[str, str]\"; expected \"str\": \"str\"  [dict-item]\ntemp_file.py:351: error: The return type of a generator function should be \"Generator\" or one of its supertypes  [misc]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "variables.py_deepseek_a4df8a65.py": "temp_file.py:154: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:218: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:264: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:287: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:298: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\nFound 5 errors in 1 file (checked 1 source file)\n",
    "storage.py_deepseek_a492ec7a.py": "temp_file.py:96: error: Item \"List[Any]\" of \"Union[Dict[Any, Any], List[Any], int, str]\" has no attribute \"update\"  [union-attr]\ntemp_file.py:96: error: Item \"int\" of \"Union[Dict[Any, Any], List[Any], int, str]\" has no attribute \"update\"  [union-attr]\ntemp_file.py:96: error: Item \"str\" of \"Union[Dict[Any, Any], List[Any], int, str]\" has no attribute \"update\"  [union-attr]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "conf.py_deepseek_26eda4d5.py": "temp_file.py:401: error: Name \"AccessorDocumenter\" is not defined  [name-defined]\ntemp_file.py:402: error: Name \"AccessorAttributeDocumenter\" is not defined  [name-defined]\ntemp_file.py:403: error: Name \"AccessorMethodDocumenter\" is not defined  [name-defined]\ntemp_file.py:404: error: Name \"AccessorCallableDocumenter\" is not defined  [name-defined]\ntemp_file.py:405: error: Name \"PandasAutosummary\" is not defined  [name-defined]\nFound 5 errors in 1 file (checked 1 source file)\n",
    "cookiejar.py_deepseek_3ace996d.py": "temp_file.py:245: error: Need type annotation for \"tmp\"  [var-annotated]\nFound 1 error in 1 file (checked 1 source file)\n",
    "test_case.py_deepseek_7c281e68.py": "temp_file.py:149: error: The return type of a generator function should be \"Generator\" or one of its supertypes  [misc]\ntemp_file.py:317: error: Missing return statement  [return]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "test_thread_runner.py_deepseek_d2ca7599.py": "temp_file.py:120: error: Variable \"pipeline\" is not valid as a type  [valid-type]\ntemp_file.py:120: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:125: error: Variable \"pipeline\" is not valid as a type  [valid-type]\ntemp_file.py:125: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:159: error: Variable \"pipeline\" is not valid as a type  [valid-type]\ntemp_file.py:159: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:177: error: Variable \"pipeline\" is not valid as a type  [valid-type]\ntemp_file.py:177: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:203: error: Variable \"pipeline\" is not valid as a type  [valid-type]\ntemp_file.py:203: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:222: error: Variable \"pipeline\" is not valid as a type  [valid-type]\ntemp_file.py:222: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\nFound 6 errors in 1 file (checked 1 source file)\n",
    "test_dtypes.py_deepseek_4f82283d.py": "temp_file.py:37: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "vocab.py_deepseek_aa60a35d.py": "temp_file.py:23: error: No parent module -- cannot perform relative import\ntemp_file.py:24: error: No parent module -- cannot perform relative import\ntemp_file.py:428: error: No parent module -- cannot perform relative import\nFound 3 errors in 1 file (errors prevented further checking)\n",
    "conftest.py_deepseek_63dfd35f.py": "temp_file.py:182: error: The return type of a generator function should be \"Generator\" or one of its supertypes  [misc]\ntemp_file.py:193: error: \"Tuple[_patch[Mock], _patch[Mock], _patch[Mock]]\" has no attribute \"__enter__\"  [attr-defined]\ntemp_file.py:193: error: \"Tuple[_patch[Mock], _patch[Mock], _patch[Mock]]\" has no attribute \"__exit__\"  [attr-defined]\ntemp_file.py:254: error: Incompatible return value type (got \"Callable[[str], Any]\", expected \"Mock\")  [return-value]\ntemp_file.py:291: error: Incompatible return value type (got \"Callable[[str, List[str], Optional[Dict[str, Any]]], Any]\", expected \"Mock\")  [return-value]\ntemp_file.py:307: error: Incompatible return value type (got \"Callable[[str], Any]\", expected \"Mock\")  [return-value]\ntemp_file.py:339: error: Incompatible return value type (got \"Callable[[str, str, str, str, str, Optional[Dict[str, Any]]], Mock]\", expected \"Mock\")  [return-value]\ntemp_file.py:358: error: Incompatible return value type (got \"Callable[[Optional[List[str]], Optional[List[Mock]]], Mock]\", expected \"Mock\")  [return-value]\nFound 8 errors in 1 file (checked 1 source file)\n",
    "sensor.py_deepseek_dab7cb1b.py": "temp_file.py:131: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"Optional[int]\")  [assignment]\nFound 1 error in 1 file (checked 1 source file)\n",
    "applications.py_deepseek_9a81b2aa.py": "temp_file.py:195: error: Argument \"dispatch\" to \"add_middleware\" of \"Starlette\" has incompatible type \"Callable[..., Any]\"; expected <nothing>  [arg-type]\nFound 1 error in 1 file (checked 1 source file)\n",
    "raiden_network.py_deepseek_34be1bfe.py": "temp_file.py:211: error: Name \"pytest.MonkeyPatch\" is not defined  [name-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "choice.py_deepseek_7210e35e.py": "temp_file.py:7: error: No parent module -- cannot perform relative import\ntemp_file.py:8: error: No parent module -- cannot perform relative import\ntemp_file.py:9: error: No parent module -- cannot perform relative import\ntemp_file.py:10: error: No parent module -- cannot perform relative import\nFound 4 errors in 1 file (errors prevented further checking)\n",
    "test_package.py_deepseek_ecc92182.py": "temp_file.py:27: error: \"Generator\" expects 3 type arguments, but 1 given  [type-arg]\ntemp_file.py:47: error: \"Generator\" expects 3 type arguments, but 1 given  [type-arg]\ntemp_file.py:60: error: \"Generator\" expects 3 type arguments, but 1 given  [type-arg]\ntemp_file.py:68: error: \"Generator\" expects 3 type arguments, but 1 given  [type-arg]\ntemp_file.py:75: error: \"Generator\" expects 3 type arguments, but 1 given  [type-arg]\ntemp_file.py:304: error: Name \"pytest.LogCaptureFixture\" is not defined  [name-defined]\ntemp_file.py:369: error: Name \"pytest.LogCaptureFixture\" is not defined  [name-defined]\ntemp_file.py:385: error: Name \"pytest.LogCaptureFixture\" is not defined  [name-defined]\ntemp_file.py:451: error: \"Tuple[_patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch_dict]\" has no attribute \"__enter__\"  [attr-defined]\ntemp_file.py:451: error: \"Tuple[_patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch_dict]\" has no attribute \"__exit__\"  [attr-defined]\nFound 10 errors in 1 file (checked 1 source file)\n",
    "refactor.py_deepseek_d1039c8d.py": "temp_file.py:28: error: No parent module -- cannot perform relative import\ntemp_file.py:29: error: No parent module -- cannot perform relative import\ntemp_file.py:30: error: No parent module -- cannot perform relative import\nFound 3 errors in 1 file (errors prevented further checking)\n",
    "core.py_deepseek_35e36449.py": "temp_file.py:7: error: Name \"AbstractDataset\" is not defined  [name-defined]\ntemp_file.py:45: error: Name \"AbstractVersionedDataset\" is not defined  [name-defined]\ntemp_file.py:51: error: Name \"VersionAlreadyExistsError\" is not defined  [name-defined]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "gated_cnn_encoder.py_deepseek_3d4edbef.py": "temp_file.py:51: error: Item \"None\" of \"Optional[Tensor]\" has no attribute \"data\"  [union-attr]\ntemp_file.py:131: error: Incompatible return value type (got \"List[Tensor]\", expected \"Tensor\")  [return-value]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "exposed_entities.py_deepseek_94c60445.py": "temp_file.py:344: error: Unsupported left operand type for | (\"Dict[str, Any]\")  [operator]\nFound 1 error in 1 file (checked 1 source file)\n",
    "inference.py_deepseek_11291039.py": "temp_file.py:46: error: Missing return statement  [empty-body]\ntemp_file.py:49: error: Missing return statement  [empty-body]\ntemp_file.py:71: error: Missing return statement  [empty-body]\ntemp_file.py:80: error: Missing return statement  [empty-body]\ntemp_file.py:84: error: Missing return statement  [empty-body]\ntemp_file.py:145: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:156: error: Name \"copy\" is not defined  [name-defined]\ntemp_file.py:174: error: \"type\" has no attribute \"EOS_SYMBOL\"  [attr-defined]\ntemp_file.py:175: error: \"type\" has no attribute \"EOS_SYMBOL\"  [attr-defined]\ntemp_file.py:193: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:203: error: Name \"json\" is not defined  [name-defined]\ntemp_file.py:213: error: \"type\" has no attribute \"JSON_TEXT_KEY\"  [attr-defined]\ntemp_file.py:215: error: \"type\" has no attribute \"JSON_FACTORS_KEY\"  [attr-defined]\ntemp_file.py:216: error: \"type\" has no attribute \"JSON_SOURCE_PREFIX_KEY\"  [attr-defined]\ntemp_file.py:219: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:219: error: \"type\" has no attribute \"JSON_SOURCE_PREFIX_KEY\"  [attr-defined]\ntemp_file.py:220: error: \"type\" has no attribute \"JSON_SOURCE_PREFIX_FACTORS_KEY\"  [attr-defined]\ntemp_file.py:222: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:225: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:228: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:235: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:242: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:243: error: \"type\" has no attribute \"JSON_TEXT_KEY\"  [attr-defined]\ntemp_file.py:245: error: Argument 1 to \"len\" has incompatible type \"Optional[List[Any]]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:246: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:247: error: Argument 1 to \"len\" has incompatible type \"Optional[List[Any]]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:249: error: Argument 1 to \"len\" has incompatible type \"Union[List[Any], Any, None]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:250: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:251: error: Argument 1 to \"len\" has incompatible type \"Union[List[Any], Any, None]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:254: error: \"type\" has no attribute \"JSON_TARGET_PREFIX_KEY\"  [attr-defined]\ntemp_file.py:257: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:257: error: \"type\" has no attribute \"JSON_TEXT_KEY\"  [attr-defined]\ntemp_file.py:259: error: \"type\" has no attribute \"JSON_TARGET_PREFIX_FACTORS_KEY\"  [attr-defined]\ntemp_file.py:263: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:267: error: \"type\" has no attribute \"JSON_USE_TARGET_PREFIX_ALL_CHUNKS_KEY\"  [attr-defined]\ntemp_file.py:268: error: \"type\" has no attribute \"JSON_KEEP_TARGET_PREFIX_KEY\"  [attr-defined]\ntemp_file.py:270: error: \"type\" has no attribute \"JSON_RESTRICT_LEXICON_KEY\"  [attr-defined]\ntemp_file.py:274: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:278: error: \"type\" has no attribute \"JSON_AVOID_KEY\"  [attr-defined]\ntemp_file.py:279: error: \"type\" has no attribute \"JSON_CONSTRAINTS_KEY\"  [attr-defined]\ntemp_file.py:285: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:310: error: \"type\" has no attribute \"DEFAULT_FACTOR_DELIMITER\"  [attr-defined]\ntemp_file.py:325: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:343: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:364: error: Name \"copy\" is not defined  [name-defined]\ntemp_file.py:447: error: Item \"None\" of \"Optional[NBestTranslations]\" has no attribute \"target_ids_list\"  [union-attr]\ntemp_file.py:447: error: Item \"None\" of \"Optional[NBestTranslations]\" has no attribute \"scores\"  [union-attr]\ntemp_file.py:505: error: \"type\" has no attribute \"DEFAULT_KNN_LAMBDA\"  [attr-defined]\ntemp_file.py:506: error: \"type\" has no attribute \"DEFAULT_NUM_STD_MAX_OUTPUT_LENGTH\"  [attr-defined]\ntemp_file.py:523: error: \"type\" has no attribute \"PAD_ID\"  [attr-defined]\ntemp_file.py:524: error: \"type\" has no attribute \"EOS_ID\"  [attr-defined]\ntemp_file.py:524: error: \"type\" has no attribute \"PAD_ID\"  [attr-defined]\ntemp_file.py:526: error: \"type\" has no attribute \"UNK_ID\"  [attr-defined]\ntemp_file.py:531: error: \"SockeyeModel\" has no attribute \"eval\"  [attr-defined]\ntemp_file.py:533: error: Name \"models_max_input_output_length\" is not defined  [name-defined]\ntemp_file.py:542: error: \"type\" has no attribute \"BEAM_SEARCH_STOP_ALL\"  [attr-defined]\ntemp_file.py:545: error: Name \"get_search_algorithm\" is not defined  [name-defined]\ntemp_file.py:565: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:581: error: \"type\" has no attribute \"SPACE_FOR_XOS\"  [attr-defined]\ntemp_file.py:616: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:623: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:639: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:651: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:655: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:671: error: Name \"itertools\" is not defined  [name-defined]\ntemp_file.py:690: error: \"Translator\" has no attribute \"_make_result\"  [attr-defined]\ntemp_file.py:694: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:702: error: \"Translator\" has no attribute \"_translate_np\"; maybe \"translate\" or \"_translate_batch\"?  [attr-defined]\ntemp_file.py:704: error: Missing return statement  [return]\nFound 69 errors in 1 file (checked 1 source file)\n",
    "test_utils.py_deepseek_f3910096.py": "temp_file.py:199: error: Incompatible types in assignment (expression has type overloaded function, variable has type overloaded function)  [assignment]\nFound 1 error in 1 file (checked 1 source file)\n",
    "experiments.py_deepseek_56dbe657.py": "temp_file.py:47: error: No parent module -- cannot perform relative import\ntemp_file.py:48: error: No parent module -- cannot perform relative import\nFound 2 errors in 1 file (errors prevented further checking)\n",
    "cyclist.py_deepseek_a9eea13e.py": "temp_file.py:40: error: \"object\" has no attribute \"air_density\"  [attr-defined]\ntemp_file.py:81: error: \"object\" has no attribute \"air_density\"  [attr-defined]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "conftest.py_deepseek_48227454.py": "temp_file.py:35: error: \"Tuple[_patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]]]\" has no attribute \"__enter__\"  [attr-defined]\ntemp_file.py:35: error: \"Tuple[_patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]], _patch[Union[MagicMock, AsyncMock]]]\" has no attribute \"__exit__\"  [attr-defined]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "test_encoding.py_deepseek_de4987e5.py": "temp_file.py:267: error: Name \"pytest.LogCaptureFixture\" is not defined  [name-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "test_masked.py_deepseek_f680e59c.py": "temp_file.py:97: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:334: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:351: error: Incompatible types in assignment (expression has type \"Type[object]\", variable has type \"str\")  [assignment]\ntemp_file.py:356: error: Unexpected keyword argument \"reason\" for \"skip\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\_pytest\\outcomes.py:119: note: \"skip\" defined here\nFound 4 errors in 1 file (checked 1 source file)\n",
    "base_tests.py_deepseek_525dc3b2.py": "temp_file.py:215: error: Name \"find_spec\" is not defined  [name-defined]\ntemp_file.py:367: error: Argument \"json_\" to \"get_json_resp\" of \"SupersetTestCase\" has incompatible type \"Dict[str, Any]\"; expected \"Optional[str]\"  [arg-type]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "kill_if_no_output.py_deepseek_82698073.py": "temp_file.py:12: error: Module has no attribute \"fcntl\"  [attr-defined]\ntemp_file.py:12: error: Module has no attribute \"F_SETFL\"  [attr-defined]\ntemp_file.py:12: error: Module has no attribute \"F_GETFL\"  [attr-defined]\ntemp_file.py:85: error: Incompatible return value type (got \"Optional[int]\", expected \"int\")  [return-value]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "base.py_deepseek_c7a7f089.py": "temp_file.py:76: error: Name \"Project\" is not defined  [name-defined]\ntemp_file.py:76: error: Name \"Renderer\" is not defined  [name-defined]\ntemp_file.py:80: error: Name \"Project\" is not defined  [name-defined]\ntemp_file.py:80: error: Name \"Renderer\" is not defined  [name-defined]\ntemp_file.py:91: error: Name \"Project\" is not defined  [name-defined]\ntemp_file.py:91: error: Name \"Renderer\" is not defined  [name-defined]\ntemp_file.py:96: error: Name \"Project\" is not defined  [name-defined]\ntemp_file.py:96: error: Name \"Renderer\" is not defined  [name-defined]\ntemp_file.py:100: error: Name \"Project\" is not defined  [name-defined]\ntemp_file.py:100: error: Name \"Renderer\" is not defined  [name-defined]\ntemp_file.py:107: error: Name \"Project\" is not defined  [name-defined]\ntemp_file.py:107: error: Name \"Renderer\" is not defined  [name-defined]\ntemp_file.py:110: error: \"PinnedPackage\" has no attribute \"package\"  [attr-defined]\ntemp_file.py:110: error: \"PinnedPackage\" has no attribute \"version\"; maybe \"get_version\"?  [attr-defined]\ntemp_file.py:111: error: Argument 1 to \"Path\" has incompatible type \"Optional[str]\"; expected \"Union[str, PathLike[str]]\"  [arg-type]\nFound 15 errors in 1 file (checked 1 source file)\n",
    "test_hist_method.py_deepseek_c8b56cbb.py": "temp_file.py:476: error: List item 0 has incompatible type \"Union[str, List[str]]\"; expected \"str\"  [list-item]\nFound 1 error in 1 file (checked 1 source file)\n",
    "text_classification_json.py_deepseek_45388262.py": "temp_file.py:42: error: Name \"Iterable\" is not defined  [name-defined]\ntemp_file.py:42: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Iterable\")\ntemp_file.py:63: error: Unsupported operand types for > (\"int\" and \"None\")  [operator]\ntemp_file.py:63: note: Right operand is of type \"Optional[int]\"\nFound 2 errors in 1 file (checked 1 source file)\n",
    "alarm_control_panel.py_deepseek_e816d2fa.py": "temp_file.py:268: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"str\")  [assignment]\ntemp_file.py:305: error: Unsupported operand types for + (\"None\" and \"timedelta\")  [operator]\ntemp_file.py:335: error: Unsupported operand types for + (\"None\" and \"timedelta\")  [operator]\ntemp_file.py:397: error: Unsupported operand types for + (\"None\" and \"timedelta\")  [operator]\ntemp_file.py:404: error: Unsupported operand types for + (\"None\" and \"timedelta\")  [operator]\ntemp_file.py:408: error: Unsupported operand types for + (\"None\" and \"timedelta\")  [operator]\nFound 6 errors in 1 file (checked 1 source file)\n",
    "converter.py_deepseek_93b9a29a.py": "temp_file.py:49: error: Argument 1 to \"extend\" of \"list\" has incompatible type \"List[List[str]]\"; expected \"Iterable[str]\"  [arg-type]\ntemp_file.py:91: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"Union[str, List[str]]\")  [assignment]\ntemp_file.py:97: error: Argument \"pinyin\" to \"post_handle_nopinyin\" of \"DefaultConverter\" has incompatible type \"Union[str, List[str]]\"; expected \"List[str]\"  [arg-type]\ntemp_file.py:137: error: No overload variant of \"__setitem__\" of \"list\" matches argument types \"int\", \"List[str]\"  [call-overload]\ntemp_file.py:137: note: Possible overload variants:\ntemp_file.py:137: note:     def __setitem__(self, SupportsIndex, str, /) -> None\ntemp_file.py:137: note:     def __setitem__(self, slice, Iterable[str], /) -> None\ntemp_file.py:144: error: No overload variant of \"__setitem__\" of \"list\" matches argument types \"int\", \"List[str]\"  [call-overload]\ntemp_file.py:144: note: Possible overload variants:\ntemp_file.py:144: note:     def __setitem__(self, SupportsIndex, str, /) -> None\ntemp_file.py:144: note:     def __setitem__(self, slice, Iterable[str], /) -> None\ntemp_file.py:154: error: Incompatible return value type (got \"List[List[str]]\", expected \"List[str]\")  [return-value]\ntemp_file.py:169: error: Missing return statement  [return]\ntemp_file.py:171: error: \"str\" not callable  [operator]\nFound 8 errors in 1 file (checked 1 source file)\n",
    "gen.py_deepseek_1e5c7057.py": "temp_file.py:71: error: Unexpected keyword argument \"fork_name\"  [call-arg]\ntemp_file.py:71: error: Unexpected keyword argument \"preset_name\"  [call-arg]\ntemp_file.py:71: error: Unexpected keyword argument \"handler_name\"  [call-arg]\ntemp_file.py:71: error: Unexpected keyword argument \"tests_src_mod_name\"  [call-arg]\ntemp_file.py:115: error: Argument \"all_mods\" to \"get_provider\" has incompatible type \"Dict[str, Dict[str, str]]\"; expected \"Dict[str, Dict[str, Union[List[str], str]]]\"  [arg-type]\ntemp_file.py:130: error: Incompatible types in assignment (expression has type \"List[Dict[str, Union[List[str], str]]]\", target has type \"Dict[str, Union[List[str], str]]\")  [assignment]\ntemp_file.py:133: error: Unsupported left operand type for + (\"Dict[str, Union[List[str], str]]\")  [operator]\ntemp_file.py:135: error: \"Dict[str, Union[List[str], str]]\" has no attribute \"append\"  [attr-defined]\nFound 8 errors in 1 file (checked 1 source file)\n",
    "stripe.py_deepseek_68c08fad.py": "temp_file.py:736: error: Name \"RemoteRealmBillingSession\" is not defined  [name-defined]\ntemp_file.py:781: error: \"BillingSession\" has no attribute \"create_stripe_customer\"; maybe \"get_data_for_stripe_customer\"?  [attr-defined]\ntemp_file.py:985: error: Name \"RealmBillingSession\" is not defined  [name-defined]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "test_stack.py_deepseek_249558e0.py": "temp_file.py:113: error: Too few arguments  [call-arg]\nFound 1 error in 1 file (checked 1 source file)\n",
    "handlers.py_deepseek_9ad132ce.py": "temp_file.py:249: error: Incompatible types in assignment (expression has type \"Union[int, str]\", variable has type \"int\")  [assignment]\nFound 1 error in 1 file (checked 1 source file)\n",
    "parse.py_deepseek_20a9738b.py": "temp_file.py:14: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "test_process_justification_and_finalization.py_deepseek_5ded0881.py": "temp_file.py:29: error: \"State\" has no attribute \"slot\"  [attr-defined]\ntemp_file.py:29: error: \"Spec\" has no attribute \"SLOTS_PER_EPOCH\"  [attr-defined]\ntemp_file.py:31: error: \"Spec\" has no attribute \"get_previous_epoch\"  [attr-defined]\ntemp_file.py:32: error: \"Spec\" has no attribute \"get_current_epoch\"  [attr-defined]\ntemp_file.py:36: error: Type variable \"temp_file.PendingAttestation\" is unbound  [valid-type]\ntemp_file.py:36: note: (Hint: Use \"Generic[PendingAttestation]\" or \"Protocol[PendingAttestation]\" base class to bind \"PendingAttestation\" inside a class)\ntemp_file.py:36: note: (Hint: Use \"PendingAttestation\" in function signature to bind \"PendingAttestation\" inside a function)\ntemp_file.py:36: error: \"State\" has no attribute \"current_epoch_attestations\"  [attr-defined]\ntemp_file.py:38: error: \"State\" has no attribute \"previous_epoch_attestations\"  [attr-defined]\ntemp_file.py:43: error: Type variable \"temp_file.ParticipationFlags\" is unbound  [valid-type]\ntemp_file.py:43: note: (Hint: Use \"Generic[ParticipationFlags]\" or \"Protocol[ParticipationFlags]\" base class to bind \"ParticipationFlags\" inside a class)\ntemp_file.py:43: note: (Hint: Use \"ParticipationFlags\" in function signature to bind \"ParticipationFlags\" inside a function)\ntemp_file.py:43: error: \"State\" has no attribute \"current_epoch_participation\"  [attr-defined]\ntemp_file.py:45: error: \"State\" has no attribute \"previous_epoch_participation\"  [attr-defined]\ntemp_file.py:49: error: \"Spec\" has no attribute \"get_total_active_balance\"  [attr-defined]\ntemp_file.py:52: error: \"Spec\" has no attribute \"compute_start_slot_at_epoch\"  [attr-defined]\ntemp_file.py:53: error: \"Spec\" has no attribute \"get_committee_count_per_slot\"  [attr-defined]\ntemp_file.py:54: error: \"Spec\" has no attribute \"SLOTS_PER_EPOCH\"  [attr-defined]\ntemp_file.py:59: error: \"Spec\" has no attribute \"get_beacon_committee\"  [attr-defined]\ntemp_file.py:63: error: \"State\" has no attribute \"validators\"  [attr-defined]\ntemp_file.py:73: error: \"Spec\" has no attribute \"PendingAttestation\"  [attr-defined]\ntemp_file.py:75: error: \"Spec\" has no attribute \"AttestationData\"  [attr-defined]\ntemp_file.py:85: error: PendingAttestation? has no attribute \"data\"  [attr-defined]\ntemp_file.py:89: error: \"Spec\" has no attribute \"ParticipationFlags\"  [attr-defined]\ntemp_file.py:89: error: \"Spec\" has no attribute \"TIMELY_HEAD_FLAG_INDEX\"  [attr-defined]\ntemp_file.py:90: error: \"Spec\" has no attribute \"ParticipationFlags\"  [attr-defined]\ntemp_file.py:90: error: \"Spec\" has no attribute \"TIMELY_SOURCE_FLAG_INDEX\"  [attr-defined]\ntemp_file.py:92: error: \"Spec\" has no attribute \"ParticipationFlags\"  [attr-defined]\ntemp_file.py:92: error: \"Spec\" has no attribute \"TIMELY_TARGET_FLAG_INDEX\"  [attr-defined]\ntemp_file.py:95: error: \"Spec\" has no attribute \"Checkpoint\"  [attr-defined]\ntemp_file.py:96: error: \"Spec\" has no attribute \"Checkpoint\"  [attr-defined]\ntemp_file.py:97: error: \"Spec\" has no attribute \"Checkpoint\"  [attr-defined]\ntemp_file.py:98: error: \"Spec\" has no attribute \"Checkpoint\"  [attr-defined]\ntemp_file.py:99: error: \"Spec\" has no attribute \"Checkpoint\"  [attr-defined]\ntemp_file.py:104: error: \"State\" has no attribute \"block_roots\"  [attr-defined]\ntemp_file.py:104: error: \"Spec\" has no attribute \"compute_start_slot_at_epoch\"  [attr-defined]\ntemp_file.py:104: error: \"Checkpoint\" has no attribute \"epoch\"  [attr-defined]\ntemp_file.py:104: error: \"Spec\" has no attribute \"SLOTS_PER_HISTORICAL_ROOT\"  [attr-defined]\ntemp_file.py:104: error: \"Checkpoint\" has no attribute \"root\"  [attr-defined]\ntemp_file.py:108: error: \"Spec\" has no attribute \"SLOTS_PER_EPOCH\"  [attr-defined]\ntemp_file.py:113: error: Type variable \"temp_file.Checkpoint\" is unbound  [valid-type]\ntemp_file.py:113: note: (Hint: Use \"Generic[Checkpoint]\" or \"Protocol[Checkpoint]\" base class to bind \"Checkpoint\" inside a class)\ntemp_file.py:113: note: (Hint: Use \"Checkpoint\" in function signature to bind \"Checkpoint\" inside a function)\ntemp_file.py:113: error: \"State\" has no attribute \"finalized_checkpoint\"  [attr-defined]\ntemp_file.py:114: error: \"State\" has no attribute \"previous_justified_checkpoint\"  [attr-defined]\ntemp_file.py:115: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:116: error: \"State\" has no attribute \"justification_bits\"  [attr-defined]\ntemp_file.py:116: error: \"Spec\" has no attribute \"Bitvector\"  [attr-defined]\ntemp_file.py:116: error: \"Spec\" has no attribute \"JUSTIFICATION_BITS_LENGTH\"  [attr-defined]\ntemp_file.py:117: error: \"State\" has no attribute \"justification_bits\"  [attr-defined]\ntemp_file.py:126: error: \"State\" has no attribute \"previous_justified_checkpoint\"  [attr-defined]\ntemp_file.py:128: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:129: error: \"State\" has no attribute \"finalized_checkpoint\"  [attr-defined]\ntemp_file.py:131: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:132: error: \"State\" has no attribute \"finalized_checkpoint\"  [attr-defined]\ntemp_file.py:136: error: \"Spec\" has no attribute \"SLOTS_PER_EPOCH\"  [attr-defined]\ntemp_file.py:141: error: Type variable \"temp_file.Checkpoint\" is unbound  [valid-type]\ntemp_file.py:141: note: (Hint: Use \"Generic[Checkpoint]\" or \"Protocol[Checkpoint]\" base class to bind \"Checkpoint\" inside a class)\ntemp_file.py:141: note: (Hint: Use \"Checkpoint\" in function signature to bind \"Checkpoint\" inside a function)\ntemp_file.py:141: error: \"State\" has no attribute \"finalized_checkpoint\"  [attr-defined]\ntemp_file.py:142: error: \"State\" has no attribute \"previous_justified_checkpoint\"  [attr-defined]\ntemp_file.py:143: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:144: error: \"State\" has no attribute \"justification_bits\"  [attr-defined]\ntemp_file.py:144: error: \"Spec\" has no attribute \"Bitvector\"  [attr-defined]\ntemp_file.py:144: error: \"Spec\" has no attribute \"JUSTIFICATION_BITS_LENGTH\"  [attr-defined]\ntemp_file.py:145: error: \"State\" has no attribute \"justification_bits\"  [attr-defined]\ntemp_file.py:154: error: \"State\" has no attribute \"previous_justified_checkpoint\"  [attr-defined]\ntemp_file.py:156: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:157: error: \"State\" has no attribute \"finalized_checkpoint\"  [attr-defined]\ntemp_file.py:159: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:160: error: \"State\" has no attribute \"finalized_checkpoint\"  [attr-defined]\ntemp_file.py:164: error: \"State\" has no attribute \"slot\"  [attr-defined]\ntemp_file.py:164: error: \"Spec\" has no attribute \"SLOTS_PER_EPOCH\"  [attr-defined]\ntemp_file.py:169: error: Type variable \"temp_file.Checkpoint\" is unbound  [valid-type]\ntemp_file.py:169: note: (Hint: Use \"Generic[Checkpoint]\" or \"Protocol[Checkpoint]\" base class to bind \"Checkpoint\" inside a class)\ntemp_file.py:169: note: (Hint: Use \"Checkpoint\" in function signature to bind \"Checkpoint\" inside a function)\ntemp_file.py:169: error: \"State\" has no attribute \"finalized_checkpoint\"  [attr-defined]\ntemp_file.py:170: error: \"State\" has no attribute \"previous_justified_checkpoint\"  [attr-defined]\ntemp_file.py:171: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:172: error: \"State\" has no attribute \"justification_bits\"  [attr-defined]\ntemp_file.py:172: error: \"Spec\" has no attribute \"Bitvector\"  [attr-defined]\ntemp_file.py:172: error: \"Spec\" has no attribute \"JUSTIFICATION_BITS_LENGTH\"  [attr-defined]\ntemp_file.py:173: error: \"State\" has no attribute \"justification_bits\"  [attr-defined]\ntemp_file.py:187: error: \"State\" has no attribute \"previous_justified_checkpoint\"  [attr-defined]\ntemp_file.py:189: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:190: error: \"State\" has no attribute \"finalized_checkpoint\"  [attr-defined]\ntemp_file.py:192: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:193: error: \"State\" has no attribute \"finalized_checkpoint\"  [attr-defined]\ntemp_file.py:197: error: \"Spec\" has no attribute \"SLOTS_PER_EPOCH\"  [attr-defined]\ntemp_file.py:202: error: Type variable \"temp_file.Checkpoint\" is unbound  [valid-type]\ntemp_file.py:202: note: (Hint: Use \"Generic[Checkpoint]\" or \"Protocol[Checkpoint]\" base class to bind \"Checkpoint\" inside a class)\ntemp_file.py:202: note: (Hint: Use \"Checkpoint\" in function signature to bind \"Checkpoint\" inside a function)\ntemp_file.py:202: error: \"State\" has no attribute \"finalized_checkpoint\"  [attr-defined]\ntemp_file.py:203: error: \"State\" has no attribute \"previous_justified_checkpoint\"  [attr-defined]\ntemp_file.py:204: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:205: error: \"State\" has no attribute \"justification_bits\"  [attr-defined]\ntemp_file.py:205: error: \"Spec\" has no attribute \"Bitvector\"  [attr-defined]\ntemp_file.py:205: error: \"Spec\" has no attribute \"JUSTIFICATION_BITS_LENGTH\"  [attr-defined]\ntemp_file.py:206: error: \"State\" has no attribute \"justification_bits\"  [attr-defined]\ntemp_file.py:216: error: \"State\" has no attribute \"previous_justified_checkpoint\"  [attr-defined]\ntemp_file.py:218: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:219: error: \"State\" has no attribute \"finalized_checkpoint\"  [attr-defined]\ntemp_file.py:221: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:222: error: \"State\" has no attribute \"finalized_checkpoint\"  [attr-defined]\ntemp_file.py:276: error: \"Spec\" has no attribute \"SLOTS_PER_EPOCH\"  [attr-defined]\ntemp_file.py:279: error: \"Spec\" has no attribute \"get_current_epoch\"  [attr-defined]\ntemp_file.py:280: error: \"Spec\" has no attribute \"get_active_validator_indices\"  [attr-defined]\ntemp_file.py:284: error: \"State\" has no attribute \"validators\"  [attr-defined]\ntemp_file.py:287: error: \"Spec\" has no attribute \"config\"  [attr-defined]\ntemp_file.py:292: error: Type variable \"temp_file.Checkpoint\" is unbound  [valid-type]\ntemp_file.py:292: note: (Hint: Use \"Generic[Checkpoint]\" or \"Protocol[Checkpoint]\" base class to bind \"Checkpoint\" inside a class)\ntemp_file.py:292: note: (Hint: Use \"Checkpoint\" in function signature to bind \"Checkpoint\" inside a function)\ntemp_file.py:292: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\ntemp_file.py:293: error: Type variable \"temp_file.Checkpoint\" is unbound  [valid-type]\ntemp_file.py:293: note: (Hint: Use \"Generic[Checkpoint]\" or \"Protocol[Checkpoint]\" base class to bind \"Checkpoint\" inside a class)\ntemp_file.py:293: note: (Hint: Use \"Checkpoint\" in function signature to bind \"Checkpoint\" inside a function)\ntemp_file.py:293: error: \"Spec\" has no attribute \"Checkpoint\"  [attr-defined]\ntemp_file.py:295: error: \"Spec\" has no attribute \"get_block_root\"  [attr-defined]\ntemp_file.py:307: error: Type variable \"temp_file.PendingAttestation\" is unbound  [valid-type]\ntemp_file.py:307: note: (Hint: Use \"Generic[PendingAttestation]\" or \"Protocol[PendingAttestation]\" base class to bind \"PendingAttestation\" inside a class)\ntemp_file.py:307: note: (Hint: Use \"PendingAttestation\" in function signature to bind \"PendingAttestation\" inside a function)\ntemp_file.py:307: error: \"Spec\" has no attribute \"get_matching_target_attestations\"  [attr-defined]\ntemp_file.py:308: error: \"Spec\" has no attribute \"get_total_active_balance\"  [attr-defined]\ntemp_file.py:309: error: \"Spec\" has no attribute \"get_attesting_balance\"  [attr-defined]\ntemp_file.py:312: error: \"Spec\" has no attribute \"get_total_balance\"  [attr-defined]\ntemp_file.py:316: error: \"Spec\" has no attribute \"get_unslashed_participating_indices\"  [attr-defined]\ntemp_file.py:316: error: \"Spec\" has no attribute \"TIMELY_TARGET_FLAG_INDEX\"  [attr-defined]\ntemp_file.py:317: error: \"Spec\" has no attribute \"get_total_active_balance\"  [attr-defined]\ntemp_file.py:318: error: \"Spec\" has no attribute \"get_total_balance\"  [attr-defined]\ntemp_file.py:321: error: \"Spec\" has no attribute \"get_total_balance\"  [attr-defined]\ntemp_file.py:327: error: \"State\" has no attribute \"current_justified_checkpoint\"  [attr-defined]\nFound 113 errors in 1 file (checked 1 source file)\n",
    "integrations.py_deepseek_b64115f4.py": "temp_file.py:3: error: Name \"Integration\" is not defined  [name-defined]\ntemp_file.py:4: error: Name \"INTEGRATIONS\" is not defined  [name-defined]\ntemp_file.py:5: error: Name \"WebhookIntegration\" is not defined  [name-defined]\ntemp_file.py:7: error: Name \"import_string\" is not defined  [name-defined]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "test_assert_frame_equal.py_deepseek_ab19c425.py": "temp_file.py:9: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "handlers.py_deepseek_21ef1750.py": "temp_file.py:108: error: \"str\" has no attribute \"toString\"  [attr-defined]\ntemp_file.py:128: error: Argument 1 to \"format\" of \"Handler\" has incompatible type \"Union[LogRecord, str]\"; expected \"LogRecord\"  [arg-type]\ntemp_file.py:176: error: Argument 1 to \"handleError\" of \"Handler\" has incompatible type \"Union[LogRecord, str]\"; expected \"LogRecord\"  [arg-type]\ntemp_file.py:342: error: \"QueueHandler\" has no attribute \"queue\"; maybe \"enqueue\"?  [attr-defined]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "test_generic.py_deepseek_f4c8dffd.py": "temp_file.py:25: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:136: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "classes.py_deepseek_5a5bb443.py": "temp_file.py:168: error: Name \"re\" is not defined  [name-defined]\ntemp_file.py:169: error: Name \"re\" is not defined  [name-defined]\ntemp_file.py:214: error: List comprehension has incompatible type List[BaseName]; expected List[Name]  [misc]\ntemp_file.py:231: error: List comprehension has incompatible type List[BaseName]; expected List[Name]  [misc]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "xq_follower.py_deepseek_cbbc76a8.py": "temp_file.py:54: error: Incompatible default for argument \"total_assets\" (default has type \"int\", argument has type \"Union[Number, List[Number]]\")  [assignment]\ntemp_file.py:105: error: Argument 2 to \"zip\" has incompatible type \"Union[Number, List[Number]]\"; expected \"Iterable[Number]\"  [arg-type]\ntemp_file.py:105: error: Argument 3 to \"zip\" has incompatible type \"Union[Number, List[Number], None]\"; expected \"Iterable[Number]\"  [arg-type]\ntemp_file.py:130: error: Unsupported operand types for * (\"Number\" and \"float\")  [operator]\ntemp_file.py:130: error: Incompatible types in assignment (expression has type \"float\", variable has type \"Optional[Number]\")  [assignment]\ntemp_file.py:133: error: Unsupported operand types for > (\"float\" and \"Number\")  [operator]\ntemp_file.py:169: error: Incompatible return value type (got \"int\", expected \"Number\")  [return-value]\ntemp_file.py:175: error: Unsupported left operand type for - (\"Number\")  [operator]\ntemp_file.py:179: error: Argument 1 to \"abs\" has incompatible type \"Number\"; expected \"SupportsAbs[<nothing>]\"  [arg-type]\ntemp_file.py:179: error: Unsupported operand types for * (\"float\" and \"Number\")  [operator]\ntemp_file.py:187: error: Unsupported operand types for < (\"int\" and \"Number\")  [operator]\ntemp_file.py:210: error: Value of type \"Optional[List[Any]]\" is not indexable  [index]\nFound 12 errors in 1 file (checked 1 source file)\n",
    "binary_sensor.py_deepseek_0433b0a2.py": "temp_file.py:17: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "api.py_deepseek_a31f2df4.py": "temp_file.py:129: error: Too many values to unpack (3 expected, 4 provided)  [misc]\nFound 1 error in 1 file (checked 1 source file)\n",
    "execution_context.py_deepseek_71a45ddd.py": "temp_file.py:62: error: Incompatible return value type (got \"Optional[int]\", expected \"int\")  [return-value]\ntemp_file.py:70: error: Incompatible return value type (got \"Optional[int]\", expected \"int\")  [return-value]\ntemp_file.py:78: error: Incompatible return value type (got \"Optional[int]\", expected \"int\")  [return-value]\ntemp_file.py:82: error: Incompatible return value type (got \"Optional[Any]\", expected \"Iterable[Any]\")  [return-value]\ntemp_file.py:86: error: Incompatible return value type (got \"Optional[int]\", expected \"int\")  [return-value]\nFound 5 errors in 1 file (checked 1 source file)\n",
    "functions.py_deepseek_02c2585e.py": "temp_file.py:51: error: Incompatible return value type (got \"Sequence[str]\", expected \"Tuple[str, ...]\")  [return-value]\ntemp_file.py:121: error: Incompatible types in assignment (expression has type \"Optional[str]\", variable has type \"str\")  [assignment]\ntemp_file.py:159: error: Argument 1 to \"ImplicitNSInfo\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\ntemp_file.py:159: error: Item \"List[str]\" of \"Optional[List[str]]\" has no attribute \"_path\"  [union-attr]\ntemp_file.py:159: error: Item \"None\" of \"Optional[List[str]]\" has no attribute \"_path\"  [union-attr]\ntemp_file.py:243: error: Incompatible types in assignment (expression has type \"Path\", variable has type \"str\")  [assignment]\nFound 6 errors in 1 file (checked 1 source file)\n",
    "test_validator_unittest.py_deepseek_d0ddfc83.py": "temp_file.py:186: error: Need type annotation for \"eth1_chain\" (hint: \"eth1_chain: List[<type>] = ...\")  [var-annotated]\ntemp_file.py:284: error: Need type annotation for \"eth1_data_votes\" (hint: \"eth1_data_votes: List[<type>] = ...\")  [var-annotated]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "optimizers.py_deepseek_9ab847a5.py": "temp_file.py:18: error: Item \"Parameter\" of \"Union[Dict[str, Any], Parameter]\" has no attribute \"update\"  [union-attr]\ntemp_file.py:28: error: Name \"re\" is not defined  [name-defined]\ntemp_file.py:37: error: Item \"Tensor\" of \"Union[Any, Tensor]\" has no attribute \"append\"  [union-attr]\ntemp_file.py:37: error: Invalid index type \"str\" for \"Union[Dict[str, Any], Parameter]\"; expected type \"Union[SupportsIndex, None, bool, int, slice, ellipsis, Tensor, _NestedSequence[Union[None, bool, int, slice, ellipsis, Tensor]], Tuple[Union[SupportsIndex, None, bool, int, slice, ellipsis, Tensor, _NestedSequence[Union[None, bool, int, slice, ellipsis, Tensor]]], ...]]\"  [index]\ntemp_file.py:37: note: Following member(s) of \"str\" have conflicts:\ntemp_file.py:37: note:     Expected:\ntemp_file.py:37: note:         def __contains__(self, object, /) -> bool\ntemp_file.py:37: note:     Got:\ntemp_file.py:37: note:         def __contains__(self, str, /) -> bool\ntemp_file.py:37: note:     Expected:\ntemp_file.py:37: note:         def __getitem__(self, int, /) -> Union[None, bool, int, slice, ellipsis, Tensor, _NestedSequence[Union[None, bool, int, slice, ellipsis, Tensor]]]\ntemp_file.py:37: note:     Got:\ntemp_file.py:37: note:         def __getitem__(self, Union[SupportsIndex, slice], /) -> str\ntemp_file.py:37: note:     <2 more conflict(s) not shown>\ntemp_file.py:40: error: Item \"Tensor\" of \"Union[Any, Tensor]\" has no attribute \"append\"  [union-attr]\ntemp_file.py:40: error: Invalid index type \"str\" for \"Union[Dict[str, Any], Parameter]\"; expected type \"Union[SupportsIndex, None, bool, int, slice, ellipsis, Tensor, _NestedSequence[Union[None, bool, int, slice, ellipsis, Tensor]], Tuple[Union[SupportsIndex, None, bool, int, slice, ellipsis, Tensor, _NestedSequence[Union[None, bool, int, slice, ellipsis, Tensor]]], ...]]\"  [index]\ntemp_file.py:40: note: Following member(s) of \"str\" have conflicts:\ntemp_file.py:40: note:     Expected:\ntemp_file.py:40: note:         def __contains__(self, object, /) -> bool\ntemp_file.py:40: note:     Got:\ntemp_file.py:40: note:         def __contains__(self, str, /) -> bool\ntemp_file.py:40: note:     Expected:\ntemp_file.py:40: note:         def __getitem__(self, int, /) -> Union[None, bool, int, slice, ellipsis, Tensor, _NestedSequence[Union[None, bool, int, slice, ellipsis, Tensor]]]\ntemp_file.py:40: note:     Got:\ntemp_file.py:40: note:         def __getitem__(self, Union[SupportsIndex, slice], /) -> str\ntemp_file.py:40: note:     <2 more conflict(s) not shown>\ntemp_file.py:45: error: \"object\" has no attribute \"get\"  [attr-defined]\ntemp_file.py:47: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:48: error: Value of type \"object\" is not indexable  [index]\ntemp_file.py:52: error: \"object\" has no attribute \"items\"  [attr-defined]\ntemp_file.py:55: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:61: error: Incompatible types in assignment (expression has type \"List[object]\", variable has type \"Union[List[Dict[str, Any]], List[Parameter]]\")  [assignment]\ntemp_file.py:65: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:68: error: Item \"Parameter\" of \"Union[Dict[str, Any], Parameter]\" has no attribute \"items\"  [union-attr]\ntemp_file.py:70: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:74: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:87: error: Name \"logger\" is not defined  [name-defined]\ntemp_file.py:128: error: Name \"re\" is not defined  [name-defined]\ntemp_file.py:158: error: Name \"copy\" is not defined  [name-defined]\ntemp_file.py:174: error: Signature of \"step\" incompatible with supertype \"Optimizer\"  [override]\ntemp_file.py:174: note:      Superclass:\ntemp_file.py:174: note:          @overload\ntemp_file.py:174: note:          def step(self, closure: None = ...) -> None\ntemp_file.py:174: note:          @overload\ntemp_file.py:174: note:          def step(self, closure: Callable[[], float]) -> float\ntemp_file.py:174: note:      Subclass:\ntemp_file.py:174: note:          def step(self) -> None\ntemp_file.py:289: error: Unexpected keyword argument \"lr\" for \"__init__\" of \"Optimizer\"  [call-arg]\ntemp_file.py:511: error: Name \"math\" is not defined  [name-defined]\ntemp_file.py:522: error: Name \"math\" is not defined  [name-defined]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:289: error: Unexpected keyword argument \"betas\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:289: error: Unexpected keyword argument \"eps\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:289: error: Unexpected keyword argument \"weight_decay\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:289: error: Unexpected keyword argument \"correct_bias\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:315: error: Unexpected keyword argument \"lr\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:315: error: Unexpected keyword argument \"eps\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:315: error: Unexpected keyword argument \"clip_threshold\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:315: error: Unexpected keyword argument \"decay_rate\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:315: error: Unexpected keyword argument \"beta1\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:315: error: Unexpected keyword argument \"weight_decay\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:315: error: Unexpected keyword argument \"scale_parameter\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:315: error: Unexpected keyword argument \"relative_step\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:315: error: Unexpected keyword argument \"warmup_init\" for \"__init__\" of \"Optimizer\"  [call-arg]\nD:\\python3.8\\lib\\site-packages\\torch\\optim\\optimizer.py:339: note: \"__init__\" of \"Optimizer\" defined here\ntemp_file.py:460: error: Signature of \"step\" incompatible with supertype \"Optimizer\"  [override]\ntemp_file.py:460: note:      Superclass:\ntemp_file.py:460: note:          @overload\ntemp_file.py:460: note:          def step(self, closure: None = ...) -> None\ntemp_file.py:460: note:          @overload\ntemp_file.py:460: note:          def step(self, closure: Callable[[], float]) -> float\ntemp_file.py:460: note:      Subclass:\ntemp_file.py:460: note:          def step(self, closure: Optional[Callable[[], float]] = ...) -> Optional[float]\nFound 37 errors in 1 file (checked 1 source file)\n",
    "base.py_deepseek_432e748f.py": "temp_file.py:20: error: \"TypeVar\" has no attribute \"parent_context\"  [attr-defined]\ntemp_file.py:28: error: \"TypeVar\" has no attribute \"constraints\"; maybe \"__constraints__\"?  [attr-defined]\ntemp_file.py:34: error: \"TypeVar\" has no attribute \"py__name__\"; maybe \"__name__\"?  [attr-defined]\ntemp_file.py:47: error: \"TypeVar\" has no attribute \"py__name__\"; maybe \"__name__\"?  [attr-defined]\ntemp_file.py:51: error: \"TypeVar\" has no attribute \"name\"  [attr-defined]\ntemp_file.py:158: error: The return type of a generator function should be \"Generator\" or one of its supertypes  [misc]\nFound 6 errors in 1 file (checked 1 source file)\n",
    "conftest.py_deepseek_06d842d1.py": "temp_file.py:122: error: Need type annotation for \"resp\" (hint: \"resp: Dict[<type>, <type>] = ...\")  [var-annotated]\nFound 1 error in 1 file (checked 1 source file)\n",
    "blockchain.py_deepseek_8dc4e30c.py": "temp_file.py:41: error: Incompatible types in assignment (expression has type \"List[Any]\", variable has type \"Set[Any]\")  [assignment]\nFound 1 error in 1 file (checked 1 source file)\n",
    "boxplot.py_deepseek_8e4f22bc.py": "temp_file.py:305: error: List item 0 has incompatible type \"Optional[str]\"; expected \"str\"  [list-item]\ntemp_file.py:340: error: Value of type \"Union[str, List[str], None]\" is not indexable  [index]\ntemp_file.py:340: error: Argument 1 to \"len\" has incompatible type \"Union[str, List[str], None]\"; expected \"Sized\"  [arg-type]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "test_mediation_fee.py_deepseek_bcbdb4de.py": "temp_file.py:438: error: The return type of a generator function should be \"Generator\" or one of its supertypes  [misc]\nFound 1 error in 1 file (checked 1 source file)\n",
    "transformer_embeddings_test.py_deepseek_7e8d35e5.py": "temp_file.py:85: error: Incompatible default for argument \"input_ids\" (default has type \"None\", argument has type \"Tensor\")  [assignment]\ntemp_file.py:85: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True\ntemp_file.py:85: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase\ntemp_file.py:85: error: Incompatible default for argument \"token_type_ids\" (default has type \"None\", argument has type \"Tensor\")  [assignment]\ntemp_file.py:85: error: Incompatible default for argument \"position_ids\" (default has type \"None\", argument has type \"Tensor\")  [assignment]\ntemp_file.py:85: error: Incompatible default for argument \"inputs_embeds\" (default has type \"None\", argument has type \"Tensor\")  [assignment]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "player.py_deepseek_504483b4.py": "temp_file.py:18: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "beam_search_test.py_deepseek_e8e5dc23.py": "temp_file.py:178: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:178: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:178: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:179: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:179: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:179: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:180: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:180: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:180: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:181: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:181: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:181: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:182: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:182: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:182: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:183: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:183: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:183: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:184: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:184: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:184: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:185: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:185: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:185: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:186: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:186: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:186: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:187: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:187: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:187: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:188: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:188: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:188: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:189: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:189: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:189: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:190: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:190: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:190: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:191: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:191: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:191: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:192: error: List item 0 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:192: error: List item 1 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:192: error: List item 2 has incompatible type \"int\"; expected \"List[int]\"  [list-item]\ntemp_file.py:194: error: List item 0 has incompatible type \"List[List[List[int]]]\"; expected \"List[List[int]]\"  [list-item]\nFound 46 errors in 1 file (checked 1 source file)\n",
    "test_indexing.py_deepseek_fa642a88.py": "temp_file.py:68: error: Name \"pytest.MonkeyPatch\" is not defined  [name-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "media_player.py_deepseek_6a1193c9.py": "temp_file.py:106: error: Module \"telnetlib\" does not explicitly export attribute \"socket\"  [attr-defined]\ntemp_file.py:123: error: Argument 3 to \"Telnet\" has incompatible type \"Optional[int]\"; expected \"float\"  [arg-type]\ntemp_file.py:130: error: Module \"telnetlib\" does not explicitly export attribute \"socket\"  [attr-defined]\ntemp_file.py:136: error: Argument 3 to \"Telnet\" has incompatible type \"Optional[int]\"; expected \"float\"  [arg-type]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "python.py_deepseek_6ca98bab.py": "temp_file.py:251: error: \"RaidenAPI\" has no attribute \"get_channel_list\"; maybe \"get_channel\"?  [attr-defined]\ntemp_file.py:300: error: \"RaidenAPI\" has no attribute \"get_tokens_list\"  [attr-defined]\ntemp_file.py:349: error: \"RaidenAPI\" has no attribute \"get_channel_list\"; maybe \"get_channel\"?  [attr-defined]\ntemp_file.py:944: error: Need type annotation for \"channels_to_conditions\" (hint: \"channels_to_conditions: Dict[<type>, <type>] = ...\")  [var-annotated]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "test_transition.py_deepseek_5b8686d2.py": "temp_file.py:30: error: \"str\" not callable  [operator]\ntemp_file.py:41: error: \"str\" not callable  [operator]\ntemp_file.py:43: error: \"str\" not callable  [operator]\ntemp_file.py:72: error: \"str\" not callable  [operator]\ntemp_file.py:91: error: \"str\" not callable  [operator]\ntemp_file.py:93: error: \"str\" not callable  [operator]\ntemp_file.py:111: error: \"str\" not callable  [operator]\ntemp_file.py:115: error: \"str\" not callable  [operator]\ntemp_file.py:132: error: \"str\" not callable  [operator]\ntemp_file.py:136: error: \"str\" not callable  [operator]\ntemp_file.py:138: error: \"str\" not callable  [operator]\ntemp_file.py:142: error: \"str\" not callable  [operator]\ntemp_file.py:145: error: \"str\" not callable  [operator]\ntemp_file.py:195: error: \"str\" not callable  [operator]\ntemp_file.py:197: error: \"str\" not callable  [operator]\ntemp_file.py:199: error: \"str\" not callable  [operator]\ntemp_file.py:202: error: \"str\" not callable  [operator]\ntemp_file.py:220: error: \"str\" not callable  [operator]\nFound 18 errors in 1 file (checked 1 source file)\n",
    "document.py_deepseek_99eb2cc1.py": "temp_file.py:177: error: Item \"None\" of \"Optional[Any]\" has no attribute \"properties\"  [union-attr]\nFound 1 error in 1 file (checked 1 source file)\n",
    "matplotlib.py_deepseek_714edf47.py": "temp_file.py:205: error: Cannot determine type of \"data\"  [has-type]\ntemp_file.py:206: error: Cannot determine type of \"data\"  [has-type]\ntemp_file.py:207: error: Cannot determine type of \"data\"  [has-type]\ntemp_file.py:323: error: Cannot determine type of \"bottom\"  [has-type]\ntemp_file.py:324: error: Cannot determine type of \"bottom\"  [has-type]\ntemp_file.py:327: error: Cannot determine type of \"data\"  [has-type]\ntemp_file.py:327: error: Cannot determine type of \"bins\"  [has-type]\ntemp_file.py:353: error: Argument 1 to \"len\" has incompatible type \"Optional[Sequence[float]]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:355: error: Argument 1 to \"len\" has incompatible type \"Optional[Sequence[float]]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:358: error: Value of type \"Optional[Sequence[float]]\" is not indexable  [index]\ntemp_file.py:411: error: Cannot determine type of \"data\"  [has-type]\ntemp_file.py:588: error: Argument \"subplots\" to \"_plot\" has incompatible type \"Optional[bool]\"; expected \"bool\"  [arg-type]\nFound 12 errors in 1 file (checked 1 source file)\n",
    "test_drop_duplicates.py_deepseek_eba4cfd2.py": "temp_file.py:73: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "network.py_deepseek_8d1b1d1c.py": "temp_file.py:233: error: Variable \"temp_file.AppChannels\" is not valid as a type  [valid-type]\ntemp_file.py:233: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:240: error: AppChannels? has no attribute \"__iter__\" (not iterable)  [attr-defined]\ntemp_file.py:329: error: Variable \"temp_file.AppChannels\" is not valid as a type  [valid-type]\ntemp_file.py:329: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:330: error: Variable \"temp_file.AppChannels\" is not valid as a type  [valid-type]\ntemp_file.py:330: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:349: error: Variable \"temp_file.AppChannels\" is not valid as a type  [valid-type]\ntemp_file.py:349: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:358: error: Variable \"temp_file.AppChannels\" is not valid as a type  [valid-type]\ntemp_file.py:358: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:670: error: Variable \"temp_file.AppChannels\" is not valid as a type  [valid-type]\ntemp_file.py:670: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:678: error: AppChannels? has no attribute \"__iter__\" (not iterable)  [attr-defined]\nFound 8 errors in 1 file (checked 1 source file)\n",
    "test_backup_restore.py_deepseek_873b7064.py": "temp_file.py:80: error: invalid syntax  [syntax]\nFound 1 error in 1 file (errors prevented further checking)\n",
    "light.py_deepseek_d56e7802.py": "temp_file.py:27: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "learning_rate_scheduler.py_deepseek_290a2bf8.py": "temp_file.py:53: error: Argument 1 to \"step\" of \"LRScheduler\" has incompatible type \"float\"; expected \"Optional[int]\"  [arg-type]\nFound 1 error in 1 file (checked 1 source file)\n",
    "bases.py_deepseek_770850d1.py": "temp_file.py:22: error: \"type\" expects no type arguments, but 1 given  [type-arg]\ntemp_file.py:47: error: \"type\" expects no type arguments, but 1 given  [type-arg]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "dataprovider.py_deepseek_db0d12a8.py": "temp_file.py:369: error: Argument \"timeframe\" to \"historic_ohlcv\" of \"DataProvider\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\nFound 1 error in 1 file (checked 1 source file)\n",
    "funcdef_return_type_trailing_comma.py_deepseek_9d900532.py": "temp_file.py:2: error: Missing return statement  [empty-body]\ntemp_file.py:2: error: \"tuple\" is not subscriptable, use \"typing.Tuple\" instead  [misc]\ntemp_file.py:10: error: Missing return statement  [empty-body]\ntemp_file.py:10: error: Name \"A\" is not defined  [name-defined]\ntemp_file.py:10: error: Name \"B\" is not defined  [name-defined]\ntemp_file.py:10: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:10: error: \"list\" expects 1 type argument, but 2 given  [type-arg]\ntemp_file.py:10: error: Name \"p\" is not defined  [name-defined]\ntemp_file.py:10: error: Name \"q\" is not defined  [name-defined]\ntemp_file.py:24: error: \"tuple\" is not subscriptable, use \"typing.Tuple\" instead  [misc]\ntemp_file.py:32: error: Missing return statement  [empty-body]\ntemp_file.py:32: error: Function \"temp_file.a\" is not valid as a type  [valid-type]\ntemp_file.py:32: note: Perhaps you need \"Callable[...]\" or a callback protocol?\ntemp_file.py:32: error: Name \"b\" is not defined  [name-defined]\ntemp_file.py:32: error: \"tuple\" is not subscriptable, use \"typing.Tuple\" instead  [misc]\ntemp_file.py:39: error: Missing return statement  [empty-body]\ntemp_file.py:39: error: Name \"p\" is not defined  [name-defined]\ntemp_file.py:39: error: Name \"q\" is not defined  [name-defined]\ntemp_file.py:39: error: Name \"A\" is not defined  [name-defined]\ntemp_file.py:39: error: Name \"B\" is not defined  [name-defined]\ntemp_file.py:39: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:39: error: \"list\" expects 1 type argument, but 2 given  [type-arg]\ntemp_file.py:47: error: Missing return statement  [empty-body]\ntemp_file.py:48: error: Function \"temp_file.a\" is not valid as a type  [valid-type]\ntemp_file.py:48: note: Perhaps you need \"Callable[...]\" or a callback protocol?\ntemp_file.py:49: error: Name \"b\" is not defined  [name-defined]\ntemp_file.py:50: error: Function \"temp_file.a\" is not valid as a type  [valid-type]\ntemp_file.py:50: note: Perhaps you need \"Callable[...]\" or a callback protocol?\ntemp_file.py:50: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:50: error: \"list\" expects 1 type argument, but 2 given  [type-arg]\ntemp_file.py:60: error: Name \"cccccccccccccccccccccccccccccc\" is not defined  [name-defined]\ntemp_file.py:65: error: Missing return statement  [empty-body]\ntemp_file.py:67: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:67: error: \"list\" expects 1 type argument, but 2 given  [type-arg]\ntemp_file.py:67: error: Name \"Ccccccccccccccccccccccccccccccccccccccccccccccccccc\" is not defined  [name-defined]\ntemp_file.py:67: error: Name \"Dddddd\" is not defined  [name-defined]\ntemp_file.py:71: error: Missing return statement  [empty-body]\ntemp_file.py:71: error: Name \"Loooooooooooooooooooooooooooooooooooong\" is not defined  [name-defined]\ntemp_file.py:71: error: Name \"Loooooooooooooooooooong\" is not defined  [name-defined]\ntemp_file.py:71: error: Name \"Looooooooooooong\" is not defined  [name-defined]\ntemp_file.py:71: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:71: error: \"list\" expects 1 type argument, but 3 given  [type-arg]\ntemp_file.py:84: error: Missing return statement  [empty-body]\ntemp_file.py:85: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:85: error: \"list\" expects 1 type argument, but 2 given  [type-arg]\ntemp_file.py:100: error: Missing return statement  [empty-body]\ntemp_file.py:102: error: Name \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\" is not defined  [name-defined]\ntemp_file.py:102: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:102: error: \"list\" expects 1 type argument, but 2 given  [type-arg]\ntemp_file.py:102: error: Name \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\" is not defined  [name-defined]\ntemp_file.py:110: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:110: error: Name \"Bad\" is not defined  [name-defined]\ntemp_file.py:115: error: Missing return statement  [empty-body]\ntemp_file.py:115: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:115: error: \"list\" expects 1 type argument, but 2 given  [type-arg]\ntemp_file.py:115: error: Function \"temp_file.a\" is not valid as a type  [valid-type]\ntemp_file.py:115: note: Perhaps you need \"Callable[...]\" or a callback protocol?\ntemp_file.py:115: error: Name \"b\" is not defined  [name-defined]\ntemp_file.py:120: error: Missing return statement  [empty-body]\ntemp_file.py:123: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:123: error: \"list\" expects 1 type argument, but 2 given  [type-arg]\ntemp_file.py:123: error: Function \"temp_file.a\" is not valid as a type  [valid-type]\ntemp_file.py:123: note: Perhaps you need \"Callable[...]\" or a callback protocol?\ntemp_file.py:123: error: Name \"b\" is not defined  [name-defined]\ntemp_file.py:128: error: Missing return statement  [empty-body]\ntemp_file.py:128: error: Function \"temp_file.a\" is not valid as a type  [valid-type]\ntemp_file.py:128: note: Perhaps you need \"Callable[...]\" or a callback protocol?\ntemp_file.py:128: error: Name \"b\" is not defined  [name-defined]\ntemp_file.py:128: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:128: error: \"list\" expects 1 type argument, but 2 given  [type-arg]\ntemp_file.py:136: error: Missing return statement  [empty-body]\ntemp_file.py:139: error: Function \"temp_file.a\" is not valid as a type  [valid-type]\ntemp_file.py:139: note: Perhaps you need \"Callable[...]\" or a callback protocol?\ntemp_file.py:139: error: Name \"b\" is not defined  [name-defined]\ntemp_file.py:139: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:139: error: \"list\" expects 1 type argument, but 2 given  [type-arg]\ntemp_file.py:147: error: Missing return statement  [empty-body]\ntemp_file.py:148: error: Name \"hl\" is not defined  [name-defined]\ntemp_file.py:149: error: Name \"Buffer\" is not defined  [name-defined]\ntemp_file.py:149: error: Name \"UInt8\" is not defined  [name-defined]\ntemp_file.py:150: error: Name \"Buffer\" is not defined  [name-defined]\ntemp_file.py:150: error: Name \"Int32\" is not defined  [name-defined]\ntemp_file.py:151: error: Name \"Scalar\" is not defined  [name-defined]\ntemp_file.py:151: error: Name \"Float32\" is not defined  [name-defined]\ntemp_file.py:153: error: Name \"Buffer\" is not defined  [name-defined]\ntemp_file.py:153: error: \"tuple\" is not subscriptable, use \"typing.Tuple\" instead  [misc]\ntemp_file.py:153: error: Name \"UInt8\" is not defined  [name-defined]\nFound 80 errors in 1 file (checked 1 source file)\n",
    "context.py_deepseek_a835034c.py": "temp_file.py:314: error: Argument 1 to \"with_phases\" has incompatible type \"List[str]\"; expected \"Set[str]\"  [arg-type]\ntemp_file.py:319: error: Argument 2 to \"with_all_phases_from\" has incompatible type \"List[Any]\"; expected \"Set[str]\"  [arg-type]\ntemp_file.py:319: error: Unsupported right operand type for in (\"Optional[Set[str]]\")  [operator]\ntemp_file.py:325: error: Argument 1 to \"with_phases\" has incompatible type \"List[str]\"; expected \"Set[str]\"  [arg-type]\ntemp_file.py:336: error: Argument 1 to \"with_phases\" has incompatible type \"List[Any]\"; expected \"Set[str]\"  [arg-type]\ntemp_file.py:399: error: Argument 2 to \"_run_test_case_with_phases\" has incompatible type \"List[str]\"; expected \"Set[str]\"  [arg-type]\ntemp_file.py:399: error: Argument 3 to \"_run_test_case_with_phases\" has incompatible type \"List[str]\"; expected \"Optional[Set[str]]\"  [arg-type]\ntemp_file.py:405: error: Argument 2 to \"_run_test_case_with_phases\" has incompatible type \"List[str]\"; expected \"Set[str]\"  [arg-type]\ntemp_file.py:405: error: Argument 3 to \"_run_test_case_with_phases\" has incompatible type \"List[str]\"; expected \"Optional[Set[str]]\"  [arg-type]\ntemp_file.py:471: error: Name \"Tuple\" is not defined  [name-defined]\ntemp_file.py:471: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Tuple\")\ntemp_file.py:522: error: \"Callable[..., Any]\" has no attribute \"suite_name\"  [attr-defined]\nFound 11 errors in 1 file (checked 1 source file)\n",
    "conftest.py_deepseek_0958eae7.py": "temp_file.py:71: error: \"Tuple[_patch[MagicMock], _patch[MagicMock], _patch[MagicMock], _patch[Union[MagicMock, AsyncMock]], _patch[AsyncMock], _patch[MagicMock], _patch[MagicMock]]\" has no attribute \"__enter__\"  [attr-defined]\ntemp_file.py:71: error: \"Tuple[_patch[MagicMock], _patch[MagicMock], _patch[MagicMock], _patch[Union[MagicMock, AsyncMock]], _patch[AsyncMock], _patch[MagicMock], _patch[MagicMock]]\" has no attribute \"__exit__\"  [attr-defined]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "conftest.py_deepseek_a2345090.py": "temp_file.py:62: error: invalid syntax  [syntax]\nFound 1 error in 1 file (errors prevented further checking)\n",
    "shard_block.py_deepseek_19f36678.py": "temp_file.py:13: error: \"object\" has no attribute \"get_shard_proposer_index\"  [attr-defined]\ntemp_file.py:16: error: \"object\" has no attribute \"get_domain\"  [attr-defined]\ntemp_file.py:16: error: \"object\" has no attribute \"DOMAIN_SHARD_PROPOSAL\"  [attr-defined]\ntemp_file.py:16: error: \"object\" has no attribute \"compute_epoch_at_slot\"  [attr-defined]\ntemp_file.py:17: error: \"object\" has no attribute \"compute_signing_root\"  [attr-defined]\ntemp_file.py:38: error: \"object\" has no attribute \"get_shard_proposer_index\"  [attr-defined]\ntemp_file.py:39: error: \"object\" has no attribute \"ShardBlock\"  [attr-defined]\ntemp_file.py:47: error: \"object\" has no attribute \"SignedShardBlock\"  [attr-defined]\ntemp_file.py:58: error: \"object\" has no attribute \"ShardTransition\"  [attr-defined]\ntemp_file.py:58: error: \"object\" has no attribute \"MAX_SHARDS\"  [attr-defined]\ntemp_file.py:61: error: \"object\" has no attribute \"get_shard_transition\"  [attr-defined]\ntemp_file.py:62: error: \"object\" has no attribute \"compute_offset_slots\"  [attr-defined]\ntemp_file.py:63: error: \"object\" has no attribute \"get_latest_slot_for_shard\"  [attr-defined]\ntemp_file.py:67: error: \"object\" has no attribute \"get_shard_transition\"  [attr-defined]\ntemp_file.py:79: error: \"object\" has no attribute \"get_active_shard_count\"  [attr-defined]\ntemp_file.py:80: error: \"object\" has no attribute \"get_committee_count_per_slot\"  [attr-defined]\ntemp_file.py:80: error: \"object\" has no attribute \"compute_epoch_at_slot\"  [attr-defined]\ntemp_file.py:81: error: \"object\" has no attribute \"get_start_shard\"  [attr-defined]\ntemp_file.py:89: error: \"object\" has no attribute \"MAX_SHARD_BLOCK_SIZE\"  [attr-defined]\nFound 19 errors in 1 file (checked 1 source file)\n",
    "import_export_tests.py_deepseek_faca9124.py": "temp_file.py:72: error: The return type of a generator function should be \"Generator\" or one of its supertypes  [misc]\ntemp_file.py:168: error: No overload variant of \"zip\" matches argument types \"List[Any]\", \"List[Any]\", \"bool\"  [call-overload]\ntemp_file.py:168: note: Possible overload variants:\ntemp_file.py:168: note:     def [_T_co, _T1] __new__(cls, Iterable[_T1], /) -> zip[Tuple[_T1]]\ntemp_file.py:168: note:     def [_T_co, _T1, _T2] __new__(cls, Iterable[_T1], Iterable[_T2], /) -> zip[Tuple[_T1, _T2]]\ntemp_file.py:168: note:     def [_T_co, _T1, _T2, _T3] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], /) -> zip[Tuple[_T1, _T2, _T3]]\ntemp_file.py:168: note:     def [_T_co, _T1, _T2, _T3, _T4] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], /) -> zip[Tuple[_T1, _T2, _T3, _T4]]\ntemp_file.py:168: note:     def [_T_co, _T1, _T2, _T3, _T4, _T5] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], Iterable[_T5], /) -> zip[Tuple[_T1, _T2, _T3, _T4, _T5]]\ntemp_file.py:168: note:     def [_T_co] __new__(cls, Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], /, *iterables: Iterable[Any]) -> zip[Tuple[Any, ...]]\ntemp_file.py:227: error: No overload variant of \"zip\" matches argument types \"List[Any]\", \"List[Any]\", \"bool\"  [call-overload]\ntemp_file.py:227: note: Possible overload variants:\ntemp_file.py:227: note:     def [_T_co, _T1] __new__(cls, Iterable[_T1], /) -> zip[Tuple[_T1]]\ntemp_file.py:227: note:     def [_T_co, _T1, _T2] __new__(cls, Iterable[_T1], Iterable[_T2], /) -> zip[Tuple[_T1, _T2]]\ntemp_file.py:227: note:     def [_T_co, _T1, _T2, _T3] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], /) -> zip[Tuple[_T1, _T2, _T3]]\ntemp_file.py:227: note:     def [_T_co, _T1, _T2, _T3, _T4] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], /) -> zip[Tuple[_T1, _T2, _T3, _T4]]\ntemp_file.py:227: note:     def [_T_co, _T1, _T2, _T3, _T4, _T5] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], Iterable[_T5], /) -> zip[Tuple[_T1, _T2, _T3, _T4, _T5]]\ntemp_file.py:227: note:     def [_T_co] __new__(cls, Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], /, *iterables: Iterable[Any]) -> zip[Tuple[Any, ...]]\ntemp_file.py:314: error: Item \"None\" of \"Optional[Any]\" has no attribute \"datasource\"  [union-attr]\ntemp_file.py:314: error: Item \"None\" of \"Optional[Any]\" has no attribute \"perm\"  [union-attr]\ntemp_file.py:318: error: Item \"None\" of \"Optional[Any]\" has no attribute \"datasource_id\"  [union-attr]\ntemp_file.py:335: error: Item \"None\" of \"Optional[Any]\" has no attribute \"datasource_id\"  [union-attr]\ntemp_file.py:337: error: Item \"None\" of \"Optional[Any]\" has no attribute \"datasource\"  [union-attr]\ntemp_file.py:337: error: Item \"None\" of \"Optional[Any]\" has no attribute \"perm\"  [union-attr]\ntemp_file.py:339: error: Item \"None\" of \"Optional[Any]\" has no attribute \"datasource_id\"  [union-attr]\ntemp_file.py:341: error: Item \"None\" of \"Optional[Any]\" has no attribute \"datasource\"  [union-attr]\ntemp_file.py:341: error: Item \"None\" of \"Optional[Any]\" has no attribute \"perm\"  [union-attr]\ntemp_file.py:395: error: Item \"None\" of \"Optional[Any]\" has no attribute \"json_metadata\"  [union-attr]\ntemp_file.py:401: error: Item \"None\" of \"Optional[Any]\" has no attribute \"slices\"  [union-attr]\ntemp_file.py:402: error: Item \"None\" of \"Optional[Any]\" has no attribute \"position\"  [union-attr]\ntemp_file.py:448: error: Item \"None\" of \"Optional[Any]\" has no attribute \"id\"  [union-attr]\ntemp_file.py:449: error: Item \"None\" of \"Optional[Any]\" has no attribute \"id\"  [union-attr]\ntemp_file.py:453: error: Item \"None\" of \"Optional[Any]\" has no attribute \"json_metadata\"  [union-attr]\ntemp_file.py:498: error: Item \"None\" of \"Optional[Any]\" has no attribute \"json_metadata\"  [union-attr]\ntemp_file.py:515: error: Item \"None\" of \"Optional[Any]\" has no attribute \"created_by\"  [union-attr]\ntemp_file.py:516: error: Item \"None\" of \"Optional[Any]\" has no attribute \"changed_by\"  [union-attr]\ntemp_file.py:517: error: Item \"None\" of \"Optional[Any]\" has no attribute \"owners\"  [union-attr]\ntemp_file.py:519: error: Item \"None\" of \"Optional[Any]\" has no attribute \"slices\"  [union-attr]\ntemp_file.py:536: error: Item \"None\" of \"Optional[Any]\" has no attribute \"created_by\"  [union-attr]\ntemp_file.py:537: error: Item \"None\" of \"Optional[Any]\" has no attribute \"changed_by\"  [union-attr]\ntemp_file.py:538: error: Item \"None\" of \"Optional[Any]\" has no attribute \"owners\"  [union-attr]\ntemp_file.py:540: error: Item \"None\" of \"Optional[Any]\" has no attribute \"slices\"  [union-attr]\ntemp_file.py:551: error: Item \"None\" of \"Optional[Any]\" has no attribute \"created_by\"  [union-attr]\ntemp_file.py:552: error: Item \"None\" of \"Optional[Any]\" has no attribute \"changed_by\"  [union-attr]\ntemp_file.py:553: error: Item \"None\" of \"Optional[Any]\" has no attribute \"owners\"  [union-attr]\ntemp_file.py:555: error: Item \"None\" of \"Optional[Any]\" has no attribute \"slices\"  [union-attr]\nFound 31 errors in 1 file (checked 1 source file)\n",
    "model_card.py_deepseek_55460c7b.py": "temp_file.py:13: error: Item \"None\" of \"Optional[str]\" has no attribute \"split\"  [union-attr]\ntemp_file.py:220: error: Argument 1 to \"get_description\" has incompatible type \"Callable[..., Any]\"; expected \"Type[Any]\"  [arg-type]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "sas7bdat.py_deepseek_217b7b95.py": "temp_file.py:166: error: Value of type \"Optional[bytes]\" is not indexable  [index]\ntemp_file.py:194: error: Incompatible types in assignment (expression has type \"int\", variable has type \"bytes\")  [assignment]\ntemp_file.py:200: error: If x = b'abc' then f\"{x}\" or \"{}\".format(x) produces \"b'abc'\", not \"abc\". If this is desired behavior, use f\"{x!r}\" or \"{!r}\".format(x). Otherwise, decode the bytes  [str-bytes-safe]\ntemp_file.py:217: error: Unsupported left operand type for + (\"None\")  [operator]\ntemp_file.py:217: note: Left operand is of type \"Optional[bytes]\"\ntemp_file.py:277: error: Argument 1 to \"len\" has incompatible type \"Optional[bytes]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:279: error: Argument 1 to \"len\" has incompatible type \"Optional[bytes]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:347: error: If x = b'abc' then f\"{x}\" or \"{}\".format(x) produces \"b'abc'\", not \"abc\". If this is desired behavior, use f\"{x!r}\" or \"{!r}\".format(x). Otherwise, decode the bytes  [str-bytes-safe]\ntemp_file.py:438: error: Incompatible types in assignment (expression has type \"Union[str, bytes]\", variable has type \"bytes\")  [assignment]\ntemp_file.py:591: error: Argument 1 to \"len\" has incompatible type \"Optional[bytes]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:593: error: Argument 1 to \"len\" has incompatible type \"Optional[bytes]\"; expected \"Sized\"  [arg-type]\ntemp_file.py:596: error: Argument 1 to \"len\" has incompatible type \"Optional[bytes]\"; expected \"Sized\"  [arg-type]\nFound 11 errors in 1 file (checked 1 source file)\n",
    "device.py_deepseek_7e5392fe.py": "temp_file.py:150: error: Incompatible return value type (got \"Union[str, None, Any]\", expected \"bool\")  [return-value]\nFound 1 error in 1 file (checked 1 source file)\n",
    "calibration.py_deepseek_70684408.py": "temp_file.py:62: error: Dict entry 5 has incompatible type \"str\": \"int\"; expected \"str\": \"str\"  [dict-item]\ntemp_file.py:159: error: Dict entry 5 has incompatible type \"str\": \"Dict[str, List[float]]\"; expected \"str\": \"str\"  [dict-item]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "openapi.py_deepseek_03accd2a.py": "temp_file.py:445: error: Value of type variable \"AnyStr\" of \"urljoin\" cannot be \"Optional[str]\"  [type-var]\nFound 1 error in 1 file (checked 1 source file)\n",
    "driver.py_deepseek_a019dddb.py": "temp_file.py:35: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "conftest.py_deepseek_d36a556c.py": "temp_file.py:46: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:62: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:63: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:111: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:151: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\nFound 5 errors in 1 file (checked 1 source file)\n",
    "avatar.py_deepseek_01403713.py": "temp_file.py:38: error: \"dict\" is not subscriptable, use \"typing.Dict\" instead  [misc]\nFound 1 error in 1 file (checked 1 source file)\n",
    "conftest.py_deepseek_8f499602.py": "temp_file.py:507: error: invalid syntax  [syntax]\nFound 1 error in 1 file (errors prevented further checking)\n",
    "messages.py_deepseek_30e9304b.py": "temp_file.py:112: error: Incompatible types in assignment (expression has type \"Tuple[str, Any]\", variable has type \"Tuple[str]\")  [assignment]\nFound 1 error in 1 file (checked 1 source file)\n",
    "template_parser.py_deepseek_d1d92522.py": "temp_file.py:198: error: \"str\" has no attribute \"removeprefix\"  [attr-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "base.py_deepseek_195feea3.py": "temp_file.py:45: error: \"list\" is not subscriptable, use \"typing.List\" instead  [misc]\ntemp_file.py:53: error: \"tuple\" is not subscriptable, use \"typing.Tuple\" instead  [misc]\ntemp_file.py:60: error: \"tuple\" is not subscriptable, use \"typing.Tuple\" instead  [misc]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "alarm_control_panel.py_deepseek_8577ea27.py": "temp_file.py:23: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "test_discovery_ability.py_deepseek_36830e91.py": "temp_file.py:125: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:126: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:129: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:130: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:135: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:135: error: \"object\" has no attribute \"strip\"  [attr-defined]\ntemp_file.py:136: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:136: error: \"object\" has no attribute \"strip\"  [attr-defined]\ntemp_file.py:137: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:137: error: \"object\" has no attribute \"__iter__\" (not iterable)  [attr-defined]\ntemp_file.py:138: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:139: error: \"object\" has no attribute \"__iter__\" (not iterable)  [attr-defined]\ntemp_file.py:141: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:142: error: \"object\" has no attribute \"__iter__\" (not iterable)  [attr-defined]\ntemp_file.py:144: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:145: error: \"object\" has no attribute \"__iter__\" (not iterable)  [attr-defined]\ntemp_file.py:147: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:150: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:151: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:153: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:154: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:155: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:157: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:158: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:167: error: Argument 1 to \"distorted_value\" has incompatible type \"map[type]\"; expected \"List[<nothing>]\"  [arg-type]\ntemp_file.py:169: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:173: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:177: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:181: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:185: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:187: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:191: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:195: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:199: error: Argument \"suppress_health_check\" to \"define_test\" has incompatible type \"List[Any]\"; expected \"Tuple[Any, ...]\"  [arg-type]\ntemp_file.py:202: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:206: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:212: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:216: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:218: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:220: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:222: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:323: error: Cannot infer type argument 1 of \"define_test\"  [misc]\ntemp_file.py:324: error: Value of type \"object\" is not indexable  [index]\nFound 43 errors in 1 file (checked 1 source file)\n",
    "blocks.py_deepseek_e29f01b9.py": "temp_file.py:219: error: Name \"external_values\" is not defined  [name-defined]\ntemp_file.py:240: error: Trying to assign name \"_mgr_locs\" that is not in \"__slots__\" of type \"temp_file.Block\"  [misc]\ntemp_file.py:256: error: Name \"ensure_block_shape\" is not defined  [name-defined]\ntemp_file.py:258: error: Name \"new_block\" is not defined  [name-defined]\ntemp_file.py:363: error: Name \"maybe_coerce_values\" is not defined  [name-defined]\ntemp_file.py:535: error: Name \"ensure_block_shape\" is not defined  [name-defined]\ntemp_file.py:536: error: Name \"maybe_coerce_values\" is not defined  [name-defined]\ntemp_file.py:624: error: Name \"maybe_coerce_values\" is not defined  [name-defined]\ntemp_file.py:1033: error: Name \"ExtensionBlock\" is not defined  [name-defined]\nFound 9 errors in 1 file (checked 1 source file)\n",
    "span_based_f1_measure.py_deepseek_e66cb97e.py": "temp_file.py:65: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"Optional[BoolTensor]\")  [assignment]\ntemp_file.py:91: error: Incompatible types in assignment (expression has type \"Tensor\", variable has type \"int\")  [assignment]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "server.py_deepseek_04969163.py": "temp_file.py:134: error: \"Dict[str, Any]\" has no attribute \"set_active\"  [attr-defined]\ntemp_file.py:153: error: \"Dict[str, Any]\" has no attribute \"set_active\"  [attr-defined]\ntemp_file.py:193: error: \"Dict[str, Any]\" has no attribute \"add_profile\"  [attr-defined]\ntemp_file.py:198: error: \"Dict[str, Any]\" has no attribute \"set_active\"  [attr-defined]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "test_base_indexer.py_deepseek_5e5d0ea5.py": "temp_file.py:256: error: \"List[float]\" has no attribute \"name\"  [attr-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "test_compression.py_deepseek_8c14f213.py": "temp_file.py:23: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:92: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\ntemp_file.py:132: error: Incompatible types in assignment (expression has type \"str\", target has type \"int\")  [assignment]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "select.py_deepseek_1d2f97a4.py": "temp_file.py:104: error: Argument 1 to \"ISYBacklightSelectEntity\" has incompatible type \"**Dict[str, Union[Any, str, Any, Any, None]]\"; expected \"str\"  [arg-type]\nFound 1 error in 1 file (checked 1 source file)\n",
    "topic.py_deepseek_5018cdae.py": "temp_file.py:267: error: \"str\" has no attribute \"removeprefix\"  [attr-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "logger_utils.py_deepseek_240f4189.py": "temp_file.py:161: error: Type variable \"temp_file.T\" is unbound  [valid-type]\ntemp_file.py:161: note: (Hint: Use \"Generic[T]\" or \"Protocol[T]\" base class to bind \"T\" inside a class)\ntemp_file.py:161: note: (Hint: Use \"T\" in function signature to bind \"T\" inside a function)\nFound 1 error in 1 file (checked 1 source file)\n",
    "transport.py_deepseek_5fa62350.py": "temp_file.py:36: error: Name \"pytest.FixtureRequest\" is not defined  [name-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "raiden_service.py_deepseek_abb03416.py": "temp_file.py:431: error: Argument 1 to \"join\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\nFound 1 error in 1 file (checked 1 source file)\n",
    "file_name.py_deepseek_3fa33654.py": "temp_file.py:26: error: Name \"InferenceState\" is not defined  [name-defined]\ntemp_file.py:28: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:32: error: Name \"Callable\" is not defined  [name-defined]\ntemp_file.py:32: note: Did you forget to import it from \"typing\"? (Suggestion: \"from typing import Callable\")\ntemp_file.py:50: error: Incompatible types in assignment (expression has type \"Union[List[Any], bool]\", variable has type \"bool\")  [assignment]\ntemp_file.py:79: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:80: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:81: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:81: error: Name \"addition\" is not defined  [name-defined]\ntemp_file.py:83: error: Name \"addition\" is not defined  [name-defined]\ntemp_file.py:93: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:97: error: Argument 2 to \"_add_strings\" has incompatible type \"reversed[Any]\"; expected \"List[Any]\"  [arg-type]\ntemp_file.py:99: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:116: error: Missing return statement  [return]\ntemp_file.py:116: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:117: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:127: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:130: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:134: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:137: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:142: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:145: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:149: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:154: error: Name \"Leaf\" is not defined  [name-defined]\ntemp_file.py:156: error: Name \"Leaf\" is not defined  [name-defined]\nFound 24 errors in 1 file (checked 1 source file)\n",
    "elmo.py_deepseek_d981c2e3.py": "temp_file.py:84: error: Cannot determine type of \"_elmo_lstm\"  [has-type]\ntemp_file.py:201: error: Incompatible types in assignment (expression has type \"Callable[[Tensor, bool], Tensor]\", variable has type \"Callable[[Tensor, DefaultNamedArg(Optional[Tensor], 'out')], Tensor]\")  [assignment]\ntemp_file.py:264: error: Item \"None\" of \"Optional[Tensor]\" has no attribute \"data\"  [union-attr]\ntemp_file.py:267: error: Item \"None\" of \"Optional[Tensor]\" has no attribute \"requires_grad\"  [union-attr]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "textual_entailment_suite.py_deepseek_657c92f3.py": "temp_file.py:25: error: List item 0 has incompatible type \"Union[str, List[str]]\"; expected \"str\"  [list-item]\ntemp_file.py:27: error: List item 0 has incompatible type \"Union[str, List[str]]\"; expected \"str\"  [list-item]\ntemp_file.py:71: error: List comprehension has incompatible type List[Dict[str, str]]; expected List[Tuple[str, str]]  [misc]\ntemp_file.py:356: error: List comprehension has incompatible type List[Tuple[str, str]]; expected List[Tuple[str, List[str]]]  [misc]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "api.py_deepseek_18d40e57.py": "temp_file.py:151: error: Incompatible types in assignment (expression has type \"Optional[Any]\", variable has type \"Dict[str, Any]\")  [assignment]\nFound 1 error in 1 file (checked 1 source file)\n",
    "strings.py_deepseek_d183b9cb.py": "temp_file.py:89: error: Unsupported left operand type for + (\"None\")  [operator]\ntemp_file.py:89: note: Left operand is of type \"Optional[str]\"\ntemp_file.py:90: error: Unsupported left operand type for + (\"None\")  [operator]\ntemp_file.py:90: note: Left operand is of type \"Optional[str]\"\nFound 2 errors in 1 file (checked 1 source file)\n",
    "utils.py_deepseek_8b360116.py": "temp_file.py:46: error: No parent module -- cannot perform relative import\nFound 1 error in 1 file (errors prevented further checking)\n",
    "test_counts.py_deepseek_91638839.py": "temp_file.py:99: error: Method \"setUp\" is marked as an override, but no base method was found with this name  [misc]\nFound 1 error in 1 file (checked 1 source file)\n",
    "scheduler_tests.py_deepseek_704e35bc.py": "temp_file.py:18: error: Function \"builtins.callable\" is not valid as a type  [valid-type]\ntemp_file.py:18: note: Perhaps you meant \"typing.Callable\" instead of \"callable\"?\ntemp_file.py:19: error: callable? not callable  [misc]\ntemp_file.py:24: error: Variable \"unittest.mock.patch\" is not valid as a type  [valid-type]\ntemp_file.py:24: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:38: error: patch? has no attribute \"call_args\"  [attr-defined]\ntemp_file.py:39: error: patch? has no attribute \"call_args\"  [attr-defined]\ntemp_file.py:46: error: Variable \"unittest.mock.patch\" is not valid as a type  [valid-type]\ntemp_file.py:46: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:61: error: patch? has no attribute \"call_args\"  [attr-defined]\ntemp_file.py:69: error: Variable \"unittest.mock.patch\" is not valid as a type  [valid-type]\ntemp_file.py:69: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:83: error: patch? has no attribute \"call_args\"  [attr-defined]\ntemp_file.py:84: error: patch? has no attribute \"call_args\"  [attr-defined]\ntemp_file.py:91: error: Variable \"unittest.mock.patch\" is not valid as a type  [valid-type]\ntemp_file.py:91: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:106: error: patch? has no attribute \"call_args\"  [attr-defined]\ntemp_file.py:115: error: Variable \"unittest.mock.patch\" is not valid as a type  [valid-type]\ntemp_file.py:115: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:119: error: patch? has no attribute \"return_value\"  [attr-defined]\ntemp_file.py:130: error: patch? has no attribute \"assert_not_called\"  [attr-defined]\ntemp_file.py:139: error: Variable \"unittest.mock.patch\" is not valid as a type  [valid-type]\ntemp_file.py:139: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:149: error: patch? has no attribute \"return_value\"  [attr-defined]\ntemp_file.py:150: error: patch? has no attribute \"side_effect\"  [attr-defined]\ntemp_file.py:153: error: patch? has no attribute \"assert_called_with\"  [attr-defined]\ntemp_file.py:165: error: Variable \"unittest.mock.patch\" is not valid as a type  [valid-type]\ntemp_file.py:165: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases\ntemp_file.py:176: error: patch? has no attribute \"return_value\"  [attr-defined]\ntemp_file.py:177: error: patch? has no attribute \"side_effect\"  [attr-defined]\ntemp_file.py:180: error: patch? has no attribute \"assert_called_with\"  [attr-defined]\ntemp_file.py:181: error: patch? has no attribute \"exception\"  [attr-defined]\nFound 24 errors in 1 file (checked 1 source file)\n",
    "conftest.py_deepseek_ef4e97b9.py": "temp_file.py:48: error: invalid syntax  [syntax]\nFound 1 error in 1 file (errors prevented further checking)\n",
    "notify.py_deepseek_79a4d062.py": "temp_file.py:152: error: Incompatible types in assignment (expression has type \"SMTP\", variable has type \"SMTP_SSL\")  [assignment]\ntemp_file.py:167: error: Module \"smtplib\" does not explicitly export attribute \"socket\"  [attr-defined]\ntemp_file.py:210: error: Incompatible types in assignment (expression has type \"MIMEText\", variable has type \"MIMEMultipart\")  [assignment]\ntemp_file.py:290: error: Incompatible types in assignment (expression has type \"MIMEApplication\", variable has type \"MIMEImage\")  [assignment]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "region_detector.py_deepseek_6c3cb449.py": "temp_file.py:73: error: Incompatible return value type (got \"Tensor\", expected \"FloatTensor\")  [return-value]\ntemp_file.py:93: error: Argument 1 to \"RegionDetectorOutput\" has incompatible type \"List[FloatTensor]\"; expected \"List[Tensor]\"  [arg-type]\ntemp_file.py:93: note: \"List\" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance\ntemp_file.py:93: note: Consider using \"Sequence\" instead, which is covariant\nFound 2 errors in 1 file (checked 1 source file)\n",
    "transactions.py_deepseek_5c5a8715.py": "temp_file.py:83: error: Unsupported operand types for * (\"int\" and \"None\")  [operator]\ntemp_file.py:83: note: Right operand is of type \"Optional[int]\"\ntemp_file.py:90: error: Unsupported operand types for * (\"int\" and \"None\")  [operator]\ntemp_file.py:90: note: Right operand is of type \"Optional[int]\"\nFound 2 errors in 1 file (checked 1 source file)\n",
    "_misc.py_deepseek_e437bff3.py": "temp_file.py:199: error: Argument 1 of \"__contains__\" is incompatible with supertype \"Mapping\"; supertype defines the argument type as \"object\"  [override]\ntemp_file.py:199: note: This violates the Liskov substitution principle\ntemp_file.py:199: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides\ntemp_file.py:199: error: Argument 1 of \"__contains__\" is incompatible with supertype \"Container\"; supertype defines the argument type as \"object\"  [override]\ntemp_file.py:204: error: Accessing \"__init__\" on an instance is unsound, since instance.__init__ could be from an incompatible subclass  [misc]\nFound 3 errors in 1 file (checked 1 source file)\n",
    "test_utils.py_deepseek_5ad1280a.py": "temp_file.py:668: error: Missing return statement  [return]\nFound 1 error in 1 file (checked 1 source file)\n",
    "test_converter.py_deepseek_e9c33d06.py": "temp_file.py:63: error: Incompatible return value type (got \"List[List[str]]\", expected \"Dict[str, List[List[str]]]\")  [return-value]\ntemp_file.py:79: error: Incompatible return value type (got \"List[List[str]]\", expected \"Dict[str, List[List[str]]]\")  [return-value]\nFound 2 errors in 1 file (checked 1 source file)\n",
    "media_browser.py_deepseek_7f9ba9bb.py": "temp_file.py:85: error: Argument 1 to \"get_proxy_image_url\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\ntemp_file.py:227: error: Argument 1 to \"int\" has incompatible type \"Optional[str]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]\ntemp_file.py:266: error: Argument 1 to \"int\" has incompatible type \"Optional[str]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]\ntemp_file.py:280: error: Argument 1 to \"int\" has incompatible type \"Optional[str]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "conftest.py_deepseek_3e1f3d3a.py": "temp_file.py:50: error: invalid syntax  [syntax]\nFound 1 error in 1 file (errors prevented further checking)\n",
    "test_value_counts.py_deepseek_32e737e2.py": "temp_file.py:929: error: Name \"education\" is not defined  [name-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "test_procedure.py_deepseek_32a863d6.py": "temp_file.py:71: error: Item \"None\" of \"Optional[CompletedProcess[Any]]\" has no attribute \"stderr\"  [union-attr]\ntemp_file.py:71: error: Item \"None\" of \"Optional[CompletedProcess[Any]]\" has no attribute \"stdout\"  [union-attr]\ntemp_file.py:75: error: Item \"None\" of \"Optional[CompletedProcess[Any]]\" has no attribute \"stderr\"  [union-attr]\ntemp_file.py:80: error: Item \"None\" of \"Optional[CompletedProcess[Any]]\" has no attribute \"stderr\"  [union-attr]\ntemp_file.py:84: error: Argument 1 to \"_get_val\" of \"CattTest\" has incompatible type \"Optional[str]\"; expected \"str\"  [arg-type]\ntemp_file.py:86: error: Argument 1 to \"int\" has incompatible type \"Optional[Any]\"; expected \"Union[str, Buffer, SupportsInt, SupportsIndex, SupportsTrunc]\"  [arg-type]\ntemp_file.py:251: error: Incompatible types in assignment (expression has type \"zip[Tuple[str, List[CattTest]]]\", variable has type \"List[Tuple[str, List[CattTest]]]\")  [assignment]\nFound 7 errors in 1 file (checked 1 source file)\n",
    "test_kraken.py_deepseek_9d701995.py": "temp_file.py:34: error: Type cannot be declared in assignment to non-self attribute  [misc]\ntemp_file.py:35: error: Type cannot be declared in assignment to non-self attribute  [misc]\ntemp_file.py:71: error: Type cannot be declared in assignment to non-self attribute  [misc]\ntemp_file.py:72: error: Type cannot be declared in assignment to non-self attribute  [misc]\ntemp_file.py:134: error: Type cannot be declared in assignment to non-self attribute  [misc]\ntemp_file.py:186: error: Type cannot be declared in assignment to non-self attribute  [misc]\nFound 6 errors in 1 file (checked 1 source file)\n",
    "hive.py_deepseek_5136cf5e.py": "temp_file.py:442: error: No overload variant of \"zip\" matches argument types \"Any\", \"Any\", \"bool\"  [call-overload]\ntemp_file.py:442: note: Possible overload variants:\ntemp_file.py:442: note:     def [_T_co, _T1] __new__(cls, Iterable[_T1], /) -> zip[Tuple[_T1]]\ntemp_file.py:442: note:     def [_T_co, _T1, _T2] __new__(cls, Iterable[_T1], Iterable[_T2], /) -> zip[Tuple[_T1, _T2]]\ntemp_file.py:442: note:     def [_T_co, _T1, _T2, _T3] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], /) -> zip[Tuple[_T1, _T2, _T3]]\ntemp_file.py:442: note:     def [_T_co, _T1, _T2, _T3, _T4] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], /) -> zip[Tuple[_T1, _T2, _T3, _T4]]\ntemp_file.py:442: note:     def [_T_co, _T1, _T2, _T3, _T4, _T5] __new__(cls, Iterable[_T1], Iterable[_T2], Iterable[_T3], Iterable[_T4], Iterable[_T5], /) -> zip[Tuple[_T1, _T2, _T3, _T4, _T5]]\ntemp_file.py:442: note:     def [_T_co] __new__(cls, Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], Iterable[Any], /, *iterables: Iterable[Any]) -> zip[Tuple[Any, ...]]\nFound 1 error in 1 file (checked 1 source file)\n",
    "test_get_accessories.py_deepseek_6909180e.py": "temp_file.py:44: error: Name \"pytest.LogCaptureFixture\" is not defined  [name-defined]\nFound 1 error in 1 file (checked 1 source file)\n",
    "sensor.py_deepseek_731836cd.py": "temp_file.py:113: error: Incompatible types in assignment (expression has type \"None\", variable has type \"float\")  [assignment]\ntemp_file.py:142: error: Incompatible types in assignment (expression has type \"None\", variable has type \"str\")  [assignment]\ntemp_file.py:165: error: Incompatible types in assignment (expression has type \"float\", variable has type \"int\")  [assignment]\ntemp_file.py:190: error: Incompatible types in assignment (expression has type \"None\", variable has type \"int\")  [assignment]\ntemp_file.py:192: error: Incompatible types in assignment (expression has type \"float\", variable has type \"int\")  [assignment]\ntemp_file.py:232: error: Incompatible types in assignment (expression has type \"None\", variable has type \"int\")  [assignment]\nFound 6 errors in 1 file (checked 1 source file)\n",
    "attention_module.py_deepseek_e99ef20b.py": "temp_file.py:247: error: Incompatible return value type (got \"Tuple[Any, Optional[Tensor]]\", expected \"Tuple[Tensor, Tensor]\")  [return-value]\ntemp_file.py:346: error: Argument 3 to \"_get_attention_probs\" of \"AttentionModule\" has incompatible type \"Optional[BoolTensor]\"; expected \"Tensor\"  [arg-type]\ntemp_file.py:347: error: Argument 4 to \"_get_attention_probs\" of \"AttentionModule\" has incompatible type \"Optional[Tensor]\"; expected \"Tensor\"  [arg-type]\ntemp_file.py:360: error: Incompatible types in assignment (expression has type \"None\", variable has type \"Tensor\")  [assignment]\nFound 4 errors in 1 file (checked 1 source file)\n",
    "attestations.py_deepseek_7db2ae98.py": "temp_file.py:180: error: Need type annotation for \"attestations\" (hint: \"attestations: List[<type>] = ...\")  [var-annotated]\nFound 1 error in 1 file (checked 1 source file)\n"
}